### ISSUE TITLE
link extraction from glossary.rst is broken

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#1]
After moving docs to a seperate repo, RST file is missing.

```
Traceback (most recent call last):
  File "C:\QGIS\apps\Python39\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "D:\pycharm\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "D:\pycharm\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/source/QGISPlugIns/enmap-box/scripts/start_enmapbox.py", line 2, in <module>
    from enmapbox import EnMAPBox
  File "D:\pycharm\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\source\QGISPlugIns\enmap-box\enmapbox\__init__.py", line 409, in <module>
    from enmapbox.gui.enmapboxgui import EnMAPBox
  File "D:\pycharm\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\source\QGISPlugIns\enmap-box\enmapbox\gui\enmapboxgui.py", line 28, in <module>
    import enmapbox.gui.datasources.manager
  File "C:\QGIS\apps\qgis\python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "D:\pycharm\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\source\QGISPlugIns\enmap-box\enmapbox\gui\datasources\manager.py", line 35, in <module>
    from ..dataviews.docks import Dock
  File "C:\QGIS\apps\qgis\python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "D:\pycharm\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\source\QGISPlugIns\enmap-box\enmapbox\gui\dataviews\docks.py", line 30, in <module>
    from enmapbox.gui.mapcanvas import MapCanvas, CanvasLink
  File "C:\QGIS\apps\qgis\python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "D:\pycharm\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\source\QGISPlugIns\enmap-box\enmapbox\gui\mapcanvas.py", line 30, in <module>
    from enmapbox.gui.mimedata import containsMapLayers, extractMapLayers
  File "C:\QGIS\apps\qgis\python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "D:\pycharm\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\source\QGISPlugIns\enmap-box\enmapbox\gui\mimedata.py", line 7, in <module>
    from enmapboxprocessing.algorithm.importproductsdraganddropsupport import tryToImportSensorProducts
  File "C:\QGIS\apps\qgis\python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "D:\pycharm\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\source\QGISPlugIns\enmap-box\enmapboxprocessing\algorithm\importproductsdraganddropsupport.py", line 7, in <module>
    from enmapboxprocessing.algorithm.importdesisl1balgorithm import ImportDesisL1BAlgorithm
  File "C:\QGIS\apps\qgis\python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "D:\pycharm\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\source\QGISPlugIns\enmap-box\enmapboxprocessing\algorithm\importdesisl1balgorithm.py", line 7, in <module>
    from enmapboxprocessing.enmapalgorithm import EnMAPProcessingAlgorithm, Group
  File "C:\QGIS\apps\qgis\python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "D:\pycharm\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\source\QGISPlugIns\enmap-box\enmapboxprocessing\enmapalgorithm.py", line 25, in <module>
    from enmapboxprocessing.glossary import injectGlossaryLinks
  File "C:\QGIS\apps\qgis\python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "D:\pycharm\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\source\QGISPlugIns\enmap-box\enmapboxprocessing\glossary.py", line 10, in <module>
    with open(filename) as file:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\source\\QGISPlugIns\\enmap-box\\doc\\source\\general\\glossary.rst'
```

**Comment by janzandr** [comment]
Quick fix: copy old RST back into code repo.
This RST will get outdated over time.

**Comment by jakimowb** [comment]
You could create a script that extracts the required information from the glossary.rst in a local enmap-box-documention clone or downloads the most-recent one / branch-specific one from https://github.com/EnMAP-Box/enmap-box-documentation

**Comment by janzandr** [comment]
Note that I added an importable package to the documentation repo:
`enmap-box-documentation\enmapboxdocumentation\__init__.py`
This way the user can place the documentation whereever he wants, and the repo path can be derived via:
```
>>>import enmapboxdocumentation
enmapboxdocumentation.__file__
```

**Comment by jakimowb** [comment]
I don't it's good code-design if a dependency (enmapbox-documentation) introduces a top-level module just that the EnMAP-Box can derive its local file path. 
As long as there are not other reasons to add the documentation repositiy to the PYTHON path, I'd prefere to use an enironmental variable / assumption that the docs repo is in the same filder like the enmapbox repo to specify the ENMAPBOX_DOCUMENTATION path.

Otherwise it would be required to list `enmapboxdocumentation` in `requirements_developers.txt`, while it cannot be installed by PIP etc.

**Comment by janzandr** [comment]
> (Moreover, it's somehow curious that the EnMAP-Box source code depends on it's documentation. Should'nt it be the other way around?)

No, EnMAP-Box algorithms (in code repo) need the glossary.rst (in doc repo) to create weblinks for the algo descriptions.

**Comment by janzandr** [comment]
> As long as there are not other reasons to add the documentation repositiy to the PYTHON path, I'd prefere to [...] assumption that the docs repo is in the same filder like the enmapbox repo [...]

That's fine for me.

**Comment by janzandr** [comment]
> Otherwise it would be required to list enmapboxdocumentation in requirements_developers.txt, while it cannot be installed by PIP etc.

If a developer is suppose to build a "correct" release version for the EnMAP-Box, then the doc repo needs to be installed.

**Comment by janzandr** [comment]
glossary.rst is not correctly copied to the plugin ZIP
