### ISSUE TITLE
RasterLayerStyling panel fails to load FORCE TSI image

### ISSUE THREAD

**Issue by jakimowb** [EnMAP-Box/enmap-box#10]
How to reproduce:

1. Start EnMAP-Box 
2. Drag 'n Drop `enmap-box/tests/testdata/force/1984-2021_060-319_HL_TSA_LNDLG_NDV_TSI.tif`
   - first bands are empty / contain no-data values only
   - wavelength is set to "decimal year"
4. Open Raster Styling Panel
5. Select the `1984-2021_060-319_HL_TSA_LNDLG_NDV_TSI.tif ` to generate Error 1

Error:
```
Traceback (most recent call last):
  File "D:\Repositories\enmap-box\enmapbox\coreapps\rasterlayerstylingapp\rasterlayerstylingpanel.py", line 264, in onLayerChanged
    self.updateGui()
  File "D:\Repositories\enmap-box\enmapbox\coreapps\rasterlayerstylingapp\rasterlayerstylingpanel.py", line 185, in updateGui
    bandNo = CreateSpectralIndicesAlgorithm.findBroadBand(layer, sname, strict=True)
  File "D:\OSGeo4W\apps\Python39\lib\site-packages\typeguard\__init__.py", line 1033, in wrapper
    retval = func(*args, **kwargs)
  File "D:\Repositories\enmap-box\enmapboxprocessing\algorithm\createspectralindicesalgorithm.py", line 260, in findBroadBand
    bandNo = reader.findWavelength(wavelength)
  File "D:\OSGeo4W\apps\Python39\lib\site-packages\typeguard\__init__.py", line 1033, in wrapper
    retval = func(*args, **kwargs)
  File "D:\Repositories\enmap-box\enmapboxprocessing\rasterreader.py", line 429, in findWavelength
    wavelength_ = self.wavelength(bandNo)
  File "D:\OSGeo4W\apps\Python39\lib\site-packages\typeguard\__init__.py", line 1033, in wrapper
    retval = func(*args, **kwargs)
  File "D:\Repositories\enmap-box\enmapboxprocessing\rasterreader.py", line 483, in wavelength
    wavelength_units = self.wavelengthUnits(bandNo)
  File "D:\OSGeo4W\apps\Python39\lib\site-packages\typeguard\__init__.py", line 1033, in wrapper
    retval = func(*args, **kwargs)
  File "D:\Repositories\enmap-box\enmapboxprocessing\rasterreader.py", line 467, in wavelengthUnits
    return Utils.wavelengthUnitsLongName(units)
  File "D:\OSGeo4W\apps\Python39\lib\site-packages\typeguard\__init__.py", line 1033, in wrapper
    retval = func(*args, **kwargs)
  File "D:\Repositories\enmap-box\enmapboxprocessing\utils.py", line 637, in wavelengthUnitsLongName
    raise ValueError(f'unknown wavelength unit: {units}')
ValueError: unknown wavelength unit: decimal year
```

**Comment by jakimowb** [comment]
relates to #5

**Comment by janzandr** [comment]
Done
![image](https://user-images.githubusercontent.com/45030715/188302653-c93a293d-b57f-4fcb-960e-96e5cd812c42.png)

**Comment by janzandr** [comment]
So, instead of having all the spectral shortcut buttons (e.g. B, G, R, NIR etc.) it would be cool to have some temporal navigation buttons with actrual DateTime :-)
