### ISSUE TITLE
ModuleNotFoundError: No module named 'geetimeseriesexplorerapp' 

### ISSUE THREAD

**Issue by jakimowb** [EnMAP-Box/enmap-box#105]
EnMAP-Box cannot be started in QGIS

How to reproduce:

create and install EnMAP-Box plugin to QGIS

Error:

````
ModuleNotFoundError: No module named 'geetimeseriesexplorerapp' 
Traceback (most recent call last):
  File "F:\OSGeo4W/apps/qgis-dev/./python\qgis\utils.py", line 448, in startPlugin
    plugins[packageName].initGui()
  File "C:\Users/geo_beja/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\enmapboxplugin.py", line 91, in initGui
    self.initStandAloneAppGuis()
  File "C:\Users/geo_beja/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\enmapboxplugin.py", line 150, in initStandAloneAppGuis
    self.initCurrentLocationMapTool()
  File "C:\Users/geo_beja/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\enmapboxplugin.py", line 159, in initCurrentLocationMapTool
    from geetimeseriesexplorerapp import MapTool
  File "C:\Users/geo_beja/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "F:\OSGeo4W/apps/qgis-dev/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'geetimeseriesexplorerapp'
````

**Comment by janzandr** [comment]
Which Zip file, did you use?

**Comment by janzandr** [comment]
Ah ok, I can reproduce the error. Strange, I'm 99% sure that it worked fine some days ago.
