### ISSUE TITLE
[Processing] Stack raster layers - 'RasterWriter' object has no attribute 'removeMetadata'

### ISSUE THREAD

**Issue by thielfab** [EnMAP-Box/enmap-box#117]
```
GIS version: 3.26.3-Buenos Aires
QGIS code revision: 65e4edfdad
Qt version: 5.12.8
Python version: 3.8.10
GDAL version: 3.0.4
GEOS version: 3.8.0-CAPI-1.13.1 
PROJ version: Rel. 6.3.1, February 10th, 2020
PDAL version: 2.0.1 (git-version: Release)
Algorithm started at: 2022-10-05T09:06:16
Algorithm 'Stack raster layers' starting?
Input parameters:
{ 'band' : None, 'grid' : None, 'outputRaster' : 'TEMPORARY_OUTPUT', 'rasters' : ['/home/openshift/Documents/Week1_3/LC08_L1TP_194022_20140225_20200911_02_T1/LC08_20140225_HGW_32633.tif','/home/openshift/Documents/Week1_3/Sentinel2/S2_20190726_HGW_32633.bsq'] }

Traceback (most recent call last):
File "/home/openshift/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/site-packages/typeguard/__init__.py", line 903, in wrapper
retval = func(*args, **kwargs)
File "/home/openshift/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapboxprocessing/algorithm/translaterasteralgorithm.py", line 340, in processAlgorithm
writer.removeMetadata()
AttributeError: 'RasterWriter' object has no attribute 'removeMetadata'

Execution failed after 0.25 seconds

Loading resulting layers
Algorithm 'Stack raster layers' finished
```

**Comment by janzandr** [comment]
Should be fixed already.
