### ISSUE TITLE
'there is no matching overloaded signal' error on identify cursor location value

### ISSUE THREAD

**Issue by vprint** [EnMAP-Box/enmap-box#12]
**Reproduction :** 

1. Load the demo data
2. Use 'Reclassify by table' tools with the following parameters : 

> raster = enmap_berlin.bsq
> band number = 062
> range boundaries = min < values < max 
> Data type = Byte
> table = 
> - minimum=0, maximum=180, new value= 0
> - minimum=181, maximum=100000, new value= 1

3. Open the output raster in a new map
4.  Try to identify pixel values with 'identify cursor location value' or 'identify pixel profiles and show them in spectral library'.

**result :** 
1. identify pixel values or identify pixel profiles give an error
2. Cursor location values panel is not updated

**Error log :** 
Une erreur est survenue lors de l'éxécution du code Python: 

KeyError: 'there is no matching overloaded signal' 
Traceback (most recent call last):
  File "C:\Users/valen/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\gui\enmapboxgui.py", line 1440, in 
    lambda crs, pt, c=canvas: self.setCurrentLocation(SpatialPoint(crs, pt), canvas)
  File "C:\Users/valen/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\gui\enmapboxgui.py", line 1873, in setCurrentLocation
    self.sigCurrentLocationChanged[SpatialPoint].emit(self.mCurrentMapLocation)
KeyError: 'there is no matching overloaded signal'

Version de Python : 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
Version de QGIS : 3.24.1-Tisler Tisler, 5709b824 

Chemin Python :
C:\Users\valen\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\apps\ensomap
C:\Users\valen\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\apps\ensomap
C:\Users\valen\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\karika
C:/PROGRA~1/QGIS32~2.1/apps/qgis/./python
C:/Users/valen/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/valen/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS32~2.1/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.24.1\bin\python39.zip
C:\PROGRA~1\QGIS32~2.1\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~2.1\apps\Python39\lib
C:\Program Files\QGIS 3.24.1\bin
C:\Users\valen\AppData\Roaming\Python\Python39\site-packages
C:\PROGRA~1\QGIS32~2.1\apps\Python39
C:\PROGRA~1\QGIS32~2.1\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~2.1\apps\Python39\lib\site-packages\GDAL-3.4.1-py3.9-win-amd64.egg
C:\PROGRA~1\QGIS32~2.1\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~2.1\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~2.1\apps\Python39\lib\site-packages\Pythonwin
C:/Users/valen/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\valen\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows
C:\Users/valen/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\site-packages
C:\Users/valen/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin
C:\Users\valen\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\qgispluginsupport\qps\pyqtgraph
C:\Users\valen\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\site-packages
C:\Users\valen\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\apps
C:\Users\valen\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\coreapps
.
C:\Users\valen\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mmqgis/forms
C:\Users\valen\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\pca4cd\extlibs_windows
C:\Users/valen/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\rvt-qgis
C:\Users/valen/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\timeseriesviewerplugin
C:\Users\valen\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\timeseriesviewerplugin\eotimeseriesviewer
C:\Users/valen/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\vrtbuilderplugin
C:\Users\valen\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\vrtbuilderplugin\vrtbuilder
C:\Users\valen\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\apps\lmuapps

**Comment by vprint** [comment]
👍
