### ISSUE TITLE
Error installing enmapboxplugin.3.11.0-rc.0.zip

### ISSUE THREAD

**Issue by aloboa** [EnMAP-Box/enmap-box#131]
This is what I get when try to install from https://github.com/EnMAP-Box/enmap-box/releases/download/v3.11.0-rc.0/enmapboxplugin.3.11.0-rc.0.zip

```
Couldn't load plugin 'enmapboxplugin' due to an error when calling its initGui() method 

FileNotFoundError: [Errno 2] No such file or directory: '/home/alobo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/coreapps/geetimeseriesexplorerapp/geetimeseriesexplorerdockwidget.ui' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 448, in startPlugin
    plugins[packageName].initGui()
  File "/home/alobo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/enmapboxplugin.py", line 91, in initGui
    self.initStandAloneAppGuis()
  File "/home/alobo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/enmapboxplugin.py", line 151, in initStandAloneAppGuis
    def initCurrentLocationMapTool(self):
  File "/home/alobo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/enmapboxplugin.py", line 182, in initGeeTimeseriesExplorerGui
    # add items to be removed when unload the plugin
  File "/home/alobo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/site-packages/typeguard/__init__.py", line 903, in wrapper
    retval = func(*args, **kwargs)
  File "/home/alobo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/coreapps/geetimeseriesexplorerapp/__init__.py", line 52, in __init__
  File "/home/alobo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/coreapps/geetimeseriesexplorerapp/__init__.py", line 59, in initGui
  File "/home/alobo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/site-packages/typeguard/__init__.py", line 903, in wrapper
    retval = func(*args, **kwargs)
  File "/home/alobo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/coreapps/geetimeseriesexplorerapp/__init__.py", line 68, in initEnmapOrQgisGui
  File "/home/alobo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/coreapps/geetimeseriesexplorerapp/geetimeseriesexplorerdockwidget.py", line 158, in __init__
  File "/usr/lib/python3/dist-packages/PyQt5/uic/__init__.py", line 238, in loadUi
    return DynamicUILoader(package).loadUi(uifile, baseinstance, resource_suffix)
  File "/usr/lib/python3/dist-packages/PyQt5/uic/Loader/loader.py", line 66, in loadUi
    return self.parse(filename, resource_suffix)
  File "/usr/lib/python3/dist-packages/PyQt5/uic/uiparser.py", line 1020, in parse
    document = parse(filename)
  File "/usr/lib/python3.9/xml/etree/ElementTree.py", line 1229, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.9/xml/etree/ElementTree.py", line 569, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/alobo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/coreapps/geetimeseriesexplorerapp/geetimeseriesexplorerdockwidget.ui'


Python version: 3.9.5 (default, Nov 18 2021, 16:00:48) [GCC 10.3.0] 
QGIS version: 3.26.0-Buenos Aires Buenos Aires, 0aece2818e 

Python Path:
/home/alobo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/terminus_processing
/home/alobo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LAStools
/usr/share/qgis/python
/home/alobo/.local/share/QGIS/QGIS3/profiles/default/python
/home/alobo/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python39.zip
/usr/lib/python3.9
/usr/lib/python3.9/lib-dynload
/home/alobo/.local/lib/python3.9/site-packages
/usr/local/lib/python3.9/dist-packages
/usr/lib/python3/dist-packages
/usr/lib/python3.9/dist-packages
/home/alobo/.local/share/QGIS/QGIS3/profiles/default/python
.
/home/alobo/.local/lib/python3.9/site-packages/IPython/extensions
/home/alobo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/site-packages
/home/alobo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/qgispluginsupport/qps/pyqtgraph
/home/alobo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/site-packages
/home/alobo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/apps
/home/alobo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/coreapps
/home/alobo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/site-packages
/home/alobo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/site-packages
```

**Comment by janzandr** [comment]
Have you restarted your QGIS after the installation?

**Comment by aloboa** [comment]
> Have you restarted your QGIS after the installation?

Yes, and it seems to work. The error came up just after the installation.

**Comment by janzandr** [comment]
Problem was that we moved the GEE TSV app from _enmapbox/coreapps_ to _enmapbox/eo4qapps_.
It's unavoidable to have those import errors after the plugin installation, in such cases.
