### ISSUE TITLE
[Create RGB from Class Probabilitiy / Fraction Layer algo] RuntimeError

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#133]
_Reported by @henriDierkes ._

```
QGIS version: 3.26.2-Buenos Aires
QGIS code revision: feec3d3b12f
Qt version: 5.15.3
Python version: 3.9.5
GDAL version: 3.5.1
GEOS version: 3.10.3-CAPI-1.16.1
PROJ version: Rel. 9.0.1, June 15th, 2022
PDAL version: 2.4.2 (git-version: aee42e)
Algorithm started at: 2022-10-07T08:47:44
Algorithm 'Create RGB image from class probability/fraction layer' starting…
Input parameters:
{ 'colors' : "['#628331', '#3d9281']", 'colorsLayer' : None, 'outputRGBImage' : 'C:\\Users\\PC\\Desktop\\EnMAP\\Test_October2022\\probability.tif', 'probability' : 'C:/Users/PC/Desktop/EnMAP/Test_October2022/probability.tif' }

Create Raster [1667x1000x3](Byte) -co INTERLEAVE=BAND COMPRESS=LZW TILED=YES BIGTIFF=YES C:\Users\PC\Desktop\EnMAP\Test_October2022\probability.tif
Traceback (most recent call last):
File "C:\Users/PC/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\site-packages\typeguard\__init__.py", line 903, in wrapper
retval = func(*args, **kwargs)
File "C:\Users/PC/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapboxprocessing\algorithm\creatergbimagefromclassprobabilityalgorithm.py", line 85, in processAlgorithm
writer = driver.createLike(reader, Qgis.Byte, 3)
File "C:\Users/PC/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\site-packages\typeguard\__init__.py", line 903, in wrapper
retval = func(*args, **kwargs)
File "C:\Users/PC/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapboxprocessing\driver.py", line 100, in createLike
raster2 = self.create(dataType, provider.xSize(), provider.ySize(), nBands, provider.extent(), provider.crs())
File "C:\Users/PC/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\site-packages\typeguard\__init__.py", line 903, in wrapper
retval = func(*args, **kwargs)
File "C:\Users/PC/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapboxprocessing\driver.py", line 68, in create
raise error
File "C:\Users/PC/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapboxprocessing\driver.py", line 64, in create
gdalDataset: gdal.Dataset = gdalDriver.Create(self.filename, width, height, nBands, gdalDataType,
File "C:\OSGeo4W\apps\Python39\lib\site-packages\osgeo\gdal.py", line 1927, in Create
return _gdal.Driver_Create(self, *args, **kwargs)
RuntimeError
Execution failed after 0.11 seconds

Loading resulting layers
Algorithm 'Create RGB image from class probability/fraction layer' finished

```

**Comment by janzandr** [comment]
Can't reproduce this. The output raster probably already existed and was opened in QGIS, which resulted in the error in __gdal.Driver_Create_.

**Comment by janzandr** [comment]
@henriDierkes please reopen if you can reproduce the problem.
