### ISSUE TITLE
Create classification dataset (from categorized vector layer and feature raster) error

### ISSUE THREAD

**Issue by dpoursanidis** [EnMAP-Box/enmap-box#177]
Good morning,
Just install ver 3.11 and below the error i have when running the "Create classification dataset (from categorized vector layer and feature raster)"

QGIS version: 3.24.3-Tisler
QGIS code revision: cf22b74e
Qt version: 5.15.3
Python version: 3.9.5
GDAL version: 3.4.3
GEOS version: 3.10.2-CAPI-1.16.0
PROJ version: Rel. 9.0.0, March 1st, 2022
PDAL version: 2.3.0 (git-version: 0a6ef5)
Algorithm started at: 2022-10-10T10:36:01
Algorithm 'Create classification dataset (from categorized vector layer and feature raster)' starting…
Input parameters:
{ 'categorizedVector' : 'F:/PRISMA HERAKLION 2020/4_Paper/For_Coregistration/LCdataV2.shp', 'categoryField' : 'Type', 'coverage' : 50, 'featureRaster' : 'F:/PRISMA HERAKLION 2020/4_Paper/For_Coregistration/For_Coregistration/Prisma_2020__shifted_to__Her2015.tif', 'majorityVoting' : True, 'outputClassificationDataset' : 'TEMPORARY_OUTPUT' }

Derive categories from selected field: [Category(value='I', name='I', color='#59fb10'), Category(value='P', name='P', color='#d0419d'), Category(value='S', name='S', color='#cb5d58'), Category(value='V', name='V', color='#470224')]
Rasterize categorized vector layer
Traceback (most recent call last):
File "C:\Users/DimitrisPoursanidis/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\site-packages\typeguard\__init__.py", line 903, in wrapper
retval = func(*args, **kwargs)
File "C:\Users/DimitrisPoursanidis/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapboxprocessing\algorithm\rasterizecategorizedvectoralgorithm.py", line 179, in processAlgorithm
message, success = layer.saveDefaultStyle(QgsMapLayer.StyleCategory.AllStyleCategories)
TypeError: QgsMapLayer.saveDefaultStyle(): too many arguments

Execution failed after 0.32 seconds

Loading resulting layers
Algorithm 'Create classification dataset (from categorized vector layer and feature raster)' finished

On Friday, such issue does not exist.

Any idea?

**Comment by janzandr** [comment]
I can't reproduce this on QGIS 3.26, maybe a QGIS 3.24 problem.
@jakimowb , @thielfab , @henriDierkes can anybody test this on QGIS 3.24? 

@dpoursanidis, can you update your QGIS?

**Comment by dpoursanidis** [comment]
Am working on that now!

**Comment by dpoursanidis** [comment]
Upgrate to 3.26 and upgrate EnMAP.
When finish i had the following

Couldn't load plugin 'enmapboxplugin' due to an error when calling its initGui() method 

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\DimitrisPoursanidis\\AppData\\Roaming\\QGIS\\QGIS3\\profiles\\default\\python\\plugins\\enmapboxplugin\\enmapbox\\coreapps\\geetimeseriesexplorerapp\\geetimeseriesexplorerdockwidget.ui' 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~1.2/apps/qgis/./python\qgis\utils.py", line 448, in startPlugin
    plugins[packageName].initGui()
  File "C:\Users/DimitrisPoursanidis/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\enmapboxplugin.py", line 91, in initGui
    self.initStandAloneAppGuis()
  File "C:\Users/DimitrisPoursanidis/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\enmapboxplugin.py", line 150, in initStandAloneAppGuis
  File "C:\Users/DimitrisPoursanidis/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\enmapboxplugin.py", line 156, in initGeeTimeseriesExplorerGui
    from geetimeseriesexplorerapp import MapTool
  File "C:\Users/DimitrisPoursanidis/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\site-packages\typeguard\__init__.py", line 903, in wrapper
    retval = func(*args, **kwargs)
  File "C:\Users\DimitrisPoursanidis\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\coreapps\geetimeseriesexplorerapp\__init__.py", line 49, in __init__
  File "C:\Users\DimitrisPoursanidis\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\coreapps\geetimeseriesexplorerapp\__init__.py", line 56, in initGui
  File "C:\Users/DimitrisPoursanidis/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\site-packages\typeguard\__init__.py", line 903, in wrapper
    retval = func(*args, **kwargs)
  File "C:\Users\DimitrisPoursanidis\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\coreapps\geetimeseriesexplorerapp\__init__.py", line 76, in initEnmapOrQgisGui
  File "C:\Users\DimitrisPoursanidis\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\coreapps\geetimeseriesexplorerapp\geetimeseriesexplorerdockwidget.py", line 159, in __init__
  File "C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib\site-packages\PyQt5\uic\__init__.py", line 238, in loadUi
    return DynamicUILoader(package).loadUi(uifile, baseinstance, resource_suffix)
  File "C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib\site-packages\PyQt5\uic\Loader\loader.py", line 66, in loadUi
    return self.parse(filename, resource_suffix)
  File "C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 1020, in parse
    document = parse(filename)
  File "C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib\xml\etree\ElementTree.py", line 1229, in parse
    tree.parse(source, parser)
  File "C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib\xml\etree\ElementTree.py", line 569, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\DimitrisPoursanidis\\AppData\\Roaming\\QGIS\\QGIS3\\profiles\\default\\python\\plugins\\enmapboxplugin\\enmapbox\\coreapps\\geetimeseriesexplorerapp\\geetimeseriesexplorerdockwidget.ui'


Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.26.2-Buenos Aires Buenos Aires, feec3d3b12f 

Python Path:
C:\Users/DimitrisPoursanidis/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\open_lidar_tools
C:\Users/DimitrisPoursanidis/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\SUEWSPrepare/Modules
C:\Users/DimitrisPoursanidis/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\sextante_animove
C:\Users/DimitrisPoursanidis/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pdaltools
C:\Users/DimitrisPoursanidis/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\merge_selected_features
C:\Users/DimitrisPoursanidis/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LAStools
C:\Users/DimitrisPoursanidis/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Coregistration
C:\Users/DimitrisPoursanidis/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ArrNorm
C:/PROGRA~1/QGIS32~1.2/apps/qgis/./python
C:/Users/DimitrisPoursanidis/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/DimitrisPoursanidis/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS32~1.2/apps/qgis/./python/plugins
C:\Program Files\Hexagon\ERDAS IMAGINE 2015\usr\lib\Win32Release\python
C:\Program Files\QGIS 3.26.2\bin\python39.zip
C:\PROGRA~1\QGIS32~1.2\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib
C:\Program Files\QGIS 3.26.2\bin
C:\Users\DimitrisPoursanidis\AppData\Roaming\Python\Python39\site-packages
C:\PROGRA~1\QGIS32~1.2\apps\Python39
C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib\site-packages\Pythonwin
C:/Users/DimitrisPoursanidis/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\DimitrisPoursanidis\AppData\Local\acatama\python39
C:\Users\DimitrisPoursanidis\AppData\Local\acatama\python39\lib\site-packages
C:\Users\DimitrisPoursanidis\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\Coregistration\extlibs_windows
C:\Users\DimitrisPoursanidis\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows
C:\Users/DimitrisPoursanidis/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\site-packages
C:\Users\DimitrisPoursanidis\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\qgispluginsupport\qps\pyqtgraph
C:\Users\DimitrisPoursanidis\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\site-packages
C:\Users\DimitrisPoursanidis\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\apps
C:\Users\DimitrisPoursanidis\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\coreapps
.
C:\Users/DimitrisPoursanidis/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\FragScape\qgis_lib_mc
C:\Users\DimitrisPoursanidis\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\HCMGIS/forms
C:\Users\DimitrisPoursanidis\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgisgbifapi\vendor
C:\Users\DimitrisPoursanidis\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgisgbifapi\vendor
C:\Users/DimitrisPoursanidis/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\rvt-qgis
C:\Users/DimitrisPoursanidis/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\site-packages
C:\Users\DimitrisPoursanidis\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\site-packages

In the end, it sais that installed succesfully.

A run (RFR) shows that the error does not exist yet.

**Comment by janzandr** [comment]
Have you restarted your QGIS after updating the EnMAP-Box?

**Comment by dpoursanidis** [comment]
Yes - works fine.
I notice only that it take more time to load the application than in the previous version (3.10).

**Comment by janzandr** [comment]
_Team decision, discussed with Sebastian van der Linden and @jakimowb:_ 

We will not fix QGIS 3.24 specific bug for EnMAP-Box v3.11

Starting with EnMAP-Box 3.12, we will support both official QGIS versions (newest and LTR)

**Comment by dpoursanidis** [comment]
Thanks for the update!
Closed for now.
