### ISSUE TITLE
CatBootRegressor issue

### ISSUE THREAD

**Issue by dpoursanidis** [EnMAP-Box/enmap-box#189]
QGIS version: 3.26.3-Buenos Aires
QGIS code revision: 65e4edfdada
Qt version: 5.15.3
Python version: 3.9.5
GDAL version: 3.5.1
GEOS version: 3.10.3-CAPI-1.16.1
PROJ version: Rel. 9.1.0, September 1st, 2022
PDAL version: 2.4.3 (git-version: 6311a6)
Algorithm started at: 2022-10-12T14:57:22
Algorithm 'Regression-based unmixing' starting…
Input parameters:
{ 'allowWithinClassMixtures' : True, 'background' : 0, 'classProbabilities' : '', 'dataset' : 'C:/Users/DimitrisPoursanidis/AppData/Local/Temp/processing_kyFyWA/dae02d0d144d447997cdf421dd69582f/outputClassificationDataset.pkl', 'ensembleSize' : 1, 'includeEndmember' : True, 'mixingProbabilities' : '0.5, 0.5', 'n' : 1000, 'outputFraction' : 'TEMPORARY_OUTPUT', 'raster' : 'F:/PRISMA HERAKLION 2020/4_Paper/For_Coregistration/For_Coregistration/Prisma_2020__shifted_to__Her2015.tif', 'regressor' : 'from catboost import CatBoostRegressor\nregressor = CatBoostRegressor(n_estimators=100)', 'robustFusion' : False }

Create ensemble
Traceback (most recent call last):
File "C:\Users/DimitrisPoursanidis/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\site-packages\typeguard\__init__.py", line 903, in wrapper
retval = func(*args, **kwargs)
File "C:\Users/DimitrisPoursanidis/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapboxprocessing\algorithm\fitregressoralgorithmbase.py", line 88, in processAlgorithm
regressor.fit(dump.X, dump.y)
File "C:\Users\DimitrisPoursanidis\AppData\Roaming\Python\Python39\site-packages\catboost\core.py", line 5504, in fit
return self._fit(X, y, cat_features, None, None, None, sample_weight, None, None, None, None, baseline,
File "C:\Users\DimitrisPoursanidis\AppData\Roaming\Python\Python39\site-packages\catboost\core.py", line 2190, in _fit
with log_fixup(log_cout, log_cerr), \
File "C:\PROGRA~1\QGIS32~2.3\apps\Python39\lib\contextlib.py", line 117, in __enter__
return next(self.gen)
File "C:\Users\DimitrisPoursanidis\AppData\Roaming\Python\Python39\site-packages\catboost\core.py", line 122, in log_fixup
_set_logger(_get_stream_like_object(log_cout), _get_stream_like_object(log_cerr))
File "C:\Users\DimitrisPoursanidis\AppData\Roaming\Python\Python39\site-packages\catboost\core.py", line 114, in _get_stream_like_object
raise CatBoostError(
_catboost.CatBoostError: Expected callable object or stream-like object

Execution failed after 0.29 seconds

Loading resulting layers
Algorithm 'Regression-based unmixing' finished

I had the same issue also in past version.

Something is missing?

**Comment by janzandr** [comment]
Can't reproduce this on the current DEV version.
Please try: https://github.com/EnMAP-Box/enmap-box/releases/tag/v3.12-alpha.1
