### ISSUE TITLE
[Regression Workflow] TypeError: type of argument "meanAbsoluteError" must be either float or int

### ISSUE THREAD

**Issue by thielfab** [EnMAP-Box/enmap-box#190]
Created a regression dataset from the testdata (veg-cover-fraction_berlin_point.gpkg, enmap_berlin.bsq)

```
Algorithm started at: 2022-10-12T12:38:53
Algorithm 'Regression workflow' starting…
Input parameters:
{ 'dataset' : '/tmp/processing_qeJUOe/a64ae39ab39e4e2e9cb3843063f9c01e/outputRegressionDataset.pkl', 'nfold' : 10, 'openReport' : True, 'outputRegression' : 'TEMPORARY_OUTPUT', 'outputRegressor' : 'TEMPORARY_OUTPUT', 'outputRegressorPerformance' : 'TEMPORARY_OUTPUT', 'raster' : '/root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/exampledata/enmap_berlin.bsq', 'regressor' : "from sklearn.pipeline import make_pipeline\nfrom sklearn.model_selection import GridSearchCV\nfrom sklearn.multioutput import MultiOutputRegressor\nfrom sklearn.preprocessing import StandardScaler\nfrom sklearn.svm import LinearSVR\n\nsvr = LinearSVR()\nparam_grid = {'epsilon': [0.], 'C': [0.001, 0.01, 0.1, 1, 10, 100, 1000]}\ntunedSVR = GridSearchCV(cv=3, estimator=svr, scoring='neg_mean_absolute_error', param_grid=param_grid)\nscaledAndTunedSVR = make_pipeline(StandardScaler(), tunedSVR)\nregressor = MultiOutputRegressor(scaledAndTunedSVR)" }

Traceback (most recent call last):
File "/root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/site-packages/typeguard/__init__.py", line 903, in wrapper
retval = func(*args, **kwargs)
File "/root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapboxprocessing/algorithm/regressionperformancealgorithm.py", line 183, in processAlgorithm
statss[target.name] = accuracyAssessment(yObserved, yPredicted)
File "/root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/site-packages/typeguard/__init__.py", line 903, in wrapper
retval = func(*args, **kwargs)
File "/root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapboxprocessing/algorithm/regressionperformancealgorithm.py", line 361, in accuracyAssessment
return AccuracyAssessmentResult(
File "/root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/site-packages/typeguard/__init__.py", line 902, in wrapper
check_argument_types(memo)
File "/root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/site-packages/typeguard/__init__.py", line 748, in check_argument_types
raise exc from None
File "/root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/site-packages/typeguard/__init__.py", line 746, in check_argument_types
check_type(description, value, expected_type, memo)
File "/root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/site-packages/typeguard/__init__.py", line 648, in check_type
check_number(argname, value, expected_type)
File "/root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/site-packages/typeguard/__init__.py", line 540, in check_number
raise TypeError('type of {} must be either float or int; got {} instead'.
TypeError: type of argument "meanAbsoluteError" must be either float or int; got numpy.float32 instead

Execution failed after 10.11 seconds
```

Version 3.11.0 Code d88782d362f
QGIS version: 3.26.3-Buenos Aires
QGIS code revision: 65e4edfdad
Qt version: 5.15.3
Python version: 3.10.4
GDAL version: 3.4.1
GEOS version: 3.10.2-CAPI-1.16.0
PROJ version: Rel. 8.2.1, January 1st, 2022
PDAL version: 2.3.0 (git-version: Release)
OS version Ubuntu 22.04.1 LTS

**Comment by janzandr** [comment]
Can't reproduce this, maybe already fixed?
@thielfab, can you show an animated GIF?
Re-open if required.
