### ISSUE TITLE
[Raster Layer Styling] error when changing from multiband to singleband raster

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#213]
Can be reproduced with the following setup:
![image](https://user-images.githubusercontent.com/45030715/196801230-f0bad2d8-26bf-4f2f-aa66-d71e5999e986.png)

```
Traceback (most recent call last):
  File "D:\source\QGISPlugIns\enmap-box\enmapbox\coreapps\rasterlayerstylingapp\rasterlayerstylingpanel.py", line 274, in onLayerChanged
    self.onRendererTabChanged()
  File "D:\source\QGISPlugIns\enmap-box\enmapbox\coreapps\rasterlayerstylingapp\rasterlayerstylingpanel.py", line 366, in onRendererTabChanged
    self.updateIsBadBand(mBand)
  File "D:\source\QGISPlugIns\enmap-box\site-packages\typeguard\__init__.py", line 903, in wrapper
    retval = func(*args, **kwargs)
  File "D:\source\QGISPlugIns\enmap-box\enmapbox\coreapps\rasterlayerstylingapp\rasterlayerstylingpanel.py", line 514, in updateIsBadBand
    if RasterReader(layer).badBandMultiplier(bandNo) == 0:
  File "D:\source\QGISPlugIns\enmap-box\site-packages\typeguard\__init__.py", line 903, in wrapper
    retval = func(*args, **kwargs)
  File "D:\source\QGISPlugIns\enmap-box\enmapboxprocessing\rasterreader.py", line 517, in badBandMultiplier
    for domain in self.metadataDomainKeys(bandNo):
  File "D:\source\QGISPlugIns\enmap-box\site-packages\typeguard\__init__.py", line 903, in wrapper
    retval = func(*args, **kwargs)
  File "D:\source\QGISPlugIns\enmap-box\enmapboxprocessing\rasterreader.py", line 368, in metadataDomainKeys
    domains: List = self._gdalObject(bandNo).GetMetadataDomainList()
  File "D:\source\QGISPlugIns\enmap-box\site-packages\typeguard\__init__.py", line 903, in wrapper
    retval = func(*args, **kwargs)
  File "D:\source\QGISPlugIns\enmap-box\enmapboxprocessing\rasterreader.py", line 633, in _gdalObject
    gdalObject = self.gdalDataset.GetRasterBand(bandNo)
  File "C:\QGIS\apps\Python39\lib\site-packages\osgeo\gdal.py", line 2151, in GetRasterBand
    return _gdal.Dataset_GetRasterBand(self, *args)
RuntimeError: D:/data/sensors/enmap/ENMAP01-____L2A-DT0000004135_20221005T023547Z_010_V010106_20221014T102749Z/ENMAP01-____L2A-DT0000004135_20221005T023547Z_010_V010106_20221014T102749Z-QL_QUALITY_CIRRUS.TIF: GDALDataset::GetRasterBand(2) - Illegal band #
```

**Comment by janzandr** [comment]
fixed already

**Comment by janzandr** [comment]
Not fixed, reported again by  @lutzhutz.
![range_slider_issue](https://user-images.githubusercontent.com/45030715/203056401-18d6add5-afa3-4d7a-bdcc-bd897ea7cc9e.gif)
