### ISSUE TITLE
[flatpak] Box won't start - KeyError: '__file__'

### ISSUE THREAD

**Issue by thielfab** [EnMAP-Box/enmap-box#215]
There is a problem with the installation via [flatpak](https://www.flatpak.org/).

QGIS + dependencies were installed using the following commands:
`flatpak install org.qgis.qgis`
`flatpak install runtime/org.kde.Sdk/x86_64/5.15-21.08`
`flatpak run --devel --command=pip3 org.qgis.qgis install -r https://raw.githubusercontent.com/EnMAP-Box/enmap-box/main/requirements.txt`

After installing the plugin the following error occurs:

```
Couldn't load plugin 'enmapboxplugin' due to an error when calling its classFactory() method 

KeyError: '__file__' 
Traceback (most recent call last):
  File "/app/share/qgis/python/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/fabian/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/__init__.py", line 51, in classFactory
    plugin = EnMAPBoxPlugin(iface)
  File "/home/fabian/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/enmapboxplugin.py", line 49, in __init__
    self.initialDependencyCheck()
  File "/home/fabian/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/enmapboxplugin.py", line 63, in initialDependencyCheck
    missing = [p for p in requiredPackages() if not p.isInstalled()]
  File "/home/fabian/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/enmapboxplugin.py", line 63, in 
    missing = [p for p in requiredPackages() if not p.isInstalled()]
  File "/home/fabian/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/dependencycheck.py", line 230, in isInstalled
    spam_spec = importlib.util.find_spec(self.pyPkgName)
  File "/usr/lib/python3.9/importlib/util.py", line 103, in find_spec
    return _find_spec(fullname, parent_path)
  File "", line 925, in _find_spec
  File "/usr/lib/python3.9/site-packages/_distutils_hack/__init__.py", line 83, in find_spec
    return method()
  File "/usr/lib/python3.9/site-packages/_distutils_hack/__init__.py", line 104, in spec_for_pip
    if self.pip_imported_during_build():
  File "/usr/lib/python3.9/site-packages/_distutils_hack/__init__.py", line 115, in pip_imported_during_build
    return any(
  File "/usr/lib/python3.9/site-packages/_distutils_hack/__init__.py", line 116, in 
    frame.f_globals['__file__'].endswith('setup.py')
KeyError: '__file__'


Python version: 3.9.9 (main, Nov 10 2011, 15:00:00) [GCC 11.3.0] 
QGIS version: 3.26.3-Buenos Aires Buenos Aires, exported 

```

QGIS version | 3.26.3-Buenos Aires | QGIS code branch | Release 3.26
-- | -- | -- | --
Qt version | 5.15.6
Python version | 3.9.9
GDAL/OGR version | 3.5.2
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.11.0-CAPI-1.17.0
SQLite version | 3.36.0
PDAL version | 2.4.3
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.5
QScintilla2 version | 2.11.6
OS version | KDE Flatpak runtime
  |   |   |  
Active Python plugins
grassprovider | 2.12.99
sagaprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
db_manager | 0.1.20

System OS: Linux Mint 20.3

**Comment by thielfab** [comment]
@jakimowb can you make sense of the error?

**Comment by thielfab** [comment]
Dirty hack: Just let the function return `True` - wcgw :-D
Changing 
https://github.com/EnMAP-Box/enmap-box/blob/93d892d7de095d25cff67e6bbef71ed5abaa1901/enmapbox/dependencycheck.py#L224-L231
to 
```
    def isInstalled(self) -> bool:
        """
        Returns True if the package is installed and can be imported in python
        :return:
        :rtype:
        """
        #spam_spec = importlib.util.find_spec(self.pyPkgName)
        return True
```

**Comment by jakimowb** [comment]
If _distutils_hack an official python package?

**Comment by jakimowb** [comment]
Seems to be not: https://stackoverflow.com/questions/69038398/python-module-distutilis-hack

**Comment by thielfab** [comment]
pip itself can not be imported within python, although `pip list` clearly says it is installed and the package installation from command line works fine

`>>> import pip`
```

Traceback (most recent call last):
  File "/usr/lib/python3.9/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/app/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "/usr/lib/python3.9/site-packages/_distutils_hack/__init__.py", line 83, in find_spec
    return method()
  File "/usr/lib/python3.9/site-packages/_distutils_hack/__init__.py", line 104, in spec_for_pip
    if self.pip_imported_during_build():
  File "/usr/lib/python3.9/site-packages/_distutils_hack/__init__.py", line 115, in pip_imported_during_build
    return any(
  File "/usr/lib/python3.9/site-packages/_distutils_hack/__init__.py", line 116, in <genexpr>
    frame.f_globals['__file__'].endswith('setup.py')
KeyError: '__file__'
```
`$ flatpak run --devel --command=python3 org.qgis.qgis -m pip list | grep pip`

```
/usr/lib/python3.9/site-packages/_distutils_hack/__init__.py:35: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
pip                22.1.2

```

**Comment by jakimowb** [comment]
Maybee the pip can be replaced using [importlib](https://docs.python.org/3/library/importlib.html#module-importlib.resources) to collect the versions of installed packages.

**Comment by thielfab** [comment]
Isn't this how it is implemented at the moment in `isInstalled()`?
Maybe it would make sense to make it less "strict", i.e. something like a `try:` logic? The Box should not be stopped from loading just because some functionality of the package manager does not work. If there is a problem, maybe the package manager can be "greyed out" in the menu and a warning will be shown?
Although, so far we only observed this with flatpak environments. So not a high priority I suppose, as much as I would love to see more Linux users ;-)

**Comment by jakimowb** [comment]
@thielfab can you check if EnMAP box starts with the fix in https://github.com/EnMAP-Box/enmap-box/tree/215-flatpak-box-wont-start-keyerror ?

**Comment by thielfab** [comment]
Seems not:
```
Couldn't load plugin 'enmapboxplugin' due to an error when calling its classFactory() method 

KeyError: '__file__' 
Traceback (most recent call last):
  File "/home/fabian/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/dependencycheck.py", line 231, in isInstalled
    spam_spec = importlib.util.find_spec(self.pyPkgName)
  File "/usr/lib/python3.9/importlib/util.py", line 103, in find_spec
    return _find_spec(fullname, parent_path)
  File "", line 925, in _find_spec
  File "/usr/lib/python3.9/site-packages/_distutils_hack/__init__.py", line 83, in find_spec
    return method()
  File "/usr/lib/python3.9/site-packages/_distutils_hack/__init__.py", line 104, in spec_for_pip
    if self.pip_imported_during_build():
  File "/usr/lib/python3.9/site-packages/_distutils_hack/__init__.py", line 115, in pip_imported_during_build
    return any(
  File "/usr/lib/python3.9/site-packages/_distutils_hack/__init__.py", line 116, in 
    frame.f_globals['__file__'].endswith('setup.py')
KeyError: '__file__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/share/qgis/python/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/fabian/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/__init__.py", line 51, in classFactory
    plugin = EnMAPBoxPlugin(iface)
  File "/home/fabian/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/enmapboxplugin.py", line 49, in __init__
    self.initialDependencyCheck()
  File "/home/fabian/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/enmapboxplugin.py", line 63, in initialDependencyCheck
    missing = [p for p in requiredPackages() if not p.isInstalled()]
  File "/home/fabian/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/enmapboxplugin.py", line 63, in 
    missing = [p for p in requiredPackages() if not p.isInstalled()]
  File "/home/fabian/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/dependencycheck.py", line 236, in isInstalled
    __import__(self.pyPkgName)
  File "/app/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "", line 1007, in _find_and_load
  File "", line 982, in _find_and_load_unlocked
  File "", line 925, in _find_spec
  File "/usr/lib/python3.9/site-packages/_distutils_hack/__init__.py", line 83, in find_spec
    return method()
  File "/usr/lib/python3.9/site-packages/_distutils_hack/__init__.py", line 104, in spec_for_pip
    if self.pip_imported_during_build():
  File "/usr/lib/python3.9/site-packages/_distutils_hack/__init__.py", line 115, in pip_imported_during_build
    return any(
  File "/usr/lib/python3.9/site-packages/_distutils_hack/__init__.py", line 116, in 
    frame.f_globals['__file__'].endswith('setup.py')
KeyError: '__file__'


```

**Comment by jakimowb** [comment]
Although I like the idea of offering the EnMAP-Box via flatpak, it is not currently an officially supported installation method. I am therefore closing the issue for the time being.
