### ISSUE TITLE
location map tool is broken

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#242]
The location map tool is broken:
![image](https://user-images.githubusercontent.com/45030715/199277548-0fd3b220-ac78-4547-a4e6-e4ca58ce1780.png)

Currently, we can't plot any **Pixel Profiles**, nor can we show **Cursor Location Values**.
![image](https://user-images.githubusercontent.com/45030715/199278262-f702b44b-ea65-4835-bea1-5dbb3cfe010e.png)

Selecting a location gives the following error:
```
Traceback (most recent call last):
  File "D:\source\QGISPlugIns\enmap-box\enmapbox\gui\enmapboxgui.py", line 1435, in <lambda>
    lambda crs, pt, c=canvas: self.setCurrentLocation(SpatialPoint(crs, pt), canvas)
  File "D:\source\QGISPlugIns\enmap-box\enmapbox\gui\enmapboxgui.py", line 1876, in setCurrentLocation
    self.sigCurrentLocationChanged[SpatialPoint].emit(self.mCurrentMapLocation)
KeyError: 'there is no matching overloaded signal'

```

**Comment by janzandr** [comment]
This bug was introduced with the QGIS 3.28 release.

**Comment by jakimowb** [comment]
Does this if started from QGIS or in PyCharm only?

**Comment by janzandr** [comment]
In PyCharm only.

**Comment by janzandr** [comment]
@jakimowb, for now, I just did a quick fix that removes the broken syntax:
```
# sigCurrentLocationChanged = pyqtSignal([SpatialPoint], [SpatialPoint, QgsMapCanvas])
sigCurrentLocationChanged = pyqtSignal(list)
```

**Comment by jakimowb** [comment]
Meanwhile I found some time to run some tests related to this issue.
First of all, the syntax was not broken, signal overloading is a feature of PyQt (and necessary. See https://www.riverbankcomputing.com/static/Docs/PyQt5/signals_slots.html#connecting-disconnecting-and-emitting-signals)

However, knowing this does not fix the problem, but otherwise your workaround is no ensurance that the "no matching overloaded signale" error will not be raised somewhere else. 

Its better if we understand why this error occurs in PyCharm and not QGIS. 

I was able to reproduce it on windows 10, but curiously not on windows 11.  For testing I restored in https://github.com/EnMAP-Box/enmap-box/tree/242-location-map-tool-is-broken the previous signal definition:
 
`sigCurrentLocationChanged = pyqtSignal([SpatialPoint], [SpatialPoint, QgsMapCanvas])`

Can you @janzandr please run the tests in tests/src/issues/test_issue_242.py and report what they do print out?

**Comment by janzandr** [comment]
executed  tests/src/issues/test_issue_242.py
error is back again
```
Error
Traceback (most recent call last):
  File "D:\source\QGISPlugIns\enmap-box\tests\src\issues\test_issue_242.py", line 73, in test_location_map_tool
    enmapBox.setCurrentLocation(pt)
  File "D:\source\QGISPlugIns\enmap-box\enmapbox\gui\enmapboxgui.py", line 1876, in setCurrentLocation
    self.sigCurrentLocationChanged[SpatialPoint].emit(self.mCurrentMapLocation)
KeyError: 'there is no matching overloaded signal'
```

**Comment by janzandr** [comment]
@jakimowb, if you can't figure it out, just use the quickfix for now. Yes, it's **nice to know** why overloading syntax isn't working, but don't waste your time on it. 
Note that we don't have to use overloading to make it work (see the quickfix, where I stored all arguments into a list).

**Comment by jakimowb** [comment]
There are several other places where signal overloading is used in our code or that of other libraries.
So adding a workaround just for the sake of a local PyCharm installation is not a good idea at all.

**Comment by janzandr** [comment]
I just want to say that we need a fix (with backport to v3.11). If your time is limitted, a quickfix is fine for now.

**Comment by janzandr** [comment]
> There are several other places where signal overloading is used in our code or that of other libraries.

Are you sure?, I can't find any:
![image](https://user-images.githubusercontent.com/45030715/201320964-fa49c22b-26f4-47ab-82fa-b9e5b683f762.png)

Except in your code:
![image](https://user-images.githubusercontent.com/45030715/201321090-8a85e59f-bfd4-44e3-baab-b32d32d3793b.png)

**Comment by jakimowb** [comment]
> executed tests/src/issues/test_issue_242.py error is back again

Which is intended in this branch ("For testing I restored ..."). But what is the printout of the other test methods;
`test_print_system_info` and `test_showcase_signal_syntax`? That could help me to better understand what happens.

**Comment by jakimowb** [comment]
Seems I found the reason: QgsPointXY does not inherit from QObject

**Comment by jakimowb** [comment]
@janzandr here you find some more examples that explain you the usefullness of overloaded signals:

https://gis-ops.com/qgis-3-plugin-tutorial-pyqt-signal-slot-explained/#overloaded-signal-example

**Comment by janzandr** [comment]
> Seems I found the reason: QgsPointXY does not inherit from QObject

Nice. (But I can't see the fix. Haven't you pushed yet?)

**Comment by janzandr** [comment]
Backport still missing:
![image](https://user-images.githubusercontent.com/45030715/203032115-f6fb517a-f5d8-434a-a8cf-e3fe325d7c2d.png)
