### ISSUE TITLE
[Profile Analytics] problem with layers that have no CRS set

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#252]
![image](https://user-images.githubusercontent.com/45030715/200286447-286ac1d7-1126-4cf9-b62f-84f071b66dfe.png)

```
An error has occurred while executing Python code: 

AssertionError 
Traceback (most recent call last):
  File "C:\Users\Andreas\AppData\Roaming\QGIS\QGIS3\profiles\EnMAP-Box Develop\python\plugins\enmapboxplugin\enmapbox\eo4qapps\profileanalyticsapp\profileanalyticsdockwidget.py", line 231, in onLiveUpdate
    self.onApplyClicked()
  File "C:\Users\Andreas\AppData\Roaming\QGIS\QGIS3\profiles\EnMAP-Box Develop\python\plugins\enmapboxplugin\enmapbox\eo4qapps\profileanalyticsapp\profileanalyticsdockwidget.py", line 275, in onApplyClicked
    yValues = reader.arrayFromPixelOffsetAndSize(pixel.x(), pixel.y(), 1, 1)
  File "C:\Users/Andreas/AppData/Roaming/QGIS/QGIS3\profiles\EnMAP-Box Develop/python/plugins\enmapboxplugin\site-packages\typeguard\__init__.py", line 903, in wrapper
    retval = func(*args, **kwargs)
  File "C:\Users/Andreas/AppData/Roaming/QGIS/QGIS3\profiles\EnMAP-Box Develop/python/plugins\enmapboxplugin\enmapboxprocessing\rasterreader.py", line 230, in arrayFromPixelOffsetAndSize
    assert self.rasterUnitsPerPixel() == QSizeF(1, 1)
AssertionError
```

**Comment by janzandr** [comment]
can't reproduce, maybe already fixed
