### ISSUE TITLE
[GEE Time Series Explorer] fix problem with STAC format changes

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#283]
Previously, a single flag bitmask part had an empty list of values:
![image](https://user-images.githubusercontent.com/45030715/205653711-c4952f2b-6453-4756-9776-a7d652e618ef.png)

Now, empty values lists are skipped, and we get error:
```
Traceback (most recent call last):
  File "D:\source\QGISPlugIns\enmap-box\enmapbox\eo4qapps\geetimeseriesexplorerapp\geetimeseriesexplorerdockwidget.py", line 600, in onCollectionClicked
    self.onLoadCollectionClicked()
  File "D:\source\QGISPlugIns\enmap-box\enmapbox\eo4qapps\geetimeseriesexplorerapp\geetimeseriesexplorerdockwidget.py", line 469, in onLoadCollectionClicked
    self.updateFilterBitmask()
  File "D:\source\QGISPlugIns\enmap-box\enmapbox\eo4qapps\geetimeseriesexplorerapp\geetimeseriesexplorerdockwidget.py", line 689, in updateFilterBitmask
    values = part['values']
KeyError: 'values'
```

**Comment by janzandr** [comment]
ToDo: merge into main

**Comment by janzandr** [comment]
Can't reproduce this on DEV or v3.11.1 anymore. Probably, I haven't fetched the latest DEV commits last time!?
