### ISSUE TITLE
Old problem for a new version: Can't open PRISMA L1 hdf5 files.

### ISSUE THREAD

**Issue by danielgomescnpm** [EnMAP-Box/enmap-box#301]
Hi!

I am working with EnMAP-Box QGIS Plugin Version 3.11.1 Code 62b8390cf18 at QGIS version 3.28.1-Firenze code fde3b8fbb8.

My machine is a Dell with an Intel Core i7 1700 CPU @ 2.9 GHz 32 GB RAM running at a Windows 10 Pro 20H2

I am trying to Import PRISMA L1 products, converting them from hdf5 to Geotiff files format. But it does not work. I always get the same error message:

```
Traceback (most recent call last):
File "C:\Users/danielgomes/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\site-packages\typeguard\__init__.py", line 903, in wrapper
retval = func(*args, **kwargs)
File "C:\Users/danielgomes/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapboxprocessing\algorithm\importprismal1algorithm.py", line 153, in processAlgorithm
self.writeSpectralErrorMatrix(filenameSpectralError, he5Filename, spectralRegion, feedback)
File "C:\Users/danielgomes/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapboxprocessing\algorithm\importprismal1algorithm.py", line 254, in writeSpectralErrorMatrix
dsVnir = self.openDataset(he5Filename, key)
File "C:\Users/danielgomes/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\site-packages\typeguard\__init__.py", line 903, in wrapper
retval = func(*args, **kwargs)
File "C:\Users/danielgomes/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapboxprocessing\algorithm\importprismal1algorithm.py", line 121, in openDataset
ds: gdal.Dataset = gdal.Open(source)
File "C:\OSGeo4W\apps\Python39\lib\site-packages\osgeo\gdal.py", line 4708, in Open
return _gdal.Open(*args)
RuntimeError: `HDF5:"""R:\prisma\data\PRS_L1_STD_OFFL_20220628135917_20220628135921_0001\02_Hdf5\PRS_L1_STD_OFFL_20220628135917_20220628135921_0001.he5"""://HDFEOS/SWATHS/PRS_L1_HCO/Data_Fields/VNIR_PIXEL_SAT_ERR_MATRIX' does not exist in the file system, and is not recognized as a supported dataset name.

Execution failed after 0.06 seconds
```
I have already followed the instructions for issue#868
(https://bitbucket.org/hu-geomatics/enmap-box/issues/868/dll-importerror-for-h5py) when I deleted the folder h5py in the Appdata-Roaming directory, I downgraded the python3-h5py to version 2.10.0-1, and I even tried to install EnMAP-box using the file **_enmapboxplugin.3.11.20220912T114623.TEST.zip_**

I have even reinstalled the EnMAP-Box 3 plugin, following the instructions available at https://enmap-box.readthedocs.io/en/latest/usr_section/usr_installation.html# , using the option via command-line at Windows.

The plugin keeps giving me the same error, I would appreciate it very much if you could help me to solve this issue.

**Comment by janzandr** [comment]
In the error message it says: "://HDFEOS/SWATHS/PRS_L1_HCO/Data_Fields/**VNIR_PIXEL_SAT_ERR_MATRIX**' does not exist in the file system, and is not recognized as a supported dataset name.

Please open the HE5 file in QGIS and check if you can see the **VNIR_PIXEL_SAT_ERR_MATRIX** item:
![image](https://user-images.githubusercontent.com/45030715/208101453-9227317c-06d6-42c6-a059-5582a60266d9.png)

**Comment by danielgomescnpm** [comment]
You got the problem! I was not able to open the HDF5 file in my QGIS. Then I realized that I had to install the plugin gdal-hdf5.lib from OSGeo4W-Setup. After that, I could open the file and the importing task ran correctly. Let me show the Log file to you:

```
Reading data with h5py (v2.10.0) API: HDFEOS/SWATHS/PRS_L1_HCO/Data Fields/VNIR_PIXEL_SAT_ERR_MATRIX
Reading data with h5py (v2.10.0) API: HDFEOS/SWATHS/PRS_L1_HCO/Data Fields/SWIR_PIXEL_SAT_ERR_MATRIX
Create Raster [1000x1000x234](Byte) -co INTERLEAVE=BAND COMPRESS=LZW TILED=YES BIGTIFF=YES D:/daniel_gomes/inputData/prisma/data/PRS_L1_STD_OFFL_20220628135917_20220628135921_0001/03_Hdf5Contents/PRS_L1_STD_OFFL_20220628135917_20220628135921_0001_ERRORMATRIX.tif
Reading data with h5py (v2.10.0) API: HDFEOS/SWATHS/PRS_L1_HCO/Data Fields/VNIR_Cube
Reading data with h5py (v2.10.0) API: HDFEOS/SWATHS/PRS_L1_HCO/Data Fields/SWIR_Cube
Create Raster [1000x1000x234](UInt16) -co INTERLEAVE=BAND COMPRESS=LZW TILED=YES BIGTIFF=YES D:/daniel_gomes/inputData/prisma/data/PRS_L1_STD_OFFL_20220628135917_20220628135921_0001/03_Hdf5Contents/PRS_L1_STD_OFFL_20220628135917_20220628135921_0001.tif
Execution completed in 14.5 seconds
Execution completed in 14.52 seconds
Results:
{'outputPrisma1_spectralErrorMatrix': 'D:/daniel_gomes/inputData/prisma/data/PRS_L1_STD_OFFL_20220628135917_20220628135921_0001/03_Hdf5Contents/PRS_L1_STD_OFFL_20220628135917_20220628135921_0001_ERRORMATRIX.tif',
'outputPrismaL1_cloudMask': 'D:/daniel_gomes/inputData/prisma/data/PRS_L1_STD_OFFL_20220628135917_20220628135921_0001/03_Hdf5Contents/PRS_L1_STD_OFFL_20220628135917_20220628135921_0001_CLOUDMASK.vrt',
'outputPrismaL1_landCoverMask': 'D:/daniel_gomes/inputData/prisma/data/PRS_L1_STD_OFFL_20220628135917_20220628135921_0001/03_Hdf5Contents/PRS_L1_STD_OFFL_20220628135917_20220628135921_0001_LANDCOVERMASK.vrt',
'outputPrismaL1_panCube': 'D:/daniel_gomes/inputData/prisma/data/PRS_L1_STD_OFFL_20220628135917_20220628135921_0001/03_Hdf5Contents/PRS_L1_STD_OFFL_20220628135917_20220628135921_0001_PAN.vrt',
'outputPrismaL1_panErrorMatrix': 'D:/daniel_gomes/inputData/prisma/data/PRS_L1_STD_OFFL_20220628135917_20220628135921_0001/03_Hdf5Contents/PRS_L1_STD_OFFL_20220628135917_20220628135921_0001_PAN_ERRORMATRIX.vrt',
'outputPrismaL1_panGeolocationFields': 'D:/daniel_gomes/inputData/prisma/data/PRS_L1_STD_OFFL_20220628135917_20220628135921_0001/03_Hdf5Contents/PRS_L1_STD_OFFL_20220628135917_20220628135921_0001_PAN_GEOLOCFIELDS.vrt',
'outputPrismaL1_spectralCube': 'D:/daniel_gomes/inputData/prisma/data/PRS_L1_STD_OFFL_20220628135917_20220628135921_0001/03_Hdf5Contents/PRS_L1_STD_OFFL_20220628135917_20220628135921_0001.tif',
'outputPrismaL1_spectralGeolocationFields': 'D:/daniel_gomes/inputData/prisma/data/PRS_L1_STD_OFFL_20220628135917_20220628135921_0001/03_Hdf5Contents/PRS_L1_STD_OFFL_20220628135917_20220628135921_0001_GEOLOCFIELDS.vrt',
'outputPrismaL1_sunGlintMask': 'D:/daniel_gomes/inputData/prisma/data/PRS_L1_STD_OFFL_20220628135917_20220628135921_0001/03_Hdf5Contents/PRS_L1_STD_OFFL_20220628135917_20220628135921_0001_SUNGLINTMASK.vrt'}

Loading resulting layers
Algorithm 'Import PRISMA L1 product' finished
```

The problem was that I had to install also the gdal-hdf5.lib

Thank you for being so helpful!
