### ISSUE TITLE
Spectral Convolution Savitsky-Golay Filter issue

### ISSUE THREAD

**Issue by mbayad33** [EnMAP-Box/enmap-box#306]
I wanted to apply spectral SVG filter on a Prisma image 
the parameters were: 
kernel = Kernel1D(array=savgol_coeffs(window_length=5, polyorder=3, deriv=1))
the processing failed and I have got the error below. 

Could you please help with this issue?

Traceback (most recent call last):
              File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\site-packages\typeguard\__init__.py", line 903, in wrapper
              retval = func(*args, **kwargs)
              File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapboxprocessing\algorithm\convolutionfilteralgorithmbase.py", line 126, in processAlgorithm
              outarray = convolve(
              File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\astropy\nddata\decorators.py", line 246, in wrapper
              result = func(data, *args, **kwargs)
              File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\astropy\convolution\convolve.py", line 332, in convolve
              raise ValueError("Setting nan_treatment='interpolate' "
             ValueError: Setting nan_treatment='interpolate' requires the kernel to be normalized, but the input kernel has a sum close to zero. For a zero-sum kernel and data with NaNs, set nan_treatment='fill'.

**Comment by janzandr** [comment]
Can't reproduce this with the _enmap_berlin.bsq_ testdata.
Please share your dataset.

**Comment by mbayad33** [comment]
Sorry, the error happened actually with the following parameters:

kernel = Kernel1D(array=savgol_coeffs(window_length=5, polyorder=3, deriv=1))


The Prisma image can be downloaded from the prisma portal or you can get my image here:

https://drive.google.com/file/d/1vkuaTx8ex2zVH7UTYW9HrDVbm0q4mrNf/view?usp=share_link

**Comment by janzandr** [comment]
Ah ok, the problem is not with your data. It is because of the **deriv=1**. Can reproduce the error with the testdata as well.

**Comment by janzandr** [comment]
You need to deactivate the **Normalize kernel** setting.
![image](https://user-images.githubusercontent.com/45030715/210377785-77aa29dd-d8de-4403-b058-a060b81b8161.png)

**Comment by mbayad33** [comment]
It worked, Thank you! 
P.S.: Both "Normalize kernel" and "Interpolate no data pixel" have to be deactivated in my case.
