### ISSUE TITLE
[GEE Time Series Explorer] Collections don't load

### ISSUE THREAD

**Issue by breierlukas** [EnMAP-Box/enmap-box#339]
When I select a Collection, a Python Error occurs. It worked before. I updated everything, but the error persists.

2023-01-24T12:04:36     WARNING    Traceback (most recent call last):
              File "C:\Users\Lukas\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\eo4qapps\geetimeseriesexplorerapp\geetimeseriesexplorerdockwidget.py", line 600, in onCollectionClicked
              self.onLoadCollectionClicked()
              File "C:\Users\Lukas\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\eo4qapps\geetimeseriesexplorerapp\geetimeseriesexplorerdockwidget.py", line 442, in onLoadCollectionClicked
              eeImported, ee = importEarthEngine(False)
              File "C:\Users/Lukas/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\site-packages\typeguard\__init__.py", line 903, in wrapper
              retval = func(*args, **kwargs)
              File "C:\Users/Lukas/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\utils.py", line 56, in importEarthEngine
              import ee
              File "C:\Users/Lukas/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 42, in __wrapping_ee_import__
              _module_.Initialize(http_transport=httplib2.Http())
              File "C:\Users\Lukas\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\__init__.py", line 131, in Initialize
              data.initialize(
              File "C:\Users\Lukas\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\data.py", line 199, in initialize
              _install_cloud_api_resource()
              File "C:\Users\Lukas\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\data.py", line 258, in _install_cloud_api_resource
              _cloud_api_resource = _cloud_api_utils.build_cloud_resource(
              File "C:\Users\Lukas\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\_cloud_api_utils.py", line 178, in build_cloud_resource
              resource = build(static_discovery=False)
              File "C:\Users\Lukas\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\_cloud_api_utils.py", line 162, in build
              return discovery.build(
              File "C:\Users\Lukas\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\googleapiclient\_helpers.py", line 130, in positional_wrapper
              return wrapped(*args, **kwargs)
              File "C:\Users\Lukas\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\googleapiclient\discovery.py", line 287, in build
              content = _retrieve_discovery_doc(
              File "C:\Users\Lukas\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\googleapiclient\discovery.py", line 422, in _retrieve_discovery_doc
              resp, content = req.execute(num_retries=num_retries)
              File "C:\Users\Lukas\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\googleapiclient\_helpers.py", line 130, in positional_wrapper
              return wrapped(*args, **kwargs)
              File "C:\Users\Lukas\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\googleapiclient\http.py", line 923, in execute
              resp, content = _retry_request(
              File "C:\Users\Lukas\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\googleapiclient\http.py", line 191, in _retry_request
              resp, content = http.request(uri, method, *args, **kwargs)
              File "C:\Users\Lukas\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\google_auth_httplib2.py", line 209, in request
              self.credentials.before_request(self._request, method, uri, request_headers)
              File "C:\Users\Lukas\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\google\auth\credentials.py", line 134, in before_request
              self.refresh(request)
              File "C:\Users\Lukas\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\google\oauth2\credentials.py", line 335, in refresh
              ) = reauth.refresh_grant(
              File "C:\Users\Lukas\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\google\oauth2\reauth.py", line 349, in refresh_grant
              _client._handle_error_response(response_data, retryable_error)
              File "C:\Users\Lukas\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\google\oauth2\_client.py", line 69, in _handle_error_response
              raise exceptions.RefreshError(

**Comment by janzandr** [comment]
Maybe not a problem with the EnMAP-Box, but the EE authentification itself.
Please follow the intructions here: https://gee-community.github.io/qgis-earthengine-plugin/

Is this code working, when executed inside the QGIS Python Console?:
```
>>> import ee
>>> print(ee.String('Hello World from EE!').getInfo())
Hello World from EE!
```

**Comment by breierlukas** [comment]
EE Authentication had to be renewed.  Sorry for the inconvenience!
