### ISSUE TITLE
[Create regression dataset (from continuous-valued vector layer and feature raster)] extent mismatch error

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#341]
When using the testdata:
![image](https://user-images.githubusercontent.com/45030715/214295622-2f72eff3-a8cc-4bd9-8858-42ffac1b269c.png)

We get the following error:
```
QGIS version: 3.28.2-Firenze
Qt version: 5.15.6
Python version: 3.10.8
GDAL version: 3.6.2
GEOS version: 3.11.1-CAPI-1.17.1
PROJ version: Rel. 9.1.0, September 1st, 2022
PDAL version: 2.4.3 (git-version: Release)
Algorithm started at: 2023-01-24T13:45:46
Algorithm 'Create regression dataset (from continuous-valued vector layer and feature raster)' starting…
Input parameters:
{ 'continuousVector' : 'D:/source/QGISPlugIns/enmap-box/enmapbox/exampledata/veg-cover-fraction_berlin_point.gpkg|layername=veg-cover-fraction_berlin_point', 'featureRaster' : 'D:/source/QGISPlugIns/enmap-box/enmapbox/exampledata/enmap_berlin.bsq', 'outputRegressionDataset' : 'TEMPORARY_OUTPUT', 'targetFields' : [] }

Rasterize continuous-valued vector layer
Sample data
Traceback (most recent call last):
File "D:\source\QGISPlugIns\enmap-box\site-packages\typeguard\_decorators.py", line 139, in wrapper
retval = func(*args, **kwargs)
File "D:\source\QGISPlugIns\enmap-box\enmapboxprocessing\algorithm\prepareregressiondatasetfromcontinuousvectoralgorithm.py", line 105, in processAlgorithm
X, y = PrepareRegressionDatasetFromContinuousRasterAlgorithm.sampleData(
File "D:\source\QGISPlugIns\enmap-box\site-packages\typeguard\_decorators.py", line 139, in wrapper
retval = func(*args, **kwargs)
File "D:\source\QGISPlugIns\enmap-box\enmapboxprocessing\algorithm\prepareregressiondatasetfromcontinuousrasteralgorithm.py", line 102, in sampleData
assert raster.extent() == regression.extent()
AssertionError

Execution failed after 0.42 seconds

Loading resulting layers
Algorithm 'Create regression dataset (from continuous-valued vector layer and feature raster)' finished
QGIS version: 3.28.2-Firenze
Qt version: 5.15.6
Python version: 3.10.8
GDAL version: 3.6.2
GEOS version: 3.11.1-CAPI-1.17.1
PROJ version: Rel. 9.1.0, September 1st, 2022
PDAL version: 2.4.3 (git-version: Release)
Algorithm started at: 2023-01-24T13:46:05
Algorithm 'Create regression dataset (from continuous-valued vector layer and feature raster)' starting…
Input parameters:
{ 'continuousVector' : 'D:/source/QGISPlugIns/enmap-box/enmapbox/exampledata/veg-cover-fraction_berlin_point.gpkg|layername=veg-cover-fraction_berlin_point', 'featureRaster' : 'D:/source/QGISPlugIns/enmap-box/enmapbox/exampledata/enmap_berlin.bsq', 'outputRegressionDataset' : 'TEMPORARY_OUTPUT', 'targetFields' : [' total vegetation cover fraction'] }

Rasterize continuous-valued vector layer
Sample data
Traceback (most recent call last):
File "D:\source\QGISPlugIns\enmap-box\site-packages\typeguard\_decorators.py", line 139, in wrapper
retval = func(*args, **kwargs)
File "D:\source\QGISPlugIns\enmap-box\enmapboxprocessing\algorithm\prepareregressiondatasetfromcontinuousvectoralgorithm.py", line 105, in processAlgorithm
X, y = PrepareRegressionDatasetFromContinuousRasterAlgorithm.sampleData(
File "D:\source\QGISPlugIns\enmap-box\site-packages\typeguard\_decorators.py", line 139, in wrapper
retval = func(*args, **kwargs)
File "D:\source\QGISPlugIns\enmap-box\enmapboxprocessing\algorithm\prepareregressiondatasetfromcontinuousrasteralgorithm.py", line 102, in sampleData
assert raster.extent() == regression.extent()
AssertionError

Execution failed after 0.15 seconds

Loading resulting layers
Algorithm 'Create regression dataset (from continuous-valued vector layer and feature raster)' finished
```

**Comment by janzandr** [comment]
Note that, this seam to be a problem in the Mambaforge QGIS 3.28.2 environment. Can't be replicated inside OSGeo4W QGIS 3.28.2

**Comment by janzandr** [comment]
Works fine in Mambaforge QGIS 3.30.0
