### ISSUE TITLE
Several unit test errors

### ISSUE THREAD

**Issue by jakimowb** [EnMAP-Box/enmap-box#366]
Several unit tests are broken. Probably easy to fix, here is a summary:
# tests/enmap-box/enmapbox/coreapps/multisourcemultibandcolorrendererapp/test_multisourcemultibandcolorrenderer.py
```
  File "F:\Repositories\enmap-box\tests\enmap-box\enmapbox\coreapps\decorrelationstretchapp\test_decorrelationstretchrenderer.py", line 10, in <module>
    from enmapboxprocessing.test.testcase import TestCase
  File "F:\OSGeo4W\apps\qgis\python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'enmapboxprocessing.test'
```
# tests/enmap-box/enmapbox/gui/widgets/test_CodeEditWidget.py
```
  File "F:\Repositories\enmap-box\tests\enmap-box\enmapbox\gui\widgets\test_MultipleMapLayerSelectionWidget.py", line 2, in <module>
    from enmapbox.gui.widgets.multiplemaplayerselectionwidget import MultipleMapLayerSelectionWidget
ImportError: cannot import name 'MultipleMapLayerSelectionWidget' from 'enmapbox.gui.widgets.multiplemaplayerselectionwidget' (F:\Repositories\enmap-box\enmapbox\gui\widgets\multiplemaplayerselectionwidget\__init__.py)

```
# tests/enmap-box/src/test_enmapboxtestdata.py (many):
![grafik](https://user-images.githubusercontent.com/1404870/220381325-a0f5ff12-9da4-467f-b1b8-b3624a06a8b1.png)

# tests/enmap-box/enmapboxprocessing/algorithm:
many fails, many UserWarnings and 

![grafik](https://user-images.githubusercontent.com/1404870/220383827-1af4bcf3-3bd2-4255-85cb-2fe7f9bf94ea.png)

# tests/src/coreapps/test_reclassifyapp.py
```
Error
Traceback (most recent call last):
  File "F:\Repositories\enmap-box\tests\src\coreapps\test_reclassifyapp.py", line 145, in test_reclassify
    dsDst = reclassify(pathSrc, pathDst, csDst, LUT, drvDst='ENVI')
TypeError: reclassify() got an unexpected keyword argument 'drvDst'

```

**Comment by janzandr** [comment]
Yes, unittests need to be overhauled.

**Comment by jakimowb** [comment]
Tested with mamba forge QGIS 3.28: F = failed, s = skipped.

```
tests/enmap-box/enmapbox/coreapps/bivariatecolorrasterrendererapp/test_bivariatecolorrasterrenderer.py .F.                                                                                                                        [ 12%]
tests/enmap-box/enmapbox/coreapps/classfractionstatisticsapp/test_classfractionrenderer.py ...                                                                                                                                    [ 24%]
tests/enmap-box/enmapbox/coreapps/decorrelationstretchapp/test_decorrelationstretchrenderer.py ..F                                                                                                                                [ 36%]
tests/enmap-box/enmapbox/coreapps/multisourcemultibandcolorrendererapp/test_multisourcemultibandcolorrenderer.py ...                                                                                                              [ 48%]
tests/enmap-box/enmapbox/gui/widgets/test_CodeEditWidget.py .                                                                                                                                                                     [ 52%]
tests/enmap-box/enmapbox/gui/widgets/test_MultipleMapLayerSelectionWidget.py F                                                                                                                                                    [ 56%]
tests/enmap-box/enmapboxprocessing/test_glossary.py ....                                                                                                                                                                          [ 72%]
tests/enmap-box/enmapboxprocessing/test_numpyutils.py ......                                                                                                                                                                      [ 96%]
tests/enmap-box/src/test_enmapboxtestdata.py .                                                                                                                                                                                    [100%]

...

FAILED tests/enmap-box/enmapbox/coreapps/bivariatecolorrasterrendererapp/test_bivariatecolorrasterrenderer.py::TestDualbandPseudocolorRenderer::test - FileNotFoundError: [Errno 2] No such file or directory: 'colorplane.txt'
FAILED tests/enmap-box/enmapbox/coreapps/decorrelationstretchapp/test_decorrelationstretchrenderer.py::TestClassFractionRenderer::test_enmap - sklearn.utils._param_validation.InvalidParameterError: The 'feature_range' parameter of MinMaxScaler must be an instance of 'tuple'. Got [0, 255] instead.
FAILED tests/enmap-box/enmapbox/gui/widgets/test_MultipleMapLayerSelectionWidget.py::TestMultipleMapLayerSelectionWidget::test_widget - Exception: QgsProject layers store is not empty: TestMultipleMapLayerSelectionWidget::test_widget
=

```

**Comment by janzandr** [comment]
Unittests are running, accept the ones from #434
