### ISSUE TITLE
typeguard.TypeCheckError: mList is not an instance of PyQt5.QtWidgets.QListWidget

### ISSUE THREAD

**Issue by danschef** [EnMAP-Box/enmap-box#398]
After updating to QGIS 3.30.0 and to typeguard 3.0.1, the EnMAP-Box (3.12 alpha9) plugin cannot be loaded. I get the following error:

```python
Konnte Erweiterung 'enmapboxplugin' nicht laden aufgrund eines Fehlers beim Aufruf der initGui() Methode 

typeguard.TypeCheckError: mList is not an instance of PyQt5.QtWidgets.QListWidget 
Traceback (most recent call last):
  File "D:\Programme/mambaforge/envs/enpt_full/Library/./python\qgis\utils.py", line 448, in startPlugin
    plugins[packageName].initGui()
  File "C:\Users/danschef/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\enmapboxplugin.py", line 106, in initGui
    self.initStandAloneAppGuis()
  File "C:\Users/danschef/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\enmapboxplugin.py", line 165, in initStandAloneAppGuis
    self.initGeeTimeseriesExplorerGui()
  File "C:\Users/danschef/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\enmapboxplugin.py", line 201, in initGeeTimeseriesExplorerGui
    self.geeTimeseriesExplorerApp = GeeTimeseriesExplorerApp(None, iface, self.currentLocationMapTool)
  File "C:\Users\danschef\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\eo4qapps\geetimeseriesexplorerapp\__init__.py", line 52, in __init__
    self.initGui()
  File "C:\Users\danschef\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\eo4qapps\geetimeseriesexplorerapp\__init__.py", line 59, in initGui
    self.initEnmapOrQgisGui(self.interface)
  File "C:\Users\danschef\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\eo4qapps\geetimeseriesexplorerapp\__init__.py", line 68, in initEnmapOrQgisGui
    self.mainDock = GeeTimeseriesExplorerDockWidget(parent=self.parent())
  File "C:\Users\danschef\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\eo4qapps\geetimeseriesexplorerapp\geetimeseriesexplorerdockwidget.py", line 199, in __init__
    self.initSpectralIndices()
  File "C:\Users\danschef\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\eo4qapps\geetimeseriesexplorerapp\geetimeseriesexplorerdockwidget.py", line 285, in initSpectralIndices
    mList: QListWidget = mAsiLists.get(spec['type'])
  File "D:\Programme\mambaforge\envs\enpt_full\lib\site-packages\typeguard\_functions.py", line 264, in check_variable_assignment
    check_type_internal(obj, expected_type, memo)
  File "D:\Programme\mambaforge\envs\enpt_full\lib\site-packages\typeguard\_checkers.py", line 671, in check_type_internal
    raise TypeCheckError(f"is not an instance of {qualified_name(origin_type)}")
typeguard.TypeCheckError: mList is not an instance of PyQt5.QtWidgets.QListWidget


Python-Version: 3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:14:58) [MSC v.1929 64 bit (AMD64)] 
QGIS-Version: 3.30.0-'s-Hertogenbosch 's-Hertogenbosch, exported
```

<details> 
  <summary>Here is the environment.</summary>

```bash
(enpt_full) >conda list
#
# Name                    Version                   Build  Channel
_py-xgboost-mutex         2.0                       cpu_0    conda-forge
acwater                   0.2.6                    pypi_0    pypi
alabaster                 0.7.12                   pypi_0    pypi
ansi2html                 1.8.0                    pypi_0    pypi
aom                       3.5.0                h63175ca_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
arosics                   1.8.1           py310h5588dad_0    conda-forge
astroid                   2.12.13                  pypi_0    pypi
astropy                   5.2.1           py310h9b08ddd_0    conda-forge
attrs                     22.2.0             pyh71513ae_0    conda-forge
babel                     2.11.0                   pypi_0    pypi
beautifulsoup4            4.12.0             pyha770c72_0    conda-forge
blas                      2.116                       mkl    conda-forge
blas-devel                3.9.0              16_win64_mkl    conda-forge
bleach                    6.0.0              pyhd8ed1ab_0    conda-forge
blosc                     1.21.3               hdccc3a2_0    conda-forge
bokeh                     2.4.3              pyhd8ed1ab_3    conda-forge
boost-cpp                 1.78.0               h9f4b32c_1    conda-forge
branca                    0.6.0              pyhd8ed1ab_0    conda-forge
brotli                    1.0.9                hcfcfb64_8    conda-forge
brotli-bin                1.0.9                hcfcfb64_8    conda-forge
brotlipy                  0.7.0           py310h8d17308_1005    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
c-blosc2                  2.7.1                h183a6f4_0    conda-forge
ca-certificates           2022.12.7            h5b45459_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cachetools                5.3.0              pyhd8ed1ab_0    conda-forge
cairo                     1.16.0            hd694305_1014    conda-forge
cartopy                   0.21.1          py310h5081e89_0    conda-forge
catboost                  1.1.1           py310h5588dad_2    conda-forge
cdsapi                    0.6.1              pyhd8ed1ab_0    conda-forge
cerberus                  1.3.4              pyhd8ed1ab_0    conda-forge
ceres-solver              2.1.0                hb02fd38_1    conda-forge
certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py310h628cb3f_3    conda-forge
cfitsio                   4.2.0                h9ebe7e4_0    conda-forge
cftime                    1.6.2           py310h9b08ddd_1    conda-forge
charls                    2.4.1                h1537add_0    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
click                     8.1.3           win_pyhd8ed1ab_2    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.7.2              pyhd8ed1ab_1    conda-forge
cloudpickle               2.2.1              pyhd8ed1ab_0    conda-forge
cmocean                   2.0                        py_3    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
colorcet                  3.0.1              pyhd8ed1ab_0    conda-forge
colorspacious             1.1.2              pyh24bf2e0_0    conda-forge
configobj                 5.0.8              pyhd8ed1ab_0    conda-forge
contourpy                 1.0.7           py310h232114e_0    conda-forge
coverage                  7.2.2           py310h8d17308_0    conda-forge
cryptography              39.0.2          py310h6e82f81_0    conda-forge
curl                      7.88.1               h68f0423_1    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cython                    0.29.33         py310h00ffb61_0    conda-forge
cytoolz                   0.12.0          py310h8d17308_1    conda-forge
dask-core                 2023.3.1           pyhd8ed1ab_0    conda-forge
dataclasses               0.8                pyhc8e2a94_3    conda-forge
dav1d                     1.0.0                h8ffe710_1    conda-forge
dicttoxml                 1.7.16             pyhd8ed1ab_0    conda-forge
dill                      0.3.6              pyhd8ed1ab_1    conda-forge
docutils                  0.17.1                   pypi_0    pypi
draco                     1.5.6                h181d51b_0    conda-forge
eccodes                   2.29.0               h23b630a_0    conda-forge
ecmwf-api-client          1.6.3              pyhd8ed1ab_0    conda-forge
eigen                     3.4.0                h2d74725_0    conda-forge
enpt                      0.19.1             pyhd8ed1ab_0    conda-forge
enpt-enmapboxapp          0.7.5                    pypi_0    pypi
et_xmlfile                1.1.0              pyhd8ed1ab_0    conda-forge
exceptiongroup            1.1.0                    pypi_0    pypi
exiv2                     0.27.6               hadc2d18_1    conda-forge
expat                     2.5.0                h1537add_0    conda-forge
fake-useragent            1.1.1                    pypi_0    pypi
fftw                      3.3.10          nompi_h38027f0_106    conda-forge
filelock                  3.10.0             pyhd8ed1ab_0    conda-forge
fiona                     1.9.1           py310h4a685fe_0    conda-forge
flake8                    6.0.0                    pypi_0    pypi
folium                    0.14.0             pyhd8ed1ab_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.2               hbde0cde_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.39.2          py310h8d17308_0    conda-forge
freeglut                  3.2.2                h0e60522_1    conda-forge
freetype                  2.12.1               h546665d_1    conda-forge
freexl                    1.0.6                h67ca5e6_1    conda-forge
fribidi                   1.0.10               h8d14728_0    conda-forge
fsspec                    2023.3.0           pyhd8ed1ab_1    conda-forge
future                    0.18.3             pyhd8ed1ab_0    conda-forge
gdal                      3.6.2           py310h644bc08_9    conda-forge
gdown                     4.6.4              pyhd8ed1ab_0    conda-forge
geoarray                  0.16.1          py310h5588dad_0    conda-forge
geojson                   3.0.1              pyhd8ed1ab_0    conda-forge
geopandas                 0.12.2             pyhd8ed1ab_0    conda-forge
geopandas-base            0.12.2             pyha770c72_0    conda-forge
geos                      3.11.1               h1537add_0    conda-forge
geotiff                   1.7.1                hc256dc0_6    conda-forge
getopt-win32              0.1                  h8ffe710_0    conda-forge
gettext                   0.21.1               h5728263_0    conda-forge
gflags                    2.2.2             ha925a31_1004    conda-forge
giflib                    5.2.1                h64bf75a_3    conda-forge
glib                      2.74.1               h12be248_1    conda-forge
glib-tools                2.74.1               h12be248_1    conda-forge
glog                      0.6.0                h4797de2_0    conda-forge
glymur                    0.12.2             pyhd8ed1ab_0    conda-forge
graphite2                 1.3.13                     1000    conda-forge
graphviz                  7.1.0                h51cb2cd_0    conda-forge
gsl                       2.7                  hdfb1a43_0    conda-forge
gst-plugins-base          1.22.0               h001b923_2    conda-forge
gstreamer                 1.22.0               h6b5321d_2    conda-forge
gts                       0.7.6                h7c369d9_2    conda-forge
h5py                      3.8.0           nompi_py310hae7a582_100    conda-forge
harfbuzz                  6.0.0                he256f1b_0    conda-forge
hdf4                      4.2.15               h1b1b6ef_5    conda-forge
hdf5                      1.12.2          nompi_h57737ce_101    conda-forge
holoviews                 1.15.4             pyhd8ed1ab_0    conda-forge
htmlmin                   0.1.12                   pypi_0    pypi
httplib2                  0.21.0             pyhd8ed1ab_0    conda-forge
icu                       70.1                 h0e60522_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
imagecodecs               2023.1.23       py310h35c0596_0    conda-forge
imageio                   2.26.0             pyh24c5eb1_0    conda-forge
imagesize                 1.4.1                    pypi_0    pypi
importlib-metadata        6.1.0              pyha770c72_0    conda-forge
importlib_metadata        6.1.0                hd8ed1ab_0    conda-forge
iniconfig                 1.1.1                    pypi_0    pypi
intel-openmp              2023.0.0         h57928b3_25922    conda-forge
iso8601                   1.1.0              pyhd8ed1ab_0    conda-forge
isort                     5.11.4                   pypi_0    pypi
jasper                    2.0.33               hc2e4405_1    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
joblib                    1.2.0              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h8ffe710_2    conda-forge
jsmin                     3.0.1              pyhd8ed1ab_0    conda-forge
jxrlib                    1.1                  h8ffe710_2    conda-forge
kealib                    1.5.0                h61be68b_0    conda-forge
kiwisolver                1.4.4           py310h232114e_1    conda-forge
krb5                      1.20.1               heb0366b_0    conda-forge
laz-perf                  3.3.0                h91493d7_0    conda-forge
lazy-object-proxy         1.8.0                    pypi_0    pypi
lcms2                     2.15                 ha5c8aab_0    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libaec                    1.0.6                h63175ca_1    conda-forge
libavif                   0.11.1               h8f5c5bc_0    conda-forge
libblas                   3.9.0              16_win64_mkl    conda-forge
libbrotlicommon           1.0.9                hcfcfb64_8    conda-forge
libbrotlidec              1.0.9                hcfcfb64_8    conda-forge
libbrotlienc              1.0.9                hcfcfb64_8    conda-forge
libcblas                  3.9.0              16_win64_mkl    conda-forge
libclang                  15.0.7          default_h77d9078_1    conda-forge
libclang13                15.0.7          default_h77d9078_1    conda-forge
libcurl                   7.88.1               h68f0423_1    conda-forge
libdeflate                1.17                 hcfcfb64_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libgd                     2.3.3                hf5a96e7_4    conda-forge
libgdal                   3.6.2                h221c0cb_9    conda-forge
libglib                   2.74.1               he8f3873_1    conda-forge
libhwloc                  2.9.0                h51c2c0f_0    conda-forge
libiconv                  1.17                 h8ffe710_0    conda-forge
libjpeg-turbo             2.1.4                hcfcfb64_0    conda-forge
libkml                    1.3.0             hf2ab4e4_1015    conda-forge
liblapack                 3.9.0              16_win64_mkl    conda-forge
liblapacke                3.9.0              16_win64_mkl    conda-forge
libnetcdf                 4.9.1           nompi_hc41bf00_101    conda-forge
libogg                    1.3.4                h8ffe710_1    conda-forge
libpng                    1.6.39               h19919ed_0    conda-forge
libpq                     15.2                 ha9684e8_0    conda-forge
libprotobuf               3.21.12              h12be248_0    conda-forge
librttopo                 1.1.0               he22b5cd_12    conda-forge
libspatialindex           1.9.3                h39d44d4_4    conda-forge
libspatialite             5.0.1               hfdcade0_23    conda-forge
libsqlite                 3.40.0               hcfcfb64_0    conda-forge
libssh2                   1.10.0               h9a1e1f7_3    conda-forge
libtiff                   4.5.0                hf8721a0_2    conda-forge
libvorbis                 1.3.7                h0e60522_0    conda-forge
libwebp                   1.3.0                hcfcfb64_0    conda-forge
libwebp-base              1.3.0                hcfcfb64_0    conda-forge
libxcb                    1.13              hcd874cb_1004    conda-forge
libxgboost                1.7.4            cpu_h20390bd_0    conda-forge
libxml2                   2.10.3               hc3477c8_4    conda-forge
libxslt                   1.1.37               h0192164_0    conda-forge
libzip                    1.9.2                h519de47_1    conda-forge
libzlib                   1.2.13               hcfcfb64_4    conda-forge
libzopfli                 1.0.3                h0e60522_0    conda-forge
lightgbm                  3.3.5           py310h00ffb61_0    conda-forge
llvmlite                  0.39.1          py310hb84602e_1    conda-forge
locket                    1.0.0              pyhd8ed1ab_0    conda-forge
lxml                      4.9.2           py310hc0e5b84_0    conda-forge
lz4-c                     1.9.4                hcfcfb64_0    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
mapclassify               2.5.0              pyhd8ed1ab_1    conda-forge
markdown                  3.4.1              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.2           py310h8d17308_0    conda-forge
matplotlib                3.7.1           py310h5588dad_0    conda-forge
matplotlib-base           3.7.1           py310h51140c5_0    conda-forge
mccabe                    0.7.0                    pypi_0    pypi
mkl                       2022.1.0           h6a75c08_874    conda-forge
mkl-devel                 2022.1.0           h57928b3_875    conda-forge
mkl-include               2022.1.0           h6a75c08_874    conda-forge
mock                      5.0.1              pyhd8ed1ab_0    conda-forge
mpld3                     0.5.9              pyhd8ed1ab_0    conda-forge
mpmath                    1.3.0              pyhd8ed1ab_0    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
munch                     2.5.0                      py_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
mvgavg                    0.1.0              pyh9f0ad1d_0    conda-forge
natsort                   8.3.1              pyhd8ed1ab_0    conda-forge
netcdf4                   1.6.3           nompi_py310hf10f414_100    conda-forge
networkx                  3.0                pyhd8ed1ab_0    conda-forge
nitro                     2.7.dev6             h39d44d4_5    conda-forge
nose2                     0.9.2                      py_0    conda-forge
numba                     0.56.4          py310h19bcfe9_0    conda-forge
numexpr                   2.7.3           py310hf5e1058_2    conda-forge
numpy                     1.23.5          py310h4a8f9c9_0    conda-forge
numpy-indexed             0.3.5                      py_1    conda-forge
openjpeg                  2.5.0                ha2aaf27_2    conda-forge
openpyxl                  3.1.1           py310h8d17308_0    conda-forge
openssl                   3.1.0                hcfcfb64_0    conda-forge
owslib                    0.28.1             pyhd8ed1ab_0    conda-forge
packaging                 23.0               pyhd8ed1ab_0    conda-forge
pandas                    1.5.3           py310h1c4a608_0    conda-forge
panel                     0.14.4             pyhd8ed1ab_0    conda-forge
pango                     1.50.14              hdffb7b3_0    conda-forge
param                     1.13.0             pyh1a96a4e_0    conda-forge
partd                     1.3.0              pyhd8ed1ab_0    conda-forge
pcre2                     10.40                h17e33f8_0    conda-forge
pdal                      2.5.2                h2d23c47_1    conda-forge
pebble                    5.0.3              pyhd8ed1ab_0    conda-forge
pillow                    9.4.0           py310hdbb7713_1    conda-forge
pint                      0.20.1             pyhd8ed1ab_0    conda-forge
pip                       23.0.1             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h8ffe710_0    conda-forge
platformdirs              2.6.2                    pypi_0    pypi
plotly                    5.13.1             pyhd8ed1ab_0    conda-forge
pluggy                    1.0.0                    pypi_0    pypi
ply                       3.11                       py_1    conda-forge
pooch                     1.7.0              pyhd8ed1ab_0    conda-forge
poppler                   23.03.0              h183ae7b_0    conda-forge
poppler-data              0.4.12               hd8ed1ab_0    conda-forge
postgresql                15.2                 hd87cd2b_0    conda-forge
proj                      9.1.1                heca977f_2    conda-forge
psutil                    5.9.4           py310h8d17308_0    conda-forge
psycopg2                  2.9.3           py310h709a2f1_2    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pthreads-win32            2.9.1                hfa6e2cd_3    conda-forge
py-tools-ds               0.21.1          py310h5588dad_0    conda-forge
py-xgboost                1.7.4           cpu_py310h2690a58_0    conda-forge
pycodestyle               2.10.0                   pypi_0    pypi
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyct                      0.4.6                      py_0    conda-forge
pyct-core                 0.4.6                      py_0    conda-forge
pydocstyle                6.2.1                    pypi_0    pypi
pyepsg                    0.4.0                      py_0    conda-forge
pyerfa                    2.0.0.2         py310h9b08ddd_0    conda-forge
pyfftw                    0.13.1          py310ha9ca8c9_0    conda-forge
pyflakes                  3.0.1                    pypi_0    pypi
pygments                  2.14.0             pyhd8ed1ab_0    conda-forge
pygrib                    2.1.4           py310h3a12092_6    conda-forge
pyhdf                     0.10.5          py310h9480a18_1    conda-forge
pykdtree                  1.3.7.post0     py310h9b08ddd_0    conda-forge
pykrige                   1.7.0           py310h8d17308_1    conda-forge
pylint                    2.15.9                   pypi_0    pypi
pyopengl                  3.1.6              pyhd8ed1ab_1    conda-forge
pyopenssl                 23.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyprind                   2.11.2          py310h5588dad_1004    conda-forge
pyproj                    3.4.1           py310hcdd211a_1    conda-forge
pyqt                      5.15.7          py310h1fd54f2_3    conda-forge
pyqt5-sip                 12.11.0         py310h00ffb61_3    conda-forge
pyqtwebkit                5.15.9          py310he49db7d_1    conda-forge
pyresample                1.26.1          py310h1c4a608_0    conda-forge
pyrsr                     0.7.0              pyhd8ed1ab_1    conda-forge
pyshp                     2.3.1              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyh0701188_6    conda-forge
pytables                  3.7.0           py310haee3a42_3    conda-forge
pytest                    7.2.0                    pypi_0    pypi
pytest-cov                4.0.0                    pypi_0    pypi
pytest-reporter           0.5.2                    pypi_0    pypi
pytest-reporter-html1     0.8.2                    pypi_0    pypi
python                    3.10.9          h4de0772_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-graphviz           0.20.1             pyh22cad53_0    conda-forge
python_abi                3.10                    3_cp310    conda-forge
pytz                      2022.7.1           pyhd8ed1ab_0    conda-forge
pyviz_comms               2.2.1              pyhd8ed1ab_1    conda-forge
pywavelets                1.4.1           py310h9b08ddd_0    conda-forge
pyyaml                    6.0             py310h8d17308_5    conda-forge
qca                       2.3.5                h2624d1c_3    conda-forge
qgis                      3.30.0          py310hc91cd07_0    conda-forge
qjson                     0.9.0             h04a78d6_1009    conda-forge
qscintilla2               2.13.4          py310he49db7d_0    conda-forge
qt-main                   5.15.8               h720456b_6    conda-forge
qtkeychain                0.13.2               h04a78d6_2    conda-forge
qtwebkit                  5.212                h992fabe_8    conda-forge
qwt                       6.2.0                h07be427_5    conda-forge
requests                  2.28.2             pyhd8ed1ab_0    conda-forge
rtree                     1.0.1           py310h1cbd46b_1    conda-forge
scikit-image              0.19.3          py310h1c4a608_2    conda-forge
scikit-learn              1.2.2           py310had3394f_0    conda-forge
scipy                     1.10.1          py310h578b7cb_0    conda-forge
sensormapgeo              0.7.0           py310h5588dad_0    conda-forge
setuptools                67.6.0             pyhd8ed1ab_0    conda-forge
shapely                   2.0.1           py310h8c82734_0    conda-forge
sicor                     0.18.0             pyhd8ed1ab_1    conda-forge
sip                       6.7.7           py310h00ffb61_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.10               hfb803bf_0    conda-forge
snowballstemmer           2.2.0                    pypi_0    pypi
soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
spectral                  0.23.1             pyh1a96a4e_0    conda-forge
sphinx                    5.3.0                    pypi_0    pypi
sphinx-argparse           0.4.0                    pypi_0    pypi
sphinx-rtd-theme          1.1.1                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.0.0                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.5                    pypi_0    pypi
sqlite                    3.40.0               hcfcfb64_0    conda-forge
suitesparse               5.4.0                h5d0cbe0_1    conda-forge
sympy                     1.11.1             pyh04b8f61_3    conda-forge
tbb                       2021.8.0             h91493d7_0    conda-forge
tenacity                  8.2.2              pyhd8ed1ab_0    conda-forge
threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge
tifffile                  2023.3.15          pyhd8ed1ab_0    conda-forge
tiledb                    2.13.2               h3132609_0    conda-forge
tk                        8.6.12               h8ffe710_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tomlkit                   0.11.6                   pypi_0    pypi
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tornado                   6.2             py310h8d17308_1    conda-forge
tqdm                      4.65.0             pyhd8ed1ab_1    conda-forge
typeguard                 3.0.1              pyhd8ed1ab_0    conda-forge
typing-extensions         4.5.0                hd8ed1ab_0    conda-forge
typing_extensions         4.5.0              pyha770c72_0    conda-forge
tzdata                    2022g                h191b570_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
unicodedata2              15.0.0          py310h8d17308_0    conda-forge
urlchecker                0.0.34                   pypi_0    pypi
urllib3                   1.26.15            pyhd8ed1ab_0    conda-forge
utm                       0.7.0              pyhd8ed1ab_0    conda-forge
vc                        14.3                 h3d8a991_9    conda-forge
vs2015_runtime            14.34.31931         h4c5c07a_10    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
win_inet_pton             1.1.0              pyhd8ed1ab_6    conda-forge
wrapt                     1.14.1                   pypi_0    pypi
xarray                    2023.2.0           pyhd8ed1ab_0    conda-forge
xerces-c                  3.2.4                h63175ca_2    conda-forge
xgboost                   1.7.4           cpu_py310h2690a58_0    conda-forge
xorg-kbproto              1.0.7             hcd874cb_1002    conda-forge
xorg-libice               1.0.10               hcd874cb_0    conda-forge
xorg-libsm                1.2.3             hcd874cb_1000    conda-forge
xorg-libx11               1.8.4                hcd874cb_0    conda-forge
xorg-libxau               1.0.9                hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xorg-libxext              1.3.4                hcd874cb_2    conda-forge
xorg-libxpm               3.5.13               hcd874cb_0    conda-forge
xorg-libxt                1.2.1                hcd874cb_2    conda-forge
xorg-xextproto            7.3.0             hcd874cb_1003    conda-forge
xorg-xproto               7.0.31            hcd874cb_1007    conda-forge
xyzservices               2023.2.0           pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
zfp                       1.0.0                h63175ca_3    conda-forge
zipp                      3.15.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               hcfcfb64_4    conda-forge
zlib-ng                   2.0.7                hcfcfb64_0    conda-forge
zstd                      1.5.2                h12be248_6    conda-forge
```
</details>

**Comment by danschef** [comment]
Downgrading typeguard to v2.13.3 fixes this issue.

**Comment by janzandr** [comment]
Hi Daniel, what is the mamba command for updating the enpt_full environment?

**Comment by danschef** [comment]
I just updated it with "mamba update --all" but had to install typeguard afterwards because it was not contained in the original setup of the enpt_full environment.

However I guess, you can also upgrade it by running something like:
```bash
mamba env update -n enpt_full -f https://git.gfz-potsdam.de/EnMAP/GFZ_Tools_EnMAP_BOX/EnPT/raw/main/tests/gitlab_CI_docker/context/environment_enpt_full.yml
```
That might be the better way as it also respects recent changes made to the environment_enpt_full.yml

**Comment by janzandr** [comment]
> mamba env update -n enpt_full -f https://git.gfz-potsdam.de/EnMAP/GFZ_Tools_EnMAP_BOX/EnPT/raw/main/tests/gitlab_CI_docker/context/environment_enpt_full.yml

That works fine.

**Comment by janzandr** [comment]
Now I can confirm the error.
