### ISSUE TITLE
netCDF4 requirement blocks main GUI

### ISSUE THREAD

**Issue by jakimowb** [EnMAP-Box/enmap-box#401]
The EnMAP-Box crashes if netCDF is not installed. This violates the our rule that the main GUI should be startable without the need to install packages that are not installed with QGIS by default

```python
from enmapbox.gui.enmapboxgui import EnMAPBox
Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm 2022.3.2\plugins\python\helpers\pydev\pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "F:\OSGeo4W\apps\qgis\python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Program Files (x86)\JetBrains\PyCharm 2022.3.2\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "F:\Repositories\QGIS-Plugins\enmap-box\enmapbox\gui\enmapboxgui.py", line 48, in <module>
    from enmapboxprocessing.algorithm.importemitl2aalgorithm import ImportEmitL2AAlgorithm
  File "F:\OSGeo4W\apps\qgis\python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Program Files (x86)\JetBrains\PyCharm 2022.3.2\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "F:\Repositories\QGIS-Plugins\enmap-box\enmapboxprocessing\algorithm\importemitl2aalgorithm.py", line 4, in <module>
    import netCDF4
  File "F:\OSGeo4W\apps\qgis\python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Program Files (x86)\JetBrains\PyCharm 2022.3.2\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'netCDF4'

```

**Comment by janzandr** [comment]
Thanks Benjamin. I can reproduce this when adding the **shadow-optional-dependencies** folder as source root:
![image](https://user-images.githubusercontent.com/45030715/226851855-264f6261-81cb-4dc9-bbf2-8345a57b859b.png)

> This violates the our rule that the main GUI should be startable without the need to install packages that are not installed with QGIS by default

Unfortunately, we still have no automatic check for this.
