### ISSUE TITLE
"TypeError: 'NoneType' object is not subscriptable" when opening a saved project in QGIS

### ISSUE THREAD

**Issue by danschef** [EnMAP-Box/enmap-box#414]
I have QGIS 3.30 and the EnMAP-Box 3.12 alpha9 installed. I just opened a previously saved project in QGIS (without having the EnMAP-Box running at all) and directly after opening the project, QGIS shows the following error, which comes from the EnMAP-Box:

```python
TypeError: 'NoneType' object is not subscriptable 
Traceback (most recent call last):
  File "C:\Users/danschef/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\enmapboxplugin.py", line 69, in readProject
    settings.readFromProject(document)
  File "C:\Users/danschef/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\enmapboxprojectsettings.py", line 24, in readFromProject
    return self.readXml(element.firstChildElement())
  File "C:\Users/danschef/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\enmapboxprojectsettings.py", line 33, in readXml
    self.setSettings(settings)
  File "C:\Users/danschef/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\enmapboxprojectsettings.py", line 79, in setSettings
    values = settings[f'EO4Q/{key}']
TypeError: 'NoneType' object is not subscriptable


Python-Version: 3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:14:58) [MSC v.1929 64 bit (AMD64)] 
QGIS-Version: 3.30.0-'s-Hertogenbosch 's-Hertogenbosch, exported 
```

**Comment by janzandr** [comment]
Thanks @danschef, technically, the EnMAP-Box is running, because it is activated, even if the GUI is not visible.
But you are right, this is a bug.

**Comment by danschef** [comment]
It seems like this is caused by a QGIS project file which was saved with an older QGIS version (3.16). After saving the file again with QGIS 3.30, the issue is gone. However, there should not be a Python error if a user opens an old project file.
