### ISSUE TITLE
[qps] Can not read HDF4 error while Box is not opened/used

### ISSUE THREAD

**Issue by thielfab** [EnMAP-Box/enmap-box#418]
Just came across this randomly:

How to reproduce:
* Open GIS, EnMAP-Box is **closed**
* Open MODIS image
* Go to Symbology, change renderer (I used Singleband pseudocolor), click Apply

The Following error shows up:
```
An error has occurred while executing Python code: 

AssertionError: Can not read HDF4_EOS:EOS_SWATH:"/home/openshift/brain/data/wvdb/hdf/MOD05_L2.A2022259.0800.061.2022259211558.hdf":mod05:Water_Vapor_Near_Infrared as gdal.Dataset 
Traceback (most recent call last):
  File "/home/openshift/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/qgispluginsupport/qps/layerconfigwidgets/gdalmetadata.py", line 1218, in apply
    ds = gdalDataset(self.mapLayer(), gdal.GA_Update)
  File "/home/openshift/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/qgispluginsupport/qps/utils.py", line 829, in gdalDataset
    return gdalDataset(dataset.source(), eAccess=eAccess)
  File "/home/openshift/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/qgispluginsupport/qps/utils.py", line 834, in gdalDataset
    assert isinstance(ds, gdal.Dataset), f'Can not read {dataset} as gdal.Dataset'
AssertionError: Can not read HDF4_EOS:EOS_SWATH:"/home/openshift/brain/data/wvdb/hdf/MOD05_L2.A2022259.0800.061.2022259211558.hdf":mod05:Water_Vapor_Near_Infrared as gdal.Dataset


Python version: 3.10.6 (main, Aug 10 2022, 11:40:04) [GCC 11.3.0] 
QGIS version: 3.26.3-Buenos Aires Buenos Aires, 65e4edfdad 
```
GDAL version: 3.4.1
EnMAP-Box version: 3.11.1

**Comment by jakimowb** [comment]
@thielfab can you provide a link to download the MODIS image?

**Comment by jakimowb** [comment]
Amongst other issues one is, that we cannot modify the metadata of HDF sub-images
````
gdal.Open('HDF4_EOS:EOS_SWATH:"/home/benni/Downloads/MOD05_L2.A2022305.0005.061.2022335032530.hdf":mod05:Water_Vapor_Near_Infrared', gdal.GA_Update)
...
RuntimeError: HDF4_EOS:EOS_SWATH:"/home/benni/Downloads/MOD05_L2.A2022305.0005.061.2022335032530.hdf":mod05:Water_Vapor_Near_Infrared: No such file or directory
````
