### ISSUE TITLE
support typeguard version 4.x

### ISSUE THREAD

**Issue by jakimowb** [EnMAP-Box/enmap-box#430]
/enmapboxprocessing/reportwriter.py raises the error listed below if typguard available:

QGIS 3.30.0
Python 3.10.9
typeguard 3.0.2

```
  File "/home/benni/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/__init__.py", line 235, in collectEnMAPBoxAlgorithms
    from enmapboxprocessing.algorithm.algorithms import algorithms
  File "/home/benni/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ee_plugin/__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "/home/benni/mambaforge/envs/enmapbox_full_latest/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/benni/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapboxprocessing/algorithm/algorithms.py", line 7, in <module>
    from enmapboxprocessing.algorithm.classificationperformancesimplealgorithm import \
  File "/home/benni/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ee_plugin/__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "/home/benni/mambaforge/envs/enmapbox_full_latest/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/benni/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapboxprocessing/algorithm/classificationperformancesimplealgorithm.py", line 4, in <module>
    from enmapboxprocessing.algorithm.classificationperformancestratifiedalgorithm import \
  File "/home/benni/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ee_plugin/__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "/home/benni/mambaforge/envs/enmapbox_full_latest/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/benni/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapboxprocessing/algorithm/classificationperformancestratifiedalgorithm.py", line 16, in <module>
    from enmapboxprocessing.reportwriter import HtmlReportWriter, CsvReportWriter, MultiReportWriter
  File "/home/benni/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ee_plugin/__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "/home/benni/mambaforge/envs/enmapbox_full_latest/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/benni/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapboxprocessing/reportwriter.py", line 151, in <module>
    class MultiReportWriter(object):
  File "/home/benni/mambaforge/envs/enmapbox_full_latest/lib/python3.10/site-packages/typeguard/_decorators.py", line 147, in typechecked
    retval = instrument(attr)
  File "/home/benni/mambaforge/envs/enmapbox_full_latest/lib/python3.10/site-packages/typeguard/_decorators.py", line 75, in instrument
    module_code = compile(module_ast, f.__code__.co_filename, "exec", dont_inherit=True)
TypeError: required field "ctx" missing from Subscript

```

**Comment by janzandr** [comment]
1. Which typegurad version?
2. Explain steps  to reproduce the error.

**Comment by jakimowb** [comment]
To be compatible with other python code that requires a non-outdated typeguard versions (e.g. in other QGIS plugins), this issue needs to be solved properly. Maybee not vor EnMAP-Box 3.12, but in a near future.

**Comment by jakimowb** [comment]
@janzandr is there any progress in make the EnMAP-Box running with up-to-date typeguard versions?
In the EnMAP-Box, typeguard is still pinned to `typeguard==2.13.3`, while the latest typeguard release is at 4.1.5 (already two major release differences) https://github.com/agronholm/typeguard

**Comment by janzandr** [comment]
Currently not working on that issue. With typeguard >2, the type checks are more rigorous. Moving to version 4 could/would introduce a lot of code breakes, which may not be covered by unittests. Making the transition to v4 could take a while. So it's more a question of priority.

**Comment by jakimowb** [comment]
Have you checked if there are any options to skip these "more rigorous" tests?
There is a lot of documentation related to this and other config options.
https://typeguard.readthedocs.io/en/latest/userguide.html#suppressing-type-checks

**Comment by janzandr** [comment]
> Have you checked if there are any options to skip these "more rigorous" tests?

Not yet, but I can do it asap.

**Comment by jakimowb** [comment]
@janzandr this issue has been opened already 2 years ago. Any comments on that? Meanwhile the depencency on an outdated typeguard version is a real problem.
Everytime when pip or conda updates packages, typeguard is updated to 4.+. So far I don't know how this can be avoided.

After an update to a recent typeguard version, the EnMAP-Box raises errors like the one below. This is highly frustrating, as typeguard can be seen as a developer's feature only which should not be used in product. I therefore recommend to remove it from all conda environment files in `.env/conda`.

  ```
 self.addParameterRasterDestination(self.P_OUTPUT_RASTER, self._OUTPUT_RASTER)
  File "/home/geographie/jakimowb/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapboxprocessing/enmapalgorithm.py", line 794, in addParameterRasterDestination
    def addParameterRasterDestination(
  File "/mnt/lustre/scratch/geographie/jakimowb/conda_envs/enmapbox/lib/python3.12/site-packages/typeguard/_functions.py", line 137, in check_argument_types
    check_type_internal(value, annotation, memo)
  File "/mnt/lustre/scratch/geographie/jakimowb/conda_envs/enmapbox/lib/python3.12/site-packages/typeguard/_checkers.py", line 956, in check_type_internal
    raise TypeCheckError(f"is not an instance of {qualified_name(origin_type)}")
typeguard.TypeCheckError: argument "defaultFileExtension" (None) is not an instance of str
Traceback (most recent call last):
  File "/home/geographie/jakimowb/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapboxprocessing/algorithm/vrtbandmathalgorithm.py", line 66, in initAlgorithm
    self.addParameterBandList(self.P_BAND_LIST, self._BAND_LIST, parentLayerParameterName=self.P_RASTER)
  File "/home/geographie/jakimowb/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapboxprocessing/enmapalgorithm.py", line 765, in addParameterBandList
    def addParameterBandList(
  File "/mnt/lustre/scratch/geographie/jakimowb/conda_envs/enmapbox/lib/python3.12/site-packages/typeguard/_functions.py", line 137, in check_argument_types
    check_type_internal(value, annotation, memo)
  File "/mnt/lustre/scratch/geographie/jakimowb/conda_envs/enmapbox/lib/python3.12/site-packages/typeguard/_checkers.py", line 951, in check_type_internal
    checker(value, origin_type, args, memo)
  File "/mnt/lustre/scratch/geographie/jakimowb/conda_envs/enmapbox/lib/python3.12/site-packages/typeguard/_checkers.py", line 295, in check_list
    raise TypeCheckError("is not a list")
typeguard.TypeCheckError: argument "defaultValue" (None) is not a list

```

**Comment by janzandr** [comment]
Discussed with @jakimowb: we won't support typeguard 3+, because it has severe performance problems, which aren't solved yet.
Unfortunately, external packages already require recent typeguard versions, so we can't fix the version to 2.13.3.
Solution: we will ship typeguard 2.13.3 as a submodule (enmapbox.typeguard) and replace all **typeguard** imports with **enmapbox.typeguard**.
