### ISSUE TITLE
SpectralLibrary class was removed and replaced by QgsVectorLayer, which causes unittests to fail

### ISSUE THREAD

**Issue by jakimowb** [EnMAP-Box/enmap-box#434]
Several tests below tests/enmap-box cannot be started with pytest because of:

```
tests/enmap-box/enmapboxprocessing/algorithm/test_SpectralResamplingByResponseFunctionLibraryAlgorithm.py:10
  /home/benni/dev/python/enmap-box/tests/enmap-box/enmapboxprocessing/algorithm/test_SpectralResamplingByResponseFunctionLibraryAlgorithm.py:10: PytestCollectionWarning: cannot collect test class 'TestSpectralResamplingByResponseFunctionLibraryAlgorithmBase' because it has a __init__ constructor (from: tests/enmap-box/enmapboxprocessing/algorithm/test_SpectralResamplingByResponseFunctionLibraryAlgorithm.py)
    class TestSpectralResamplingByResponseFunctionLibraryAlgorithmBase(TestCase):

```

**Comment by janzandr** [comment]
Not quite sure about your error message, but I can confirm that the test is failing:

```
Error
Traceback (most recent call last):
  File "D:\source\QGISPlugIns\enmap-box\tests\enmap-box\enmapboxprocessing\algorithm\test_SpectralResamplingByResponseFunctionLibraryAlgorithm.py", line 19, in test
    result = self.runalg(alg, parameters)
  File "C:\QGIS\apps\qgis-ltr\python\plugins\processing\core\Processing.py", line 187, in runAlgorithm
    ret, results = execute(alg, parameters, context, feedback, catch_exceptions=False)
  File "C:\QGIS\apps\qgis-ltr\python\plugins\processing\gui\AlgorithmExecutor.py", line 72, in execute
    results, ok = alg.run(parameters, context, feedback, {}, False)
_core.QgsProcessingException: Traceback (most recent call last):
  File "C:\Users\Andreas\AppData\Roaming\Python\Python39\site-packages\typeguard\__init__.py", line 1033, in wrapper
    retval = func(*args, **kwargs)
  File "D:\source\QGISPlugIns\enmap-box\enmapboxprocessing\algorithm\spectralresamplingbyresponsefunctionlibraryalgorithm.py", line 76, in processAlgorithm
    for profile in spectralLibrary.profiles(profile_field=binaryField):
AttributeError: 'QgsVectorLayer' object has no attribute 'profiles'
```

**Comment by janzandr** [comment]
Hmm, looks like the **SpectralLibrary** class was replaced by a standard **QgsVectorLayer**, which has no **profiles()** methode.

@jakimowb, how would I now read all profiles of a library? A minimalistic code snippet would be helpful.

**Comment by janzandr** [comment]
Those unittests are affected:
![image](https://user-images.githubusercontent.com/45030715/229060715-8f9a04dd-a3a3-47a2-8d89-d1c9bb806e37.png)

**Comment by janzandr** [comment]
New code must look like this:
![image](https://user-images.githubusercontent.com/45030715/229070715-58724370-4ee2-413d-b90c-2c9be1e82dc5.png)
See

**Comment by jakimowb** [comment]
Imports like `from qps.speclib.core.spectralprofile import decodeProfileValueDict` will fail as qps is a submodule of enmapbox and not available in the pythonpath.

**Comment by janzandr** [comment]
Yes, sorry, thanks for fixing.
