### ISSUE TITLE
Couldn't load plugin 'enmapboxplugin' due to an error when calling its classFactory() method 

### ISSUE THREAD

**Issue by KhalilM94** [EnMAP-Box/enmap-box#453]
Lanching the plugin raises the following error [and stops the algorithms from loading]:

```
AssertionError 
Traceback (most recent call last):
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/khalilmisbah/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/__init__.py", line 51, in classFactory
    plugin = EnMAPBoxPlugin(iface)
  File "/Users/khalilmisbah/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/enmapboxplugin.py", line 54, in __init__
    enmapbox.initAll()
  File "/Users/khalilmisbah/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/__init__.py", line 365, in initAll
    registerEditorWidgets()
  File "/Users/khalilmisbah/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/__init__.py", line 212, in registerEditorWidgets
    registerEditorWidgets()
  File "/Users/khalilmisbah/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/qgispluginsupport/qps/__init__.py", line 144, in registerEditorWidgets
    assert isinstance(classificationSchemeEditorWidgetFactory(True), ClassificationSchemeWidgetFactory)
AssertionError
```
MacOS
Python version: 3.9.5 (default, Sep 10 2021, 16:18:19) [Clang 12.0.5 (clang-1205.0.22.11)] 
QGIS version: 3.28.5-Firenze Firenze, 50adba36f2

**Comment by jakimowb** [comment]
Dear @KhalilM94 I cannot reproduce this error on MacBook Pro 2020, Intel Core i5 (which might be outdated)

Please check if one the following steps help:

1. Update to the most recent LTR - 3.28.6 (yours is 3.28.5) 
2. ensure to have the most-recent EnMAP-Box installe, by writing this 3.12.0
3. de-activate the other optional QGIS plugins

Please let us know if this helps.

**Comment by jakimowb** [comment]
This issue seems to be stale and the error to be gone. We can re-open it if the error still occurs.
