### ISSUE TITLE
New error when starting EnMap-Box

### ISSUE THREAD

**Issue by grantboxer** [EnMAP-Box/enmap-box#459]
I am using QGIS v 3.30.1, any thoughts? I have re-installed all the dependencies as per the read-the-docs.

Error message below

2023-04-26T11:41:06     WARNING    warning:C:\OSGeo4W\apps\Python39\lib\site-packages\pkg_resources\__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google.logging')`.
             Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
              declare_namespace(pkg)
             
             traceback: File "", line 1, in 
              File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 443, in startPlugin
              if not _startPlugin(packageName):
              File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
              plugins[packageName] = package.classFactory(iface)
              File "C:\Users/Grant/AppData/Roaming/QGIS/QGIS3\profiles\Grant/python/plugins\ee_plugin\__init__.py", line 65, in classFactory
              pre_init_plugin()
              File "C:\Users/Grant/AppData/Roaming/QGIS/QGIS3\profiles\Grant/python/plugins\ee_plugin\__init__.py", line 23, in pre_init_plugin
              pkg_resources.working_set.add_entry(extra_libs_path)
              File "C:\OSGeo4W\apps\Python39\lib\site-packages\pkg_resources\__init__.py", line 670, in add_entry
              self.add(dist, entry, False)
              File "C:\OSGeo4W\apps\Python39\lib\site-packages\pkg_resources\__init__.py", line 769, in add
              self._added_new(dist)
              File "C:\OSGeo4W\apps\Python39\lib\site-packages\pkg_resources\__init__.py", line 989, in _added_new
              callback(dist)
              File "C:\OSGeo4W\apps\Python39\lib\site-packages\pkg_resources\__init__.py", line 3351, in 
              lambda dist: dist.activate(replace=True),
              File "C:\OSGeo4W\apps\Python39\lib\site-packages\pkg_resources\__init__.py", line 2870, in activate
              declare_namespace(pkg)
              File "C:\OSGeo4W\apps\Python39\lib\site-packages\pkg_resources\__init__.py", line 2338, in declare_namespace
              warnings.warn(msg, DeprecationWarning, stacklevel=2)

**Comment by janzandr** [comment]
Please check the Google Earth Engine plugin version.
![image](https://user-images.githubusercontent.com/45030715/234494004-cf33094b-7569-4225-be27-adc7ad99b68d.png)

Are you using the latest 0.0.6? If not, update, restart QGIS, and try again.

**Comment by janzandr** [comment]
For my understaning: is this really an error or just a warning?
Is the EnMAP-Box starting and can you use it?

**Comment by janzandr** [comment]
Alright, now you show a totally different error ;-)
@jakimowb, seams to be related to QPS, please check:

```
"C:\Users/boxer/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\qgispluginsupport\qps\utils.py", line 53, in
    from osgeo import gdal, ogr, osr, gdal_array
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\osgeo\gdal_array.py", line 13, in
    from . import _gdal_array
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: numpy.core.multiarray failed to import
```

**Comment by janzandr** [comment]
@grantboxer, if possible, also try QGIS 3.28.4 LTR version.

**Comment by grantboxer** [comment]
Sorry, how do I check that?

 

Cheers grant

**Comment by janzandr** [comment]
@grantboxer, I asked @jakimowb to check it.
You can try if the problem also occurs under QGIS LTR.

**Comment by grantboxer** [comment]
Yes, looks like the same message

 

Couldn't load plugin 'enmapboxplugin' due to an error when calling its classFactory() method 

ImportError: numpy.core.multiarray failed to import 

Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/boxer/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\__init__.py", line 51, in classFactory
    plugin = EnMAPBoxPlugin(iface)
  File "C:\Users/boxer/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\enmapboxplugin.py", line 51, in __init__
    self.initialDependencyCheck()
  File "C:\Users/boxer/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\enmapboxplugin.py", line 77, in initialDependencyCheck
    from enmapbox.dependencycheck import missingPackageInfo, requiredPackages
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/boxer/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\dependencycheck.py", line 38, in 
    from enmapbox.qgispluginsupport.qps.utils import qgisAppQgisInterface
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/boxer/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\qgispluginsupport\qps\utils.py", line 53, in 
    from osgeo import gdal, ogr, osr, gdal_array
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\osgeo\gdal_array.py", line 13, in 
    from . import _gdal_array
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: numpy.core.multiarray failed to import


Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.28.5-Firenze Firenze, 50adba36f2 

Python Path:

*                     C:/OSGeo4W/apps/qgis-ltr/./python

*                     C:/Users/boxer/AppData/Roaming/QGIS/QGIS3\profiles\default/python

*                     C:/Users/boxer/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins

*                     C:/OSGeo4W/apps/qgis-ltr/./python/plugins

*                     C:\OSGeo4W\apps\grass\grass82\etc\python

*                     C:\OSGeo4W\bin

*                     C:\OSGeo4W\bin\python39.zip

*                     C:\OSGeo4W\apps\Python39\DLLs

*                     C:\OSGeo4W\apps\Python39\lib

*                     C:\Users\boxer\AppData\Roaming\Python\Python39\site-packages

*                     C:\OSGeo4W\apps\Python39

*                     C:\OSGeo4W\apps\Python39\lib\site-packages

*                     C:\OSGeo4W\apps\Python39\lib\site-packages\win32

*                     C:\OSGeo4W\apps\Python39\lib\site-packages\win32\lib

*                     C:\OSGeo4W\apps\Python39\lib\site-packages\Pythonwin

*                     C:/Users/boxer/AppData/Roaming/QGIS/QGIS3\profiles\default/python

*                     C:\Users/boxer/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\site-packages

*                     C:\Users\boxer\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\site-packages

*                     C:\Users\boxer\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\apps

*                     C:\Users\boxer\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\coreapps

C:\Users\boxer\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\eo4qapps

**Comment by grantboxer** [comment]
I have downloaded the 3.28.4 version as bz2 file – how do I open that to install it?

**Comment by janzandr** [comment]
Yes, sounds good.

**Comment by janzandr** [comment]
@jakimowb, I can't reproduce the error in QPS, you may check and reopen if reqequired.

```
"C:\Users/boxer/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\qgispluginsupport\qps\utils.py", line 53, in
    from osgeo import gdal, ogr, osr, gdal_array
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\osgeo\gdal_array.py", line 13, in
    from . import _gdal_array
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: numpy.core.multiarray failed to import

```

**Comment by jakimowb** [comment]
> @jakimowb, I can't reproduce the error in QPS, you may check and reopen if reqequired.
> 
> ```
> "C:\Users/boxer/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\qgispluginsupport\qps\utils.py", line 53, in
>     from osgeo import gdal, ogr, osr, gdal_array
>   File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
>     mod = _builtin_import(name, globals, locals, fromlist, level)
>   File "C:\OSGeo4W\apps\Python39\lib\site-packages\osgeo\gdal_array.py", line 13, in
>     from . import _gdal_array
>   File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
>     mod = _builtin_import(name, globals, locals, fromlist, level)
> ImportError: numpy.core.multiarray failed to import
> ```

The errors have always been related to numpy/gdal imports. Looks more like a setup issue of the local python installation.
