### ISSUE TITLE
ValueError: ndarray is not C-contiguous

### ISSUE THREAD

**Issue by jakimowb** [EnMAP-Box/enmap-box#463]
test_clusterers in `tests/enmap-box/enmapboxprocessing/algorithm/test_FitClustererAlgorithm.py` fails with the following error:

```
Error
Traceback (most recent call last):
  File "F:\Repositories\QGIS-Plugins\enmap-box\tests\enmap-box\enmapboxprocessing\algorithm\test_FitClustererAlgorithm.py", line 101, in test_clusterers
    self.runalg(alg, parameters)
  File "F:\OSGeo4W\apps\qgis\python\plugins\processing\core\Processing.py", line 179, in runAlgorithm
    ret, results = execute(alg, parameters, context, feedback, catch_exceptions=False)
  File "F:\OSGeo4W\apps\qgis\python\plugins\processing\gui\AlgorithmExecutor.py", line 72, in execute
    results, ok = alg.run(parameters, context, feedback, {}, False)
_core.QgsProcessingException: Traceback (most recent call last):
  File "F:\Repositories\QGIS-Plugins\enmap-box\enmapboxprocessing\algorithm\fitclustereralgorithmbase.py", line 101, in processAlgorithm
    clusterCount = int(np.max(clusterer.predict(dump.X))) + 1
  File "F:\OSGeo4W\apps\Python39\lib\site-packages\sklearn\pipeline.py", line 458, in predict
    return self.steps[-1][1].predict(Xt, **predict_params)
  File "F:\OSGeo4W\apps\Python39\lib\site-packages\sklearn\cluster\_mean_shift.py", line 514, in predict
    return pairwise_distances_argmin(X, self.cluster_centers_)
  File "F:\OSGeo4W\apps\Python39\lib\site-packages\sklearn\metrics\pairwise.py", line 791, in pairwise_distances_argmin
    indices = PairwiseDistancesArgKmin.compute(
  File "sklearn\metrics\_pairwise_distances_reduction.pyx", line 672, in sklearn.metrics._pairwise_distances_reduction.PairwiseDistancesArgKmin.compute
  File "sklearn\metrics\_pairwise_distances_reduction.pyx", line 1055, in sklearn.metrics._pairwise_distances_reduction.FastEuclideanPairwiseDistancesArgKmin.__init__
  File "sklearn\metrics\_dist_metrics.pyx", line 1300, in sklearn.metrics._dist_metrics.DatasetsPair.get_for
  File "sklearn\metrics\_dist_metrics.pyx", line 1348, in sklearn.metrics._dist_metrics.DenseDenseDatasetsPair.__init__
  File "stringsource", line 658, in View.MemoryView.memoryview_cwrapper
  File "stringsource", line 349, in View.MemoryView.memoryview.__cinit__
ValueError: ndarray is not C-contiguous

```

This could be related to #462

**Comment by janzandr** [comment]
Probably already solved. Test isn't failing on my system. Re-open if necessary.
