### ISSUE TITLE
Python Error

### ISSUE THREAD

**Issue by grantboxer** [EnMAP-Box/enmap-box#464]
I am getting python errors whenever I try to load QGIS either from the network installer and the standalone installers.
See below.

Couldn't load plugin 'enmapboxplugin' due to an error when calling its classFactory() method 

ImportError: numpy.core.multiarray failed to import 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS33~1.2/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/Grant/AppData/Roaming/QGIS/QGIS3\profiles\Grant/python/plugins\enmapboxplugin\__init__.py", line 51, in classFactory
    plugin = EnMAPBoxPlugin(iface)
  File "C:\Users/Grant/AppData/Roaming/QGIS/QGIS3\profiles\Grant/python/plugins\enmapboxplugin\enmapbox\enmapboxplugin.py", line 51, in __init__
    self.initialDependencyCheck()
  File "C:\Users/Grant/AppData/Roaming/QGIS/QGIS3\profiles\Grant/python/plugins\enmapboxplugin\enmapbox\enmapboxplugin.py", line 77, in initialDependencyCheck
    from enmapbox.dependencycheck import missingPackageInfo, requiredPackages
  File "C:\PROGRA~1/QGIS33~1.2/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Grant/AppData/Roaming/QGIS/QGIS3\profiles\Grant/python/plugins\enmapboxplugin\enmapbox\dependencycheck.py", line 38, in 
    from enmapbox.qgispluginsupport.qps.utils import qgisAppQgisInterface
  File "C:\PROGRA~1/QGIS33~1.2/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Grant/AppData/Roaming/QGIS/QGIS3\profiles\Grant/python/plugins\enmapboxplugin\enmapbox\qgispluginsupport\qps\utils.py", line 53, in 
    from osgeo import gdal, ogr, osr, gdal_array
  File "C:\PROGRA~1/QGIS33~1.2/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\QGIS33~1.2\apps\Python39\lib\site-packages\osgeo\gdal_array.py", line 13, in 
    from . import _gdal_array
  File "C:\PROGRA~1/QGIS33~1.2/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: numpy.core.multiarray failed to import

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.30.2-'s-Hertogenbosch 's-Hertogenbosch, 0992b533 

Python Path:
C:/PROGRA~1/QGIS33~1.2/apps/qgis/./python
C:/Users/Grant/AppData/Roaming/QGIS/QGIS3\profiles\Grant/python
C:/Users/Grant/AppData/Roaming/QGIS/QGIS3\profiles\Grant/python/plugins
C:/PROGRA~1/QGIS33~1.2/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS33~1.2\apps\grass\grass82\etc\python
C:\Users\Grant\Documents
C:\Program Files\QGIS 3.30.2\bin\python39.zip
C:\PROGRA~1\QGIS33~1.2\apps\Python39\DLLs
C:\PROGRA~1\QGIS33~1.2\apps\Python39\lib
C:\Program Files\QGIS 3.30.2\bin
C:\Users\Grant\AppData\Roaming\Python\Python39\site-packages
C:\PROGRA~1\QGIS33~1.2\apps\Python39
C:\PROGRA~1\QGIS33~1.2\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS33~1.2\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS33~1.2\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS33~1.2\apps\Python39\lib\site-packages\Pythonwin
C:/Users/Grant/AppData/Roaming/QGIS/QGIS3\profiles\Grant/python
C:\Users/Grant/AppData/Roaming/QGIS/QGIS3\profiles\Grant/python/plugins\enmapboxplugin\site-packages
C:\Users\Grant\AppData\Roaming\QGIS\QGIS3\profiles\Grant\python\plugins\enmapboxplugin\enmapbox\qgispluginsupport\qps\pyqtgraph
C:\Users\Grant\AppData\Roaming\QGIS\QGIS3\profiles\Grant\python\plugins\enmapboxplugin\enmapbox\site-packages
C:\Users\Grant\AppData\Roaming\QGIS\QGIS3\profiles\Grant\python\plugins\enmapboxplugin\enmapbox\apps
C:\Users\Grant\AppData\Roaming\QGIS\QGIS3\profiles\Grant\python\plugins\enmapboxplugin\enmapbox\coreapps
C:\Users\Grant\AppData\Roaming\QGIS\QGIS3\profiles\Grant\python\plugins\enmapboxplugin\enmapbox\eo4qapps

**Comment by janzandr** [comment]
Looks more like a problem with your QGIS installation. Please try to execute the following command in your QGOS Python Console:
`from osgeo import gdal, ogr, osr, gdal_array`

![image](https://user-images.githubusercontent.com/45030715/236751744-2f035730-d31f-430c-87e2-fa181f69de25.png)

Is that working?

**Comment by grantboxer** [comment]
Hi Andreas,

 

I get the following result for the network installer and the standalone 3.30 and 3.28 versions.

 

# Python Console

# Use iface to access QGIS API interface or type help(iface) for more info

# Security warning: typing commands from an untrusted source can harm your computer

from osgeo import gdal, ogr, osr, gdal_array

RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xe . Check the section C-API incompatibility at the Troubleshooting ImportError section at https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem .

Traceback (most recent call last):

  File "C:\PROGRA~1\QGIS33~1.2\apps\Python39\lib\code.py", line 90, in runcode

    exec(code, self.locals)

  File "<input>", line 1, in <module>

  File "C:\PROGRA~1/QGIS33~1.2/apps/qgis/./python\qgis\utils.py", line 888, in _import

    mod = _builtin_import(name, globals, locals, fromlist, level)

  File "C:\PROGRA~1\QGIS33~1.2\apps\Python39\lib\site-packages\osgeo\gdal_array.py", line 13, in <module>

    from . import _gdal_array

  File "C:\PROGRA~1/QGIS33~1.2/apps/qgis/./python\qgis\utils.py", line 888, in _import

    mod = _builtin_import(name, globals, locals, fromlist, level)

ImportError: numpy.core.multiarray failed to import

**Comment by janzandr** [comment]
Sorry, something is wrong with your system / QGIS. That isn't EnMAP-Box related.
@jakimowb, any ideas?

**Comment by grantboxer** [comment]
Hi Andreas,

 

Now that’s confusing!

 

See below for message I get on starting QGIS.

 

Couldn't load plugin 'enmapboxplugin' due to an error when calling its classFactory() method 

ImportError: numpy.core.multiarray failed to import 

Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS33~1.2/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/boxer/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\__init__.py", line 51, in classFactory
    plugin = EnMAPBoxPlugin(iface)
  File "C:\Users/boxer/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\enmapboxplugin.py", line 51, in __init__
    self.initialDependencyCheck()
  File "C:\Users/boxer/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\enmapboxplugin.py", line 77, in initialDependencyCheck
    from enmapbox.dependencycheck import missingPackageInfo, requiredPackages
  File "C:\PROGRA~1/QGIS33~1.2/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/boxer/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\dependencycheck.py", line 38, in 
    from enmapbox.qgispluginsupport.qps.utils import qgisAppQgisInterface
  File "C:\PROGRA~1/QGIS33~1.2/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/boxer/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\qgispluginsupport\qps\utils.py", line 53, in 
    from osgeo import gdal, ogr, osr, gdal_array
  File "C:\PROGRA~1/QGIS33~1.2/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\QGIS33~1.2\apps\Python39\lib\site-packages\osgeo\gdal_array.py", line 13, in 
    from . import _gdal_array
  File "C:\PROGRA~1/QGIS33~1.2/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: numpy.core.multiarray failed to import


Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.30.2-'s-Hertogenbosch 's-Hertogenbosch, 0992b533 

Python Path:

*                     C:/PROGRA~1/QGIS33~1.2/apps/qgis/./python

*                     C:/Users/boxer/AppData/Roaming/QGIS/QGIS3\profiles\default/python

*                     C:/Users/boxer/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins

*                     C:/PROGRA~1/QGIS33~1.2/apps/qgis/./python/plugins

*                     C:\PROGRA~1\QGIS33~1.2\apps\grass\grass82\etc\python

*                     C:\Users\boxer\Documents

*                     C:\Program Files\QGIS 3.30.2\bin\python39.zip

*                     C:\PROGRA~1\QGIS33~1.2\apps\Python39\DLLs

*                     C:\PROGRA~1\QGIS33~1.2\apps\Python39\lib

*                     C:\Program Files\QGIS 3.30.2\bin

*                     C:\Users\boxer\AppData\Roaming\Python\Python39\site-packages

*                     C:\PROGRA~1\QGIS33~1.2\apps\Python39

*                     C:\PROGRA~1\QGIS33~1.2\apps\Python39\lib\site-packages

*                     C:\PROGRA~1\QGIS33~1.2\apps\Python39\lib\site-packages\win32

*                     C:\PROGRA~1\QGIS33~1.2\apps\Python39\lib\site-packages\win32\lib

*                     C:\PROGRA~1\QGIS33~1.2\apps\Python39\lib\site-packages\Pythonwin

*                     C:/Users/boxer/AppData/Roaming/QGIS/QGIS3\profiles\default/python

*                     C:\Users/boxer/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\site-packages

*                     C:\Users\boxer\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\qgispluginsupport\qps\pyqtgraph

*                     C:\Users\boxer\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\site-packages

*                     C:\Users\boxer\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\apps

*                     C:\Users\boxer\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\coreapps

C:\Users\boxer\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\eo4qapps

**Comment by janzandr** [comment]
> Now that’s confusing!
> See below for message I get on starting QGIS.
> Couldn't load plugin 'enmapboxplugin' due to an error when calling its classFactory() method
> 
> ImportError: numpy.core.multiarray failed to import

There is a problem with your GDAL/Numpy, as you tested, you can reproduce the error with the import statement alone:
`from osgeo import gdal, ogr, osr, gdal_array`

Not sure how to help you with that.
Have you reinstalled QGIS into a fresh location (do not overwrite existing QGIS installation)?
Have you tried a different PC?

**Comment by grantboxer** [comment]
Hi Andreas,

 

The EnMAP-Box plug-in loads OK in 3.28.5 but not in 3.30.2.

 

I will use 3.28.5 when I need to use the plug-in until we find out what the issue is.

 

Cheers Grant

**Comment by janzandr** [comment]
Have you tried the **QGIS-OSGeo4W-3.28.7-1.msi** installer? Maybe that takes care of the problem.
https://qgis.org/en/site/forusers/download.html
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/e3acf1c7-4e7c-4b14-ab82-07f15241e794)

**Comment by janzandr** [comment]
If that isn't helping, I would ask you to file an issue in the QGIS issue tracker to get help.

**Comment by dpoursanidis** [comment]
Nor the 3.28 LTR neither the 3.30 works.

I test 3.28.0-Firenze and is fine.

It is clear a QGIS issue and not a python (i have Anaconda) or EnMAP side issue.

**Comment by janzandr** [comment]
Problem is related to QGIS installation, can't do much on the EnMAP-Box side about it.

**Comment by grantboxer** [comment]
OK thanks!
