### ISSUE TITLE
Ubuntu 22.04: No module named 'PyQt5.pyrcc_main'

### ISSUE THREAD

**Issue by thielfab** [EnMAP-Box/enmap-box#466]
Since Update 3.12.1 the EnMAP-Box does not start on Ubuntu 22.04 (i.e., our virtual noVNC desktops). Before everything worked fine.

```
2023-05-09T08:54:35     CRITICAL    Traceback (most recent call last):
              File "/usr/lib/python3/dist-packages/qgis/utils.py", line 423, in _startPlugin
              plugins[packageName] = package.classFactory(iface)
              File "/home/openshift/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/__init__.py", line 55, in classFactory
              raise ex
              File "/home/openshift/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/__init__.py", line 51, in classFactory
              plugin = EnMAPBoxPlugin(iface)
              File "/home/openshift/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/enmapboxplugin.py", line 54, in __init__
              enmapbox.initAll()
              File "/home/openshift/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/__init__.py", line 356, in initAll
              initEnMAPBoxResources()
              File "/home/openshift/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/__init__.py", line 200, in initEnMAPBoxResources
              from .qgispluginsupport.qps.resources import initQtResources
              File "/home/openshift/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ee_plugin/__init__.py", line 38, in __wrapping_ee_import__
              _module_ = __builtin_import__(name, *args, **kwargs)
              File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "/home/openshift/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/qgispluginsupport/qps/resources.py", line 33, in 
              import PyQt5.pyrcc_main
              File "/home/openshift/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ee_plugin/__init__.py", line 38, in __wrapping_ee_import__
              _module_ = __builtin_import__(name, *args, **kwargs)
              File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
             ModuleNotFoundError: No module named 'PyQt5.pyrcc_main'
```

QGIS version
3.28.5-Firenze
QGIS code revision
50adba36f2
Qt version
5.15.3
Python version
3.10.6
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Ubuntu 22.04.1 LTS

Active Python plugins
ee_plugin
0.0.6
zoomview
1.1.2
DataPlotly
4.0.0
send2google_earth
0.3.1
quick_map_services
0.19.33
BitFlagRenderer
0.4.20200817T093838.master
db_manager
0.1.20
sagaprovider
2.12.99
processing
2.12.99
MetaSearch
0.3.6
grassprovider
2.12.99

**Comment by janzandr** [comment]
@thielfab is this issue already solved?

**Comment by thielfab** [comment]
Not really. This might be related to #403. We "fixed" the issue by moving to a full conda installation.

**Comment by thielfab** [comment]
I can not test this as the state of the system is not the same as it was at the time of the bug report. I did though notice the same issue in a test yesterday in a clean Ubuntu 23.10 docker environment. Installing `pyqt5-dev-tools` via apt seemed to have fixed the issue.
