### ISSUE TITLE
An error has occurred while executing Python code

### ISSUE THREAD

**Issue by Nizom1994** [EnMAP-Box/enmap-box#480]
I am having problem with EnMAP box plugin.
Before It was working properly but suddenly started to give a error. 
Is there any way how to solve this problem?

Here is a massage below: 

An error has occurred while executing Python code: 
ImportError: DLL load failed while importing _ufuncs: The specified module could not be found. 
Traceback (most recent call last):
  File "C:\Users\dell\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\apps\lmuapps\lmuvegetationapps\enmapboxintegration.py", line 86, in start_GUI_IVVRM
    from lmuvegetationapps.IVVRM.IVVRM_GUI import MainUiFunc
  File "C:\Users/dell/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\PROGRA~1/QGIS32~1.5/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\dell\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\apps\lmuapps\lmuvegetationapps\IVVRM\IVVRM_GUI.py", line 29, in 
    from scipy.interpolate import interp1d
  File "C:\Users/dell/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\PROGRA~1/QGIS32~1.5/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\dell\AppData\Roaming\Python\Python39\site-packages\scipy\interpolate\__init__.py", line 166, in 
    from .interpolate import *
  File "C:\Users/dell/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\PROGRA~1/QGIS32~1.5/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\dell\AppData\Roaming\Python\Python39\site-packages\scipy\interpolate\interpolate.py", line 11, in 
    import scipy.special as spec
  File "C:\Users/dell/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\PROGRA~1/QGIS32~1.5/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\dell\AppData\Roaming\Python\Python39\site-packages\scipy\special\__init__.py", line 643, in 
    from . import _ufuncs
  File "C:\Users/dell/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\PROGRA~1/QGIS32~1.5/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: DLL load failed while importing _ufuncs: The specified module could not be found.

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.28.5-Firenze Firenze, 50adba36f2 

Python Path:
C:\Users\dell\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\apps\ensomap
C:\Users\dell\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\apps\ensomap
C:/PROGRA~1/QGIS32~1.5/apps/qgis-ltr/./python
C:/Users/dell/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/dell/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS32~1.5/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS32~1.5\apps\grass\grass82\etc\python
C:\Users\dell\Documents
C:\Program Files\QGIS 3.28.5\bin\python39.zip
C:\PROGRA~1\QGIS32~1.5\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.5\apps\Python39\lib
C:\Program Files\QGIS 3.28.5\bin
C:\Users\dell\AppData\Roaming\Python\Python39\site-packages
C:\PROGRA~1\QGIS32~1.5\apps\Python39
C:\PROGRA~1\QGIS32~1.5\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.5\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.5\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.5\apps\Python39\lib\site-packages\Pythonwin
C:/Users/dell/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\dell\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows
C:\Users/dell/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\site-packages
C:\Users\dell\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\qgispluginsupport\qps\pyqtgraph
C:\Users\dell\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\site-packages
C:\Users\dell\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\apps
C:\Users\dell\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\coreapps
C:\Users\dell\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\eo4qapps
.
C:\Users/dell/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\site-packages
C:\Users\dell\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\site-packages
C:\Users/dell/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\site-packages
C:\Users/dell/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin
C:\Users\dell\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\site-packages
C:\Users\dell\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\apps\lmuapps

**Comment by janzandr** [comment]
@Nizom1994 and @jakimowb are discussing this issue via email.
