### ISSUE TITLE
ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

### ISSUE THREAD

**Issue by dpoursanidis** [EnMAP-Box/enmap-box#495]
QGIS version: 3.28.3-Firenze
QGIS code revision: c12bcb2f76c
Qt version: 5.15.3
Python version: 3.9.5
GDAL version: 3.6.2
GEOS version: 3.11.1-CAPI-1.17.1
PROJ version: Rel. 9.1.1, December 1st, 2022
PDAL version: 2.4.3 (git-version: f8d673)
Algorithm started at: 2023-06-05T17:36:07
Algorithm 'Classification workflow' starting…
Input parameters:
{ 'classifier' : 'from sklearn.ensemble import RandomForestClassifier\nclassifier = RandomForestClassifier(n_estimators=100, oob_score=True)', 'dataset' : 'C:/Users/homoaquaticus/AppData/Local/Temp/processing_JpPMCv/c56f8c458f40477ca2b445fe685ce35d/outputClassificationDataset.pkl', 'nfold' : 10, 'openReport' : True, 'outputClassification' : 'C:/Users/homoaquaticus/Desktop/Mission 1120 Kos/Seagrass/05062022/classiciation.tif', 'outputClassifier' : 'C:/Users/homoaquaticus/Desktop/Mission 1120 Kos/Seagrass/05062022/class.pkl', 'outputClassifierPerformance' : 'C:/Users/homoaquaticus/Desktop/Mission 1120 Kos/Seagrass/05062022/accu.html', 'outputProbability' : 'C:/Users/homoaquaticus/Desktop/Mission 1120 Kos/Seagrass/05062022/propability.tif', 'raster' : 'C:/Users/homoaquaticus/Desktop/Mission 1120 Kos/Seagrass/Planet_5_bands.tif' }

Traceback (most recent call last):
File "C:\Users\homoaquaticus\AppData\Roaming\Python\Python39\site-packages\typeguard\__init__.py", line 1033, in wrapper
retval = func(*args, **kwargs)
File "C:\Users/homoaquaticus/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapboxprocessing\algorithm\fitclassifieralgorithmbase.py", line 98, in processAlgorithm
classifier.fit(dump.X, dump.y.ravel())
File "C:\Users\homoaquaticus\AppData\Roaming\Python\Python39\site-packages\sklearn\ensemble\_forest.py", line 327, in fit
X, y = self._validate_data(
File "C:\Users\homoaquaticus\AppData\Roaming\Python\Python39\site-packages\sklearn\base.py", line 581, in _validate_data
X, y = check_X_y(X, y, **check_params)
File "C:\Users\homoaquaticus\AppData\Roaming\Python\Python39\site-packages\sklearn\utils\validation.py", line 964, in check_X_y
X = check_array(
File "C:\Users\homoaquaticus\AppData\Roaming\Python\Python39\site-packages\sklearn\utils\validation.py", line 800, in check_array
_assert_all_finite(array, allow_nan=force_all_finite == "allow-nan")
File "C:\Users\homoaquaticus\AppData\Roaming\Python\Python39\site-packages\sklearn\utils\validation.py", line 114, in _assert_all_finite
raise ValueError(
ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

Execution failed after 0.14 seconds

Loading resulting layers
Algorithm 'Classification workflow' finished
HTML output has been generated by this algorithm.
Open the results dialog to check it.

Any idea how to tackle that?
Is the problem arrive from the raster imagery (Planet_5_bands.tif)?

**Comment by janzandr** [comment]
> Is the problem arrive from the raster imagery (Planet_5_bands.tif)?

Yes, the error **ValueError: Input contains NaN, infinity or a value too large for dtype('float32').** seams to indicates that. 

> Any idea how to tackle that?

Maybe we can/should filter invalid points automatically, to circumvent the problem. For now, you would need to fix the input raster manually.

Can you share your data for testing?

**Comment by dpoursanidis** [comment]
You have mail ;)

**Comment by janzandr** [comment]
At least one no data pixel is covered by the reference polygons:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/1a0da6c8-4b50-433b-b756-0fd5b42c2872)

I will automatically exclude those samples in the future.
