### ISSUE TITLE
IndexError when trying to import PRISMA L2D  data

### ISSUE THREAD

**Issue by danschef** [EnMAP-Box/enmap-box#497]
With the EnMAP-Box 3.13.alpha0, the PRISMA L2D import fails with the following error:

```python
QGIS-Version: 3.30.2-'s-Hertogenbosch
Qt-Version: 5.15.8
Python-Version: 3.11.3
GDAL-Version: 3.6.4
GEOS-Version: 3.11.2-CAPI-1.17.2
PROJ-Version: Rel. 9.2.0, March 1st, 2023
PDAL-Version: 2.5.3 (git-version: Release)
Algorithmus gestartet um: 2023-06-07T14:14:42
Algorithmus Import PRISMA L2D product startet…
Eingabeparameter:
{ 'badBandThreshold' : None, 'badPixelType' : [0], 'file' : 'X:\\PRISMA\\Tudela\\PRS_L2D_STD_20230416110146_20230416110150_0001.he5', 'outputPrismaL2D_spectralCube' : 'TEMPORARY_OUTPUT', 'spectralRegion' : 0 }

Reading data with h5py (v3.8.0) API: HDFEOS/SWATHS/PRS_L2D_HCO/Data Fields/VNIR_Cube
Reading data with h5py (v3.8.0) API: HDFEOS/SWATHS/PRS_L2D_HCO/Data Fields/SWIR_Cube
Traceback (most recent call last):
File "D:\Programme\mambaforge\envs\enpt_py311\Lib\site-packages\typeguard\__init__.py", line 1033, in wrapper
retval = func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "C:\Users/danschef/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapboxprocessing\algorithm\importprismal2dalgorithm.py", line 168, in processAlgorithm
self.writeSpectralCube(filenameSpectralCube, he5Filename, spectralRegion, badBandMultipliers, feedback)
File "D:\Programme\mambaforge\envs\enpt_py311\Lib\site-packages\typeguard\__init__.py", line 1033, in wrapper
retval = func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "C:\Users/danschef/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapboxprocessing\algorithm\importprismal2dalgorithm.py", line 250, in writeSpectralCube
writer = driver.createFromArray(array, extent, crs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Programme\mambaforge\envs\enpt_py311\Lib\site-packages\typeguard\__init__.py", line 1033, in wrapper
retval = func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "C:\Users/danschef/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapboxprocessing\driver.py", line 87, in createFromArray
raster = self.create(dataType=dataType, width=width, height=height, nBands=nBands, extent=extent, crs=crs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Programme\mambaforge\envs\enpt_py311\Lib\site-packages\typeguard\__init__.py", line 1033, in wrapper
retval = func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "C:\Users/danschef/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapboxprocessing\driver.py", line 53, in create
info = f'Create Raster [{width}x{height}x{nBands}]({Utils.qgisDataTypeName(dataType)})' \
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Programme\mambaforge\envs\enpt_py311\Lib\site-packages\typeguard\__init__.py", line 1033, in wrapper
retval = func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "C:\Users/danschef/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapboxprocessing\utils.py", line 91, in qgisDataTypeName
return str(dataType).split('.')[1]
~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

Execution failed after 58.66 Sekunden

Lade Ergebnis Layer
Algorithmus 'Import PRISMA L2D product' beendet
```

<details>
  <summary>Here is my environment.</summary>
  
  
  ```bash
  (enpt_py311) C:\Users\danschef>conda list
# packages in environment at D:\Programme\mambaforge\envs\enpt_py311:
#
# Name                    Version                   Build  Channel
_py-xgboost-mutex         2.0                       cpu_0    conda-forge
acwater                   0.3.0              pyhd8ed1ab_1    conda-forge
alabaster                 0.7.13                   pypi_0    pypi
ansi2html                 1.8.0                    pypi_0    pypi
aom                       3.5.0                h63175ca_0    conda-forge
arosics                   1.9.0           py311h1ea47a8_1    conda-forge
astroid                   2.15.5                   pypi_0    pypi
astropy                   5.2.2           py311h59ca53f_0    conda-forge
attrs                     23.1.0             pyh71513ae_1    conda-forge
babel                     2.12.1                   pypi_0    pypi
beautifulsoup4            4.12.2             pyha770c72_0    conda-forge
blas                      2.116                       mkl    conda-forge
blas-devel                3.9.0              16_win64_mkl    conda-forge
bleach                    6.0.0              pyhd8ed1ab_0    conda-forge
blosc                     1.21.4               hdccc3a2_0    conda-forge
bokeh                     3.1.1              pyhd8ed1ab_0    conda-forge
boost-cpp                 1.78.0               h9f4b32c_3    conda-forge
branca                    0.6.0              pyhd8ed1ab_0    conda-forge
brotli                    1.0.9                hcfcfb64_8    conda-forge
brotli-bin                1.0.9                hcfcfb64_8    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
c-blosc2                  2.8.0                h183a6f4_1    conda-forge
ca-certificates           2023.5.7             h56e8100_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cachetools                5.3.0              pyhd8ed1ab_0    conda-forge
cairo                     1.16.0            hdecc03f_1016    conda-forge
cartopy                   0.21.1          py311h178a126_1    conda-forge
catboost                  1.2             py311h1ea47a8_4    conda-forge
cdsapi                    0.6.1              pyhd8ed1ab_0    conda-forge
cerberus                  1.3.4              pyhd8ed1ab_0    conda-forge
ceres-solver              2.1.0                hb02fd38_1    conda-forge
certifi                   2023.5.7           pyhd8ed1ab_0    conda-forge
cfitsio                   4.2.0                h9ebe7e4_0    conda-forge
cftime                    1.6.2           py311h59ca53f_1    conda-forge
charls                    2.4.2                h1537add_0    conda-forge
charset-normalizer        3.1.0              pyhd8ed1ab_0    conda-forge
click                     8.1.3           win_pyhd8ed1ab_2    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.7.2              pyhd8ed1ab_1    conda-forge
cloudpickle               2.2.1              pyhd8ed1ab_0    conda-forge
cmocean                   3.0.3              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
colorcet                  3.0.1              pyhd8ed1ab_0    conda-forge
colorspacious             1.1.2              pyh24bf2e0_0    conda-forge
configobj                 5.0.8              pyhd8ed1ab_0    conda-forge
contourpy                 1.0.7           py311h005e61a_0    conda-forge
coverage                  7.2.6           py311ha68e1ae_0    conda-forge
curl                      8.1.1                h68f0423_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cython                    0.29.34         py311h12c1d0e_0    conda-forge
cytoolz                   0.12.0          py311ha68e1ae_1    conda-forge
dask-core                 2023.5.0           pyhd8ed1ab_0    conda-forge
dataclasses               0.8                pyhc8e2a94_3    conda-forge
dav1d                     1.2.0                hcfcfb64_0    conda-forge
dicttoxml                 1.7.16             pyhd8ed1ab_0    conda-forge
dill                      0.3.6              pyhd8ed1ab_1    conda-forge
docutils                  0.18.1                   pypi_0    pypi
draco                     1.5.6                h181d51b_0    conda-forge
eccodes                   2.30.0               h2993e7e_0    conda-forge
ecmwf-api-client          1.6.3              pyhd8ed1ab_0    conda-forge
eigen                     3.4.0                h2d74725_0    conda-forge
enpt                      0.19.2             pyhd8ed1ab_0    conda-forge
enpt_enmapboxapp          0.7.6              pyhd8ed1ab_0    conda-forge
et_xmlfile                1.1.0              pyhd8ed1ab_0    conda-forge
exceptiongroup            1.1.1              pyhd8ed1ab_0    conda-forge
exiv2                     0.27.6               hadc2d18_1    conda-forge
expat                     2.5.0                h63175ca_1    conda-forge
fake-useragent            1.1.3                    pypi_0    pypi
fftw                      3.3.10          nompi_h38027f0_107    conda-forge
filelock                  3.12.0             pyhd8ed1ab_0    conda-forge
fiona                     1.9.3           py311ha4db88c_0    conda-forge
flake8                    6.0.0                    pypi_0    pypi
folium                    0.14.0             pyhd8ed1ab_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.2               hbde0cde_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.39.4          py311ha68e1ae_0    conda-forge
freeglut                  3.2.2                h63175ca_2    conda-forge
freetype                  2.12.1               h546665d_1    conda-forge
freexl                    1.0.6                h67ca5e6_1    conda-forge
fribidi                   1.0.10               h8d14728_0    conda-forge
fsspec                    2023.5.0           pyh1a96a4e_0    conda-forge
future                    0.18.3             pyhd8ed1ab_0    conda-forge
gdal                      3.6.4           py311heaf1029_2    conda-forge
gdown                     4.7.1              pyhd8ed1ab_0    conda-forge
geoarray                  0.16.1          py311h1ea47a8_0    conda-forge
geojson                   3.0.1              pyhd8ed1ab_0    conda-forge
geopandas                 0.13.0             pyhd8ed1ab_0    conda-forge
geopandas-base            0.13.0             pyha770c72_0    conda-forge
geos                      3.11.2               h1537add_0    conda-forge
geotiff                   1.7.1                h7222e44_8    conda-forge
getopt-win32              0.1                  h8ffe710_0    conda-forge
gettext                   0.21.1               h5728263_0    conda-forge
gflags                    2.2.2             ha925a31_1004    conda-forge
giflib                    5.2.1                h64bf75a_3    conda-forge
glib                      2.76.3               h12be248_0    conda-forge
glib-tools                2.76.3               h12be248_0    conda-forge
glog                      0.6.0                h4797de2_0    conda-forge
glymur                    0.12.7             pyhd8ed1ab_0    conda-forge
graphite2                 1.3.13                     1000    conda-forge
graphviz                  8.0.5                h51cb2cd_0    conda-forge
gsl                       2.7                  hdfb1a43_0    conda-forge
gst-plugins-base          1.22.3               h001b923_1    conda-forge
gstreamer                 1.22.3               h6b5321d_1    conda-forge
gts                       0.7.6                h7c369d9_2    conda-forge
h5py                      3.8.0           nompi_py311hfbc32a6_101    conda-forge
harfbuzz                  7.3.0                h196d34a_0    conda-forge
hdf4                      4.2.15               h1334946_6    conda-forge
hdf5                      1.14.0          nompi_h918d9b7_103    conda-forge
holoviews                 1.16.0             pyhd8ed1ab_0    conda-forge
htmlmin                   0.1.12                   pypi_0    pypi
httplib2                  0.22.0             pyhd8ed1ab_0    conda-forge
icu                       72.1                 h63175ca_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
imagecodecs               2023.1.23       py311h2c9abbb_2    conda-forge
imageio                   2.28.1             pyh24c5eb1_0    conda-forge
imagesize                 1.4.1                    pypi_0    pypi
importlib-metadata        6.6.0              pyha770c72_0    conda-forge
importlib_metadata        6.6.0                hd8ed1ab_0    conda-forge
iniconfig                 2.0.0              pyhd8ed1ab_0    conda-forge
intel-openmp              2023.1.0         h57928b3_46319    conda-forge
iso8601                   1.1.0              pyhd8ed1ab_0    conda-forge
isofit                    1.1.6                      py_1    conda-forge
isort                     5.12.0                   pypi_0    pypi
jasper                    4.0.0                h00710e9_1    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
joblib                    1.2.0              pyhd8ed1ab_0    conda-forge
jsmin                     3.0.1              pyhd8ed1ab_0    conda-forge
jxrlib                    1.1                  h8ffe710_2    conda-forge
kealib                    1.5.1                hc8369a0_3    conda-forge
kiwisolver                1.4.4           py311h005e61a_1    conda-forge
krb5                      1.20.1               heb0366b_0    conda-forge
laz-perf                  3.3.0                h91493d7_0    conda-forge
lazy-object-proxy         1.9.0                    pypi_0    pypi
lazy_loader               0.2                pyhd8ed1ab_0    conda-forge
lcms2                     2.15                 h3e3b177_1    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libaec                    1.0.6                h63175ca_1    conda-forge
libavif                   0.11.1               h5da7522_1    conda-forge
libblas                   3.9.0              16_win64_mkl    conda-forge
libbrotlicommon           1.0.9                hcfcfb64_8    conda-forge
libbrotlidec              1.0.9                hcfcfb64_8    conda-forge
libbrotlienc              1.0.9                hcfcfb64_8    conda-forge
libcblas                  3.9.0              16_win64_mkl    conda-forge
libclang                  16.0.3          default_h8b4101f_1    conda-forge
libclang13                16.0.3          default_h45d3cf4_1    conda-forge
libcurl                   8.1.1                h68f0423_0    conda-forge
libdeflate                1.18                 hcfcfb64_0    conda-forge
libexpat                  2.5.0                h63175ca_1    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libgd                     2.3.3                h2ed9e1d_6    conda-forge
libgdal                   3.6.4                h36c8192_2    conda-forge
libglib                   2.76.3               he8f3873_0    conda-forge
libhwloc                  2.9.1                h51c2c0f_0    conda-forge
libiconv                  1.17                 h8ffe710_0    conda-forge
libjpeg-turbo             2.1.5.1              hcfcfb64_0    conda-forge
libkml                    1.3.0             hf2ab4e4_1015    conda-forge
liblapack                 3.9.0              16_win64_mkl    conda-forge
liblapacke                3.9.0              16_win64_mkl    conda-forge
libnetcdf                 4.9.2           nompi_hc664c2b_104    conda-forge
libogg                    1.3.4                h8ffe710_1    conda-forge
libpng                    1.6.39               h19919ed_0    conda-forge
libpq                     15.3                 ha9684e8_0    conda-forge
libprotobuf               3.21.12              h12be248_0    conda-forge
librttopo                 1.1.0               he1da8c1_13    conda-forge
libspatialindex           1.9.3                h39d44d4_4    conda-forge
libspatialite             5.0.1               h50a8ebb_25    conda-forge
libsqlite                 3.42.0               hcfcfb64_0    conda-forge
libssh2                   1.10.0               h9a1e1f7_3    conda-forge
libtiff                   4.5.0                h6c8260b_6    conda-forge
libvorbis                 1.3.7                h0e60522_0    conda-forge
libwebp                   1.3.0                hcfcfb64_0    conda-forge
libwebp-base              1.3.0                hcfcfb64_0    conda-forge
libxcb                    1.15                 hcd874cb_0    conda-forge
libxgboost                1.7.4            cpu_h20390bd_0    conda-forge
libxml2                   2.10.4               hc3477c8_0    conda-forge
libxslt                   1.1.37               h0192164_0    conda-forge
libzip                    1.9.2                h519de47_1    conda-forge
libzlib                   1.2.13               hcfcfb64_4    conda-forge
libzopfli                 1.0.3                h0e60522_0    conda-forge
lightgbm                  3.3.5           py311h12c1d0e_0    conda-forge
linkify-it-py             2.0.0              pyhd8ed1ab_0    conda-forge
llvmlite                  0.40.0          py311h5bc0dda_0    conda-forge
locket                    1.0.0              pyhd8ed1ab_0    conda-forge
lxml                      4.9.2           py311h5942461_0    conda-forge
lz4-c                     1.9.4                hcfcfb64_0    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
mapclassify               2.5.0              pyhd8ed1ab_1    conda-forge
markdown                  3.4.3              pyhd8ed1ab_0    conda-forge
markdown-it-py            2.2.0              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.2           py311ha68e1ae_0    conda-forge
matplotlib                3.7.1           py311h1ea47a8_0    conda-forge
matplotlib-base           3.7.1           py311h6e989c2_0    conda-forge
mccabe                    0.7.0                    pypi_0    pypi
mdit-py-plugins           0.3.5              pyhd8ed1ab_0    conda-forge
mdurl                     0.1.0              pyhd8ed1ab_0    conda-forge
mkl                       2022.1.0           h6a75c08_874    conda-forge
mkl-devel                 2022.1.0           h57928b3_875    conda-forge
mkl-include               2022.1.0           h6a75c08_874    conda-forge
mock                      5.0.2              pyhd8ed1ab_0    conda-forge
mpld3                     0.5.9              pyhd8ed1ab_0    conda-forge
mpmath                    1.3.0              pyhd8ed1ab_0    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
munch                     3.0.0              pyhd8ed1ab_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
mvgavg                    0.1.0              pyh9f0ad1d_0    conda-forge
natsort                   8.3.1              pyhd8ed1ab_0    conda-forge
netcdf4                   1.6.3           nompi_py311h896b27b_102    conda-forge
networkx                  3.1                pyhd8ed1ab_0    conda-forge
nitro                     2.7.dev8             h1537add_0    conda-forge
nose2                     0.9.2                      py_0    conda-forge
numba                     0.57.0          py311h2c0921f_0    conda-forge
numexpr                   2.8.4           mkl_py311h9a3bfb6_0    conda-forge
numpy                     1.23.5          py311h95d790f_0    conda-forge
numpy-indexed             0.3.7              pyhd8ed1ab_0    conda-forge
openjpeg                  2.5.0                ha2aaf27_2    conda-forge
openpyxl                  3.1.2           py311ha68e1ae_0    conda-forge
openssl                   3.1.0                hcfcfb64_3    conda-forge
owslib                    0.29.2             pyhd8ed1ab_0    conda-forge
packaging                 23.1               pyhd8ed1ab_0    conda-forge
pandas                    2.0.1           py311hf63dbb6_1    conda-forge
panel                     1.0.2              pyhd8ed1ab_0    conda-forge
pango                     1.50.14              hd64ce24_1    conda-forge
param                     1.13.0             pyh1a96a4e_0    conda-forge
partd                     1.4.0              pyhd8ed1ab_0    conda-forge
pcre2                     10.40                h17e33f8_0    conda-forge
pdal                      2.5.3                hac3c4d1_0    conda-forge
pebble                    5.0.3              pyhd8ed1ab_0    conda-forge
pep8                      1.7.1                      py_0    conda-forge
pillow                    9.5.0           py311hde623f7_1    conda-forge
pint                      0.21               pyhd8ed1ab_0    conda-forge
pip                       23.1.2             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h8ffe710_0    conda-forge
platformdirs              3.5.1              pyhd8ed1ab_0    conda-forge
plotly                    5.14.1             pyhd8ed1ab_0    conda-forge
pluggy                    1.0.0              pyhd8ed1ab_5    conda-forge
ply                       3.11                       py_1    conda-forge
pooch                     1.7.0              pyha770c72_3    conda-forge
poppler                   23.05.0              h45d20d0_1    conda-forge
poppler-data              0.4.12               hd8ed1ab_0    conda-forge
postgresql                15.3                 hd87cd2b_0    conda-forge
proj                      9.2.0                heca977f_0    conda-forge
psutil                    5.9.5           py311ha68e1ae_0    conda-forge
psycopg2                  2.9.3           py311hb12f294_2    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pthreads-win32            2.9.1                hfa6e2cd_3    conda-forge
py-cpuinfo                9.0.0              pyhd8ed1ab_0    conda-forge
py-tools-ds               0.21.1          py311h1ea47a8_0    conda-forge
py-xgboost                1.7.4           cpu_py311h3180b0a_0    conda-forge
pycodestyle               2.10.0                   pypi_0    pypi
pyct                      0.4.6                      py_0    conda-forge
pyct-core                 0.4.6                      py_0    conda-forge
pydocstyle                6.3.0                    pypi_0    pypi
pyepsg                    0.4.0                      py_0    conda-forge
pyerfa                    2.0.0.3         py311h59ca53f_0    conda-forge
pyfftw                    0.13.1          py311he023d06_0    conda-forge
pyflakes                  3.0.1                    pypi_0    pypi
pygments                  2.15.1             pyhd8ed1ab_0    conda-forge
pygrib                    2.1.4           py311hb25bc96_7    conda-forge
pyhdf                     0.10.5          py311h702c2b7_1    conda-forge
pykdtree                  1.3.7.post0     py311h59ca53f_0    conda-forge
pykrige                   1.7.0           py311h59ca53f_1    conda-forge
pylint                    2.17.4                   pypi_0    pypi
pyopengl                  3.1.6              pyhd8ed1ab_1    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyprind                   2.11.2          py311h1ea47a8_1004    conda-forge
pyproj                    3.5.0           py311h095e9de_1    conda-forge
pyqt                      5.15.7          py311h125bc19_3    conda-forge
pyqt5-sip                 12.11.0         py311h12c1d0e_3    conda-forge
pyqtwebkit                5.15.9          py311h5a77453_1    conda-forge
pyresample                1.27.0          py311hf63dbb6_0    conda-forge
pyrsr                     0.7.0              pyhd8ed1ab_1    conda-forge
pyshp                     2.3.1              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyh0701188_6    conda-forge
pytables                  3.8.0           py311h6e06090_1    conda-forge
pytest                    7.3.1              pyhd8ed1ab_0    conda-forge
pytest-cov                4.1.0                    pypi_0    pypi
pytest-reporter           0.5.2                    pypi_0    pypi
pytest-reporter-html1     0.8.2                    pypi_0    pypi
python                    3.11.3          h2628c8c_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-graphviz           0.20.1             pyh22cad53_0    conda-forge
python-tzdata             2023.3             pyhd8ed1ab_0    conda-forge
python-xxhash             3.2.0           py311ha68e1ae_0    conda-forge
python_abi                3.11                    3_cp311    conda-forge
pytz                      2023.3             pyhd8ed1ab_0    conda-forge
pyviz_comms               2.3.0              pyhd8ed1ab_0    conda-forge
pywavelets                1.4.1           py311h59ca53f_0    conda-forge
pyyaml                    6.0             py311ha68e1ae_5    conda-forge
qca                       2.3.6                h2624d1c_0    conda-forge
qgis                      3.30.2          py311h1e9536a_1    conda-forge
qjson                     0.9.0             h04a78d6_1009    conda-forge
qscintilla2               2.14.0          py311h5a77453_0    conda-forge
qt-main                   5.15.8              h2c8576c_11    conda-forge
qtkeychain                0.14.0               h04a78d6_0    conda-forge
qtwebkit                  5.212               hab0d466_10    conda-forge
qwt                       6.2.0                h07be427_5    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
rtree                     1.0.1           py311hcacb13a_1    conda-forge
scikit-image              0.20.0          py311hf63dbb6_1    conda-forge
scikit-learn              1.2.2           py311h142b183_1    conda-forge
scipy                     1.10.1          py311h37ff6ca_3    conda-forge
sensormapgeo              0.7.0           py311h1ea47a8_0    conda-forge
setuptools                67.7.2             pyhd8ed1ab_0    conda-forge
shapely                   2.0.1           py311h343093d_1    conda-forge
sicor                     0.19.0             pyhd8ed1ab_0    conda-forge
sip                       6.7.9           py311h12c1d0e_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.10               hfb803bf_0    conda-forge
snowballstemmer           2.2.0                    pypi_0    pypi
soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
spectral                  0.23.1             pyh1a96a4e_0    conda-forge
sphinx                    6.2.1                    pypi_0    pypi
sphinx-argparse           0.4.0                    pypi_0    pypi
sphinx-rtd-theme          1.2.1                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.4                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.0.1                    pypi_0    pypi
sphinxcontrib-jquery      4.1                      pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.5                    pypi_0    pypi
sqlite                    3.42.0               hcfcfb64_0    conda-forge
suitesparse               5.4.0                h5d0cbe0_1    conda-forge
sympy                     1.12               pyh04b8f61_3    conda-forge
tbb                       2021.9.0             h91493d7_0    conda-forge
tenacity                  8.2.2              pyhd8ed1ab_0    conda-forge
threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge
tifffile                  2023.4.12          pyhd8ed1ab_0    conda-forge
tiledb                    2.13.2               h3132609_0    conda-forge
tk                        8.6.12               h8ffe710_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tomlkit                   0.11.8                   pypi_0    pypi
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tornado                   6.3.2           py311ha68e1ae_0    conda-forge
tqdm                      4.65.0             pyhd8ed1ab_1    conda-forge
typeguard                 2.13.3             pyhd8ed1ab_0    conda-forge
typing-extensions         4.6.1                hd8ed1ab_0    conda-forge
typing_extensions         4.6.1              pyha770c72_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
uc-micro-py               1.0.1              pyhd8ed1ab_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
urlchecker                0.0.34                   pypi_0    pypi
urllib3                   2.0.2              pyhd8ed1ab_0    conda-forge
utm                       0.7.0              pyhd8ed1ab_0    conda-forge
vc                        14.3                hb25d44b_16    conda-forge
vc14_runtime              14.34.31931         h5081d32_16    conda-forge
vs2015_runtime            14.34.31931         hed1258a_16    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
win_inet_pton             1.1.0              pyhd8ed1ab_6    conda-forge
wrapt                     1.15.0                   pypi_0    pypi
xarray                    2023.5.0           pyhd8ed1ab_0    conda-forge
xerces-c                  3.2.4                h63175ca_2    conda-forge
xgboost                   1.7.4           cpu_py311h3180b0a_0    conda-forge
xlrd                      2.0.1              pyhd8ed1ab_3    conda-forge
xorg-kbproto              1.0.7             hcd874cb_1002    conda-forge
xorg-libice               1.0.10               hcd874cb_0    conda-forge
xorg-libsm                1.2.3             hcd874cb_1000    conda-forge
xorg-libx11               1.8.4                hefa74cf_1    conda-forge
xorg-libxau               1.0.11               hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xorg-libxext              1.3.4                hcd874cb_2    conda-forge
xorg-libxpm               3.5.13               hcd874cb_0    conda-forge
xorg-libxt                1.2.1                hcd874cb_2    conda-forge
xorg-xextproto            7.3.0             hcd874cb_1003    conda-forge
xorg-xproto               7.0.31            hcd874cb_1007    conda-forge
xxhash                    0.8.1                hcfcfb64_0    conda-forge
xyzservices               2023.5.0           pyhd8ed1ab_1    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
zfp                       1.0.0                h63175ca_3    conda-forge
zipp                      3.15.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               hcfcfb64_4    conda-forge
zlib-ng                   2.0.7                hcfcfb64_0    conda-forge
zstd                      1.5.2                h12be248_6    conda-forge
  ```
  
</details>

**Comment by janzandr** [comment]
Hi @danschef, please execute this in your Python Console:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/ca63cb2c-30ac-487c-aeaf-74a7cc3ed834)

What is the output?

**Comment by danschef** [comment]
```python
>>> str(Qgis.DataType.Float64)
'7'
```

**Comment by janzandr** [comment]
Alright, the str() logic for QGIS DataTypes seams to have changed. Will fix this.

**Comment by danschef** [comment]
Ok, would be nice if the fix would not break the LTR support.

**Comment by janzandr** [comment]
We are developing on LTR, so this is unlikely to happen ;-)

**Comment by danschef** [comment]
@janzandr Any reason why https://github.com/EnMAP-Box/enmap-box/pull/498 was only merged into the `release_3.12` branch and not into `main`? As a user, I would expect that I can use the fixed code by building the EnMAP-Box by myself from the `main` branch, which does not work.

**Comment by janzandr** [comment]
> @janzandr Any reason why #498 was only merged into the `release_3.12` branch and not into `main`? As a user, I would expect that I can use the fixed code by building the EnMAP-Box by myself from the `main` branch, which does not work.

Hmm, something went wrong I guess. Should be fixed now.
