### ISSUE TITLE
TypeError: QgsMapToolAddFeature.__init__() got multiple values for argument 'mode'

### ISSUE THREAD

**Issue by danschef** [EnMAP-Box/enmap-box#516]
- EnMAP-Box Version 3.13.0alpha0.20230619T163435.main Code [41eceb4b141](https://github.com/EnMAP-Box/enmap-box/commit/41eceb4b1411c25f04d6b4498a73f48f5a4931ab)
- QGIS 
- QGIS 3.30.3-'s-Hertogenbosch
- Python 3.11
- Windows 11

I just opened EnMAP VNIR and SWIR BSQ files by dragging/dropping them into the EnMAP-Box, unfolded the bands entry, hit right click on the first band and clicked `Open in new map`:
![grafik](https://github.com/EnMAP-Box/enmap-box/assets/16669114/36c6c20c-35ee-49ab-8d08-a2b121302133)

Then the EnMAP-Box raised the following error without showing any map:

```python
Ein Fehler trat bei der Ausführung von Python-Code auf: 

TypeError: QgsMapToolAddFeature.__init__() got multiple values for argument 'mode' 
Traceback (most recent call last):
  File "C:\Users/danschef/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\gui\datasources\manager.py", line 586, in 
    a.triggered.connect(lambda *args, n=node: self.openInMap(n.rasterSource(), rgb=[n.bandIndex()]))
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/danschef/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\gui\datasources\manager.py", line 667, in openInMap
    dock = emb.createDock('MAP')
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/danschef/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\gui\enmapboxgui.py", line 1961, in createDock
    return self.mDockManager.createDock(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/danschef/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\gui\dataviews\dockmanager.py", line 719, in createDock
    dock = cls(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users/danschef/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\gui\dataviews\docks.py", line 893, in __init__
    self.mCanvas: MapCanvas = MapCanvas(self)
                              ^^^^^^^^^^^^^^^
  File "C:\Users/danschef/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\gui\mapcanvas.py", line 899, in __init__
    self.mMapTools = MapCanvasMapTools(self, self.mCadDock)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/danschef/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\gui\mapcanvas.py", line 810, in __init__
    self.mtAddFeature = QgsMapToolAddFeature(canvas, cadDock, mode=QgsMapToolCapture.CaptureNone)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: QgsMapToolAddFeature.__init__() got multiple values for argument 'mode'


Python-Version: 3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 17:59:51) [MSC v.1935 64 bit (AMD64)] 
QGIS-Version: 3.30.3-'s-Hertogenbosch 's-Hertogenbosch, exported 
```

**Comment by danschef** [comment]
The same issue ocurrs with QGIS 3.28.7-Firenze (latest LTR).

**Comment by jakimowb** [comment]
I cannot reproduce the error (EnMAP-box 3.12.1 Code. neither QGIS .28.8, nor QGIS 3.32)

@danschef :
- can you create an empty map view? [View -> Add Map View]?
- does the error occure when using the standard example data? [Project -> Add Example Data]?
- does the error occure only after dropping your EnMAP data set?

**Comment by danschef** [comment]
It seems to work with the EnMAP-Box 3.12 but not with the latest experimental version (3.13).

**Comment by danschef** [comment]
@jakimowb
After recreating the entire environment with `mamba env create -n enpt_full_fixed2 -f https://git.gfz-potsdam.de/EnMAP/GFZ_Tools_EnMAP_BOX/EnPT/-/raw/main/tests/gitlab_CI_docker/context/environment_enpt_full_dev.yml`, I can also not reproduce it anymore (EnMAP-Box 3.13.0-alpha-0). So, I think we can close this for now.

However, I am still blocked by #488.
