### ISSUE TITLE
Can not open Map View

### ISSUE THREAD

**Issue by thielfab** [EnMAP-Box/enmap-box#570]
After clicking *Open a Map View* button:
```
An error has occurred while executing Python code: 

TypeError: __init__() got multiple values for argument 'mode' 
Traceback (most recent call last):
  File "C:\Users/fabian/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\gui\enmapboxgui.py", line 1265, in 
    self.ui.mActionLoadExampleData.triggered.connect(lambda: self.openExampleData(
  File "C:\Users/fabian/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\gui\enmapboxgui.py", line 1839, in openExampleData
    dock: MapDock = self.createDock('MAP')
  File "C:\Users/fabian/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\gui\enmapboxgui.py", line 2053, in createDock
    return self.mDockManager.createDock(*args, **kwds)
  File "C:\Users/fabian/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\gui\dataviews\dockmanager.py", line 721, in createDock
    dock = cls(*args, **kwds)
  File "C:\Users/fabian/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\gui\dataviews\docks.py", line 882, in __init__
    self.mCanvas: MapCanvas = MapCanvas(self)
  File "C:\Users/fabian/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\gui\mapcanvas.py", line 897, in __init__
    self.mMapTools = MapCanvasMapTools(self, self.mCadDock)
  File "C:\Users/fabian/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\gui\mapcanvas.py", line 808, in __init__
    self.mtAddFeature = QgsMapToolAddFeature(canvas, cadDock, mode=QgsMapToolCapture.CaptureNone)
TypeError: __init__() got multiple values for argument 'mode'

```
Seems to be related to **QGIS 3.32.2-Lima**
EnMAP-Box Version 3.13.0alpha0.20230818T122709.main Code [7dd220072a9](https://github.com/EnMAP-Box/enmap-box/commit/7dd220072a99218b246702752e6604ef0c0cff6c)

**Comment by thielfab** [comment]
qgispluginsupport was not up to date when building the plugin

**Comment by janzandr** [comment]
> qgispluginsupport was not up to date when building the plugin

Not sure what that means? As far as I know, you don't have to have deal with the _qgispluginsupport_ repo manually.
All _qgispluginsupport_ code should be part of the EnMAP-Box repo.

How have you fixed the problem? Or did @jakimowb fixed it by updating the qps dependency?

**Comment by thielfab** [comment]
I forgot to `git submodule update --remote`

**Comment by janzandr** [comment]
> I forgot to `git submodule update --remote`

@jakimowb, is that really necessary? I never do this.
