### ISSUE TITLE
TypeError when running PRISMA L2D import in batch

### ISSUE THREAD

**Issue by danschef** [EnMAP-Box/enmap-box#584]
EnMAP-Box 3.13.alpha0
QGIS 3.32.2

When I run the PRISMA L2D import tool in batch processing, I get a TypeError, although I think the parameters are set correctly:

```python

Verarbeite Algorithmus 1/2…
Algorithmus Import PRISMA L2D product startet…
Eingabeparameter:
{"badBandThreshold":null,"badPixelType":[0],"file":"X:\\PRISMA\\Demmin\\PRS_L2D_STD_20220530102458_20220530102503_0001.he5","outputPrismaL2D_panCube":"","outputPrismaL2D_panErrorMatrix":"","outputPrismaL2D_panGeolocationFields":"","outputPrismaL2D_spectralCube":"X:/HS_ARD/Demmin/PRS_L2D_STD_20220530102458_20220530102503_0001.bsq","outputPrismaL2D_spectralErrorMatrix":"","outputPrismaL2D_spectralGeolocationFields":"","outputPrismaL2D_spectralGeometricFields":"","spectralRegion":0}

Traceback (most recent call last):
File "D:\Programme\mambaforge\envs\enpt_full_dev\Lib\site-packages\typeguard\__init__.py", line 1033, in wrapper
retval = func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "C:\Users/danschef/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapboxprocessing\algorithm\importprismal2dalgorithm.py", line 141, in processAlgorithm
filenameSpectralGeolocation = self.parameterAsOutputLayer(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Programme\mambaforge\envs\enpt_full_dev\Lib\site-packages\typeguard\__init__.py", line 1033, in wrapper
retval = func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "C:\Users/danschef/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapboxprocessing\enmapalgorithm.py", line 429, in parameterAsOutputLayer
if not isabs(filename):
^^^^^^^^^^^^^^^
File "<frozen ntpath>", line 89, in isabs
TypeError: expected str, bytes or os.PathLike object, not QgsProcessingOutputLayerDefinition

Algorithmus Import PRISMA L2D product gescheitert…
Ausführung nach 0.196 Sekunden gescheitert

Verarbeite Algorithmus 2/2…
Algorithmus Import PRISMA L2D product startet…
Eingabeparameter:
{"badBandThreshold":null,"badPixelType":[0],"file":"X:\\PRISMA\\Demmin\\PRS_L2D_STD_20220709101510_20220709101515_0001.he5","outputPrismaL2D_panCube":"","outputPrismaL2D_panErrorMatrix":"","outputPrismaL2D_panGeolocationFields":"","outputPrismaL2D_spectralCube":"X:/HS_ARD/Demmin/PRS_L2D_STD_20220709101510_20220709101515_0001.bsq","outputPrismaL2D_spectralErrorMatrix":"","outputPrismaL2D_spectralGeolocationFields":"","outputPrismaL2D_spectralGeometricFields":"","spectralRegion":0}

Traceback (most recent call last):
File "D:\Programme\mambaforge\envs\enpt_full_dev\Lib\site-packages\typeguard\__init__.py", line 1033, in wrapper
retval = func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "C:\Users/danschef/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapboxprocessing\algorithm\importprismal2dalgorithm.py", line 141, in processAlgorithm
filenameSpectralGeolocation = self.parameterAsOutputLayer(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Programme\mambaforge\envs\enpt_full_dev\Lib\site-packages\typeguard\__init__.py", line 1033, in wrapper
retval = func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "C:\Users/danschef/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapboxprocessing\enmapalgorithm.py", line 429, in parameterAsOutputLayer
if not isabs(filename):
^^^^^^^^^^^^^^^
File "<frozen ntpath>", line 89, in isabs
TypeError: expected str, bytes or os.PathLike object, not QgsProcessingOutputLayerDefinition

Algorithmus Import PRISMA L2D product gescheitert…
Ausführung nach 0.06 Sekunden gescheitert
Stapelverarbeitung nach 0.308 Sekunden abgeschlossen
2 Ausführungen gescheitert. Mehr Details im Protokoll.
```

**Comment by janzandr** [comment]
Confirmed

**Comment by janzandr** [comment]
@jakimowb can you quickly fix #585?

**Comment by danschef** [comment]
Thanks @janzandr for the quick fix.

**Comment by janzandr** [comment]
Is already available here: https://github.com/EnMAP-Box/enmap-box/releases/tag/v3.13-alpha.1
