### ISSUE TITLE
classificationfromrenderedimagealgorithm.py: TypeError (Python 3.10)

### ISSUE THREAD

**Issue by jakimowb** [EnMAP-Box/enmap-box#626]
see https://github.com/EnMAP-Box/enmap-box/actions/runs/6202947597/job/16842698104?pr=625 for more details.

```
 Logged critical: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/typeguard/__init__.py", line 1033, in wrapper
    retval = func(*args, **kwargs)
  File "/usr/src/enmapboxprocessing/algorithm/classificationfromrenderedimagealgorithm.py", line 64, in processAlgorithm
    categories.append(Category(v, name, color))
  File "/usr/local/lib/python3.10/dist-packages/typeguard/__init__.py", line 1032, in wrapper
    check_argument_types(memo)
  File "/usr/local/lib/python3.10/dist-packages/typeguard/__init__.py", line 875, in check_argument_types
    raise TypeError(*exc.args) from None
TypeError: type of argument "value" must be one of (int, float, str); got numpy.uint32 instead
```

**Comment by janzandr** [comment]
Hmm, yes, makes sense that typeguard complains. But why isn't the test failing locally?

**Comment by janzandr** [comment]
@jakimowb can I see the package versions in the report summary somewhere?

**Comment by janzandr** [comment]
Just for my understanding: where can I see which YML file is used?
Is this the YML, which produces the error?
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/db11259b-5d74-47d9-ba9f-f65a8fc5557c)

**Comment by janzandr** [comment]
should work now
