### ISSUE TITLE
[Location Browser] gives requests.exceptions.JSONDecodeError

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#636]
Just search for e.g. **berlin**:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/d7827430-fb12-40d2-a9a4-d60c32f39c9b)

```
An error has occurred while executing Python code: 

requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0) 
Traceback (most recent call last):
  File "D:\QGIS\apps\Python39\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "D:\QGIS\apps\Python39\lib\site-packages\simplejson\__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "D:\QGIS\apps\Python39\lib\site-packages\simplejson\decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "D:\QGIS\apps\Python39\lib\site-packages\simplejson\decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Andreas\AppData\Roaming\QGIS\QGIS3\profiles\EnMAP-Box Develop\python\plugins\enmapboxplugin\enmapbox\eo4qapps\locationbrowserapp\locationbrowserdockwidget.py", line 133, in onRequestNominatimClicked
    nominatimResults = requests.get(url).json()
  File "D:\QGIS\apps\Python39\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)


Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.28.8-Firenze Firenze, 5ac45272 

Python Path:
C:\Users/Andreas/AppData/Roaming/QGIS/QGIS3\profiles\EnMAP-Box Develop/python/plugins\Coregistration
D:/QGIS/apps/qgis-ltr/./python
C:/Users/Andreas/AppData/Roaming/QGIS/QGIS3\profiles\EnMAP-Box Develop/python
C:/Users/Andreas/AppData/Roaming/QGIS/QGIS3\profiles\EnMAP-Box Develop/python/plugins
D:/QGIS/apps/qgis-ltr/./python/plugins
D:\QGIS\apps\grass\grass83\etc\python
C:\Users\Andreas\Documents
D:\QGIS\bin\python39.zip
D:\QGIS\apps\Python39\DLLs
D:\QGIS\apps\Python39\lib
D:\QGIS\bin
C:\Users\Andreas\AppData\Roaming\Python\Python39\site-packages
D:\QGIS\apps\Python39
D:\QGIS\apps\Python39\lib\site-packages
D:\QGIS\apps\Python39\lib\site-packages\win32
D:\QGIS\apps\Python39\lib\site-packages\win32\lib
D:\QGIS\apps\Python39\lib\site-packages\Pythonwin
C:/Users/Andreas/AppData/Roaming/QGIS/QGIS3\profiles\EnMAP-Box Develop/python
C:\Users\Andreas\AppData\Roaming\QGIS\QGIS3\profiles\EnMAP-Box Develop\python\plugins\ee_plugin\extlibs_windows
C:\Users/Andreas/AppData/Roaming/QGIS/QGIS3\profiles\EnMAP-Box Develop/python/plugins\enmapboxplugin\site-packages
C:\Users/Andreas/AppData/Roaming/QGIS/QGIS3\profiles\EnMAP-Box Develop/python/plugins\enmapboxplugin
C:\Users\Andreas\AppData\Roaming\QGIS\QGIS3\profiles\EnMAP-Box Develop\python\plugins\enmapboxplugin\enmapbox\qgispluginsupport\qps\pyqtgraph
C:\Users\Andreas\AppData\Roaming\QGIS\QGIS3\profiles\EnMAP-Box Develop\python\plugins\enmapboxplugin\enmapbox\site-packages
C:\Users\Andreas\AppData\Roaming\QGIS\QGIS3\profiles\EnMAP-Box Develop\python\plugins\enmapboxplugin\enmapbox\apps
C:\Users\Andreas\AppData\Roaming\QGIS\QGIS3\profiles\EnMAP-Box Develop\python\plugins\enmapboxplugin\enmapbox\coreapps
C:\Users\Andreas\AppData\Roaming\QGIS\QGIS3\profiles\EnMAP-Box Develop\python\plugins\enmapboxplugin\enmapbox\eo4qapps
.
C:\Users\Andreas\AppData\Roaming\QGIS\QGIS3\profiles\EnMAP-Box Develop\python\plugins\qgis_stac\lib
C:\Users/Andreas/AppData/Roaming/QGIS/QGIS3\profiles\EnMAP-Box Develop/python/plugins\timeseriesviewerplugin
C:\Users\Andreas\AppData\Roaming\QGIS\QGIS3\profiles\EnMAP-Box Develop\python\plugins\timeseriesviewerplugin\eotimeseriesviewer
C:\Users/Andreas/AppData/Roaming/QGIS/QGIS3\profiles\EnMAP-Box Develop/python/plugins\vrtbuilderplugin
C:\Users\Andreas\AppData\Roaming\QGIS\QGIS3\profiles\EnMAP-Box Develop\python\plugins\vrtbuilderplugin\vrtbuilder
```

**Comment by janzandr** [comment]
The request url format has changed:
https://www.drupal.org/project/geolocation/issues/3378805
