### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by xiaokaichen1111** [EnMAP-Box/enmap-box#663]
When I make ANN inversion,and input the input image,the error is as folloes:
2023-10-01T05:57:35     WARNING    Traceback (most recent call last):
              File "C:\Users\18306\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\apps\lmuapps\lmuvegetationapps\Processor\Processor_Inversion_GUI.py", line 131, in 
              self.gui.mLayerImage.layerChanged.connect(lambda: self.open_file(mode="imgDropdown"))
              File "C:\Users\18306\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\apps\lmuapps\lmuvegetationapps\Processor\Processor_Inversion_GUI.py", line 195, in open_file
              meta = self.get_image_meta(image=self.image, image_type="Input Image") # get metadata of image
              File "C:\Users\18306\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\apps\lmuapps\lmuvegetationapps\Processor\Processor_Inversion_GUI.py", line 525, in get_image_meta
              nrows = int(metadict['ENVI']['lines'])
             KeyError: 'lines'

**Comment by xiaokaichen1111** [comment]
<img width="858" alt="image" src="https://github.com/EnMAP-Box/enmap-box/assets/84078930/19d4027d-bcf4-4104-a892-5600a5cff0fa">

**Comment by janzandr** [comment]
As far as I know, the tool only supports ENVI BSQ raster. Save your raster as ENVI BSQ and try again.

**Comment by janzandr** [comment]
BTW: @Maesiu is the developer of this tool.

**Comment by xiaokaichen1111** [comment]
Thanks o lot.
