### ISSUE TITLE
EnMap installation - trouble with Python library

### ISSUE THREAD

**Issue by Sodalith11** [EnMAP-Box/enmap-box#690]
Hi guys,
I want to use the EnMap Box 3 Plugin in QGIS. After installing the plugin (and the required Google Earth Earthworks plugin) I end up with this error message:

```
 WARNING    Traceback (most recent call last):
              File "C:\Users/[USER]/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\gui\enmapboxgui.py", line 811, in showPackageInstaller
              w.addPackages(requiredPackages())
              File "C:\Users/[USER]/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\dependencycheck.py", line 1026, in addPackages
              self.loadPIPVersionInfo(packages)
              File "C:\Users/[USER]/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\dependencycheck.py", line 957, in loadPIPVersionInfo
              self.startTask(task)
              File "C:\Users/[USER]/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\dependencycheck.py", line 972, in startTask
              qgsTask.run()
              File "C:\Users/[USER]/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\dependencycheck.py", line 275, in run
              process = subprocess.run(cmdList,
              File "C:\PROGRA~1\QGIS33~2.3\apps\Python39\lib\subprocess.py", line 528, in run
              raise CalledProcessError(retcode, process.args,
             subprocess.CalledProcessError: Command 'C:\Program Files\QGIS 3.32.3\bin\qgis-bin.exe -m pip list' returned non-zero exit status 1.
```

I have already tried, same issue with older/newer QGIS versions. 
As I don't have Admin rights in the PC, I had the Admin try the same, no other outcome. Is some Python library missing? Might have to do with firewall setup? 

Thanks for any help!

**Comment by janzandr** [comment]
The problem seams to be related to the EnMAP-Box PIP Package Installer, which is currently broken.

**Comment by Sodalith11** [comment]
Thanks for the reply. I managed to solve the issue:

When installing the Plugin:
- Do not tick the Earth Engine Works Box (I don't need it anyway, atm)

After the plugin installed:
- Open the Geo4W Shell
- Enter the line (as described in the EnMAP Box installation guidelines (for Windows)):
`python3 -m pip install -r https://raw.githubusercontent.com/EnMAP-Box/enmap-box/main/requirements.txt `

- Run EnMAP Box in QGIS

That worked for me.
