### ISSUE TITLE
Error loading 'Classification Workflow (Advanced)

### ISSUE THREAD

**Issue by Neelumgithub** [EnMAP-Box/enmap-box#694]
An error has occurred while executing Python code: 

PyQt5.uic.exceptions.NoSuchClassError: Unknown C++ class:                                                                                     QgsFileWidget 
Traceback (most recent call last):
  File "C:\Users\DBA\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\coreapps\classificationworkflowapp\__init__.py", line 32, in startGUI
    w = ClassificationWorkflowGui(parent=self.enmapbox.ui)
  File "C:\Users\DBA\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\coreapps\classificationworkflowapp\classificationworkflowgui.py", line 249, in __init__
    loadUi(join(dirname(__file__), 'main.ui'), self)
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\__init__.py", line 238, in loadUi
    return DynamicUILoader(package).loadUi(uifile, baseinstance, resource_suffix)
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\Loader\loader.py", line 66, in loadUi
    return self.parse(filename, resource_suffix)
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 1037, in parse
    actor(elem)
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 828, in createUserInterface
    self.traverseWidgetTree(elem)
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 273, in createWidget
    self.traverseWidgetTree(elem)
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 503, in createLayout
    self.traverseWidgetTree(elem)
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 546, in handleItem
    self.traverseWidgetTree(elem)
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 273, in createWidget
    self.traverseWidgetTree(elem)
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 273, in createWidget
    self.traverseWidgetTree(elem)
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 503, in createLayout
    self.traverseWidgetTree(elem)
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 546, in handleItem
    self.traverseWidgetTree(elem)
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 273, in createWidget
    self.traverseWidgetTree(elem)
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 273, in createWidget
    self.traverseWidgetTree(elem)
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 503, in createLayout
    self.traverseWidgetTree(elem)
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 546, in handleItem
    self.traverseWidgetTree(elem)
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 273, in createWidget
    self.traverseWidgetTree(elem)
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 503, in createLayout
    self.traverseWidgetTree(elem)
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 546, in handleItem
    self.traverseWidgetTree(elem)
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 503, in createLayout
    self.traverseWidgetTree(elem)
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 546, in handleItem
    self.traverseWidgetTree(elem)
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 264, in createWidget
    self.stack.push(self.setupObject(widget_class, parent, elem))
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 230, in setupObject
    self.wprops.setProperties(obj, branch)
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\properties.py", line 415, in setProperties
    prop_value = self.convert(prop, widget)
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\properties.py", line 378, in convert
    return func(prop[0], **args)
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\properties.py", line 129, in _enum
    return self._pyEnumMember(prop.text)
  File "C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\PyQt5\uic\properties.py", line 115, in _pyEnumMember
    raise NoSuchClassError(prefix)
PyQt5.uic.exceptions.NoSuchClassError: Unknown C++ class: 
                                                                                    QgsFileWidget

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.32.3-Lima Lima, 67d46100b5 

Python Path:
C:\Users\DBA\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\apps\ensomap
C:/PROGRA~1/QGIS33~1.3/apps/qgis/./python
C:/Users/DBA/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/DBA/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS33~1.3/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS33~1.3\apps\grass\grass83\etc\python
C:\Users\DBA\Documents
C:\Program Files\QGIS 3.32.3\bin\python39.zip
C:\PROGRA~1\QGIS33~1.3\apps\Python39\DLLs
C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib
C:\Program Files\QGIS 3.32.3\bin
C:\PROGRA~1\QGIS33~1.3\apps\Python39
C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\Pythonwin
C:/Users/DBA/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\DBA\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows
C:\Users/DBA/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\site-packages
C:\Users/DBA/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin
C:\Users\DBA\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\qgispluginsupport\qps\pyqtgraph
C:\Users\DBA\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\site-packages
C:\Users\DBA\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\apps
C:\Users\DBA\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\coreapps
C:\Users\DBA\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\eo4qapps
.

**Comment by janzandr** [comment]
I can reproduce the problem under QGIS v3.28 LTR.

**Comment by LarpUnina** [comment]
I have the same Python error. Is there a way to fix it?

```
An error has occurred while executing Python code: 

PyQt5.uic.exceptions.NoSuchClassError: Unknown C++ class:                                                                                     QgsFileWidget 
Traceback (most recent call last):
  File "C:\Users\Gabriele\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\coreapps\classificationworkflowapp\__init__.py", line 32, in startGUI
    w = ClassificationWorkflowGui(parent=self.enmapbox.ui)
  File "C:\Users\Gabriele\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\coreapps\classificationworkflowapp\classificationworkflowgui.py", line 249, in __init__
    loadUi(join(dirname(__file__), 'main.ui'), self)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\__init__.py", line 238, in loadUi
    return DynamicUILoader(package).loadUi(uifile, baseinstance, resource_suffix)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\Loader\loader.py", line 66, in loadUi
    return self.parse(filename, resource_suffix)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 1037, in parse
    actor(elem)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 828, in createUserInterface
    self.traverseWidgetTree(elem)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 273, in createWidget
    self.traverseWidgetTree(elem)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 503, in createLayout
    self.traverseWidgetTree(elem)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 546, in handleItem
    self.traverseWidgetTree(elem)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 273, in createWidget
    self.traverseWidgetTree(elem)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 273, in createWidget
    self.traverseWidgetTree(elem)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 503, in createLayout
    self.traverseWidgetTree(elem)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 546, in handleItem
    self.traverseWidgetTree(elem)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 273, in createWidget
    self.traverseWidgetTree(elem)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 273, in createWidget
    self.traverseWidgetTree(elem)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 503, in createLayout
    self.traverseWidgetTree(elem)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 546, in handleItem
    self.traverseWidgetTree(elem)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 273, in createWidget
    self.traverseWidgetTree(elem)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 503, in createLayout
    self.traverseWidgetTree(elem)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 546, in handleItem
    self.traverseWidgetTree(elem)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 503, in createLayout
    self.traverseWidgetTree(elem)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 546, in handleItem
    self.traverseWidgetTree(elem)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 264, in createWidget
    self.stack.push(self.setupObject(widget_class, parent, elem))
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 230, in setupObject
    self.wprops.setProperties(obj, branch)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\properties.py", line 415, in setProperties
    prop_value = self.convert(prop, widget)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\properties.py", line 378, in convert
    return func(prop[0], **args)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\properties.py", line 129, in _enum
    return self._pyEnumMember(prop.text)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\properties.py", line 115, in _pyEnumMember
    raise NoSuchClassError(prefix)
PyQt5.uic.exceptions.NoSuchClassError: Unknown C++ class: 
                                                                                    QgsFileWidget


Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.28.13-Firenze Firenze, 3b4db4f561 

Python Path:
C:\Users\Gabriele\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\apps\ensomap
C:\Users/Gabriele/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ZonalStatisticsMultiband
C:/OSGeo4W/apps/qgis-ltr/./python
C:/Users/Gabriele/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Gabriele/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGeo4W/apps/qgis-ltr/./python/plugins
C:\OSGeo4W\apps\grass\grass83\etc\python
C:\Users\Gabriele\Documents
C:\OSGeo4W\bin\python39.zip
C:\OSGeo4W\apps\Python39\DLLs
C:\OSGeo4W\apps\Python39\lib
C:\OSGeo4W\bin
C:\Users\Gabriele\AppData\Roaming\Python\Python39\site-packages
C:\OSGeo4W\apps\Python39
C:\OSGeo4W\apps\Python39\lib\site-packages
C:\OSGeo4W\apps\Python39\lib\site-packages\win32
C:\OSGeo4W\apps\Python39\lib\site-packages\win32\lib
C:\OSGeo4W\apps\Python39\lib\site-packages\Pythonwin
C:/Users/Gabriele/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users/Gabriele/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\site-packages
C:\Users/Gabriele/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin
C:\Users\Gabriele\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\site-packages
C:\Users\Gabriele\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\apps
C:\Users\Gabriele\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\coreapps
C:\Users\Gabriele\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\eo4qapps
.
```

**Comment by janzandr** [comment]
I didn't took the time to look into it. I'll do this soon.

**Comment by AdamWasniewski** [comment]
Hello, how did you resolve this problem? I have the same problem

**Comment by janzandr** [comment]
I will release a DEV version with the fix tomorrow.

**Comment by AdamWasniewski** [comment]
Thank you. I will check if this will work for me

**Comment by LarpUnina** [comment]
@janzandr We have tested it and it works now.  Thank you very much for your help!
