### ISSUE TITLE
Error in executing EnPT - EnMAP Processing Tool (v0.7.6) for Level-1B to Level-2A conversion

### ISSUE THREAD

**Issue by unanduwa** [EnMAP-Box/enmap-box#719]
Error in executing EnPT - EnMAP Processing Tool (v0.7.6) for Level-1B to Level-2A conversion

```
QGIS version: 3.28.12-Firenze
QGIS code revision: dcc633b2de
Qt version: 5.15.3
Python version: 3.9.5
GDAL version: 3.7.2
GEOS version: 3.12.0-CAPI-1.18.0
PROJ version: Rel. 9.3.0, September 1st, 2023
PDAL version: 2.5.5 (git-version: 24f78d)
Algorithm started at: 2023-11-12T12:27:40
Algorithm 'EnPT - EnMAP Processing Tool (v0.7.6)' starting…
Input parameters:
{ 'CPUs' : 4, 'auto_download_ecmwf' : False, 'average_elevation' : 0, 'blocksize' : 100, 'conda_root' : 'C:\\ProgramData\\Anaconda3', 'deadpix_P_algorithm' : 1, 'deadpix_P_interp_spatial' : 0, 'deadpix_P_interp_spectral' : 0, 'disable_progress_bars' : True, 'drop_bad_bands' : True, 'enable_ac' : True, 'json_config' : '', 'mode_ac' : 2, 'n_lines_to_append' : None, 'ortho_resampAlg' : 2, 'output_dir' : 'C:\\Users\\D E L L\\Documents\\EnPT\\Output\\20231112__1', 'output_format' : 0, 'output_interleave' : 2, 'path_dem' : None, 'path_earthSunDist' : '', 'path_l1b_enmap_image' : 'D:\\FYP\\EnMap data\\dims_op_oc_oc-en_701023889_1\\ENMAP.HSI.L1B\\ENMAP-HSI-L1BDT0000040015_13-2023-09-05T05_44_01.422_ravindur-cat1distributor_701023887_722615514_2023-11-11T18_00_33.472\\ENMAP01-____L1B-DT0000040015_20230905T054401Z_013_V010400_20231111T151725Z.ZIP', 'path_l1b_enmap_image_gapfill' : '', 'path_reference_image' : None, 'path_solar_irr' : '', 'polymer_additional_results' : True, 'polymer_root' : '', 'run_deadpix_P' : False, 'scale_factor_boa_ref' : 10000, 'scale_factor_toa_ref' : 10000, 'target_epsg' : None, 'target_projection_type' : 0, 'threads' : -1, 'vswir_overlap_algorithm' : 3, 'working_dir' : '' }

Found Conda installation at C:\ProgramData\Anaconda3.
The Conda installation contains the 'enpt' environment as expected.

Calling EnPT with the following command:
enpt --CPUs 4 --auto_download_ecmwf False --average_elevation 0 --blocksize 100 --deadpix_P_algorithm spatial --deadpix_P_interp_spatial linear --deadpix_P_interp_spectral linear --disable_progress_bars True --drop_bad_bands True --enable_ac True --mode_ac combined --ortho_resampAlg gauss --output_dir C:\Users\D E L L\Documents\EnPT\Output\20231112__1 --output_format GTiff --output_interleave pixel --path_l1b_enmap_image D:\FYP\EnMap data\dims_op_oc_oc-en_701023889_1\ENMAP.HSI.L1B\ENMAP-HSI-L1BDT0000040015_13-2023-09-05T05_44_01.422_ravindur-cat1distributor_701023887_722615514_2023-11-11T18_00_33.472\ENMAP01-____L1B-DT0000040015_20230905T054401Z_013_V010400_20231111T151725Z.ZIP --polymer_additional_results True --run_deadpix_P False --scale_factor_boa_ref 10000 --scale_factor_toa_ref 10000 --target_projection_type UTM --threads -1 --vswir_overlap_algorithm swir_only


Traceback (most recent call last):
File "C:\Users\D E L L\AppData\Roaming\Python\Python39\site-packages\enpt_enmapboxapp\enpt_external_algorithm.py", line 110, in _locate_enpt_run_script
return check_output('where enpt_run_cmd.bat', shell=True).decode('UTF-8').strip()
File "C:\PROGRA~1\QGIS32~1.12\apps\Python39\lib\subprocess.py", line 424, in check_output
return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
File "C:\PROGRA~1\QGIS32~1.12\apps\Python39\lib\subprocess.py", line 528, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'where enpt_run_cmd.bat' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\D E L L\AppData\Roaming\Python\Python39\site-packages\enpt_enmapboxapp\enpt_external_algorithm.py", line 184, in processAlgorithm
path_enpt_runscript = self._locate_enpt_run_script()
File "C:\Users\D E L L\AppData\Roaming\Python\Python39\site-packages\enpt_enmapboxapp\enpt_external_algorithm.py", line 118, in _locate_enpt_run_script
raise EnvironmentError('The EnPT run script could not be found. Please make sure, that enpt_enmapboxapp '
OSError: The EnPT run script could not be found. Please make sure, that enpt_enmapboxapp is correctly installed into your QGIS Python environment.

Execution failed after 0.21 seconds

Loading resulting layers
Algorithm 'EnPT - EnMAP Processing Tool (v0.7.6)' finished
```

**Comment by janzandr** [comment]
Hi @danschef, can you please take care of this issue/question.

**Comment by danschef** [comment]
@https://github.com/unanduwa Please provide some more information how installed QGIS, the EnMAP-Box, and EnPT. Did you follow the [installation instructions for EnPT](https://enmap.git-pages.gfz-potsdam.de/GFZ_Tools_EnMAP_BOX/EnPT/doc/installation.html)?

**Comment by unanduwa** [comment]
Yes, those instructions were followed.

- QGIS version  3.28.12-Firenze (because the latest version didn't function properly with EnMap-Box)
- EnMap-Box 3 Version 3.13.1
- EnPT - EnMAP Processing Tool (v0.7.6)

**Comment by danschef** [comment]
Ok, I had a look into this. Something seems to be wrong with the installation of the EnPT run script. However, I don´t have the time to work on this in the next too weeks. You could as a workaround just install EnPT via conda into the same environment like QGIS as documented [here](https://enmap.git-pages.gfz-potsdam.de/GFZ_Tools_EnMAP_BOX/EnPT/doc/installation.html#installing-enpt-along-with-qgis-and-the-enmap-box-backend-gui).

I will post updates and fixes of this issue [here](https://git.gfz-potsdam.de/EnMAP/GFZ_Tools_EnMAP_BOX/enpt_enmapboxapp/-/issues/30).

**Comment by janzandr** [comment]
Thanks @danschef.
