### ISSUE TITLE
[Map View] Setting QGIS Map center/extent does not work

### ISSUE THREAD

**Issue by thielfab** [EnMAP-Box/enmap-box#738]
* Open Map View, go into context menu
* Select one of QGIS, e.g. `QGIS --> Set map center`
* Error

```
Traceback (most recent call last):
  File "C:\Users/fabian/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\gui\contextmenuprovider.py", line 70, in 
    self.spatialExtent().toCrs(qgisApp.mapCanvas().mapSettings().destinationCrs())))
AttributeError: 'EnMAPBoxContextMenuProvider' object has no attribute 'spatialExtent'
```
```
2023-12-05T15:59:46     WARNING    Traceback (most recent call last):
              File "C:\Users/fabian/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\gui\contextmenuprovider.py", line 59, in 
              self.spatialCenter().toCrs(qgisApp.mapCanvas().mapSettings().destinationCrs())))
             AttributeError: 'EnMAPBoxContextMenuProvider' object has no attribute 'spatialCenter'
```

EnMAP-Box 3.13.2
QGIS 3.34.1

**Comment by janzandr** [comment]
I can also confirm this for QGIS 3.28.
