### ISSUE TITLE
Enmap (Python error)

### ISSUE THREAD

**Issue by mohammed-arkan** [EnMAP-Box/enmap-box#760]
I got this error
"
An error has occurred while executing Python code: 

subprocess.CalledProcessError: Command 'C:\Program Files\QGIS 3.34.1\apps\Python39\python3.exe -m pip list' returned non-zero exit status 1. 
Traceback (most recent call last):
  File "C:\Users/msi pc/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\gui\enmapboxgui.py", line 807, in showPackageInstaller
    w.addPackages(requiredPackages())
  File "C:\Users/msi pc/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\dependencycheck.py", line 1043, in addPackages
    self.loadPIPVersionInfo(packages)
  File "C:\Users/msi pc/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\dependencycheck.py", line 974, in loadPIPVersionInfo
    self.startTask(task)
  File "C:\Users/msi pc/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\dependencycheck.py", line 989, in startTask
    qgsTask.run()
  File "C:\Users/msi pc/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapbox\dependencycheck.py", line 292, in run
    process = subprocess.run(cmdList,
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'C:\Program Files\QGIS 3.34.1\apps\Python39\python3.exe -m pip list' returned non-zero exit status 1.

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.34.1-Prizren Prizren, 133927424d 

Python Path:
C:\Users\msi pc\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\apps\ensomap
C:/PROGRA~1/QGIS33~1.1/apps/qgis/./python
C:/Users/msi pc/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/msi pc/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS33~1.1/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS33~1.1\apps\grass\grass83\etc\python
C:\Users\msi pc\Documents
C:\Program Files\QGIS 3.34.1\bin\python39.zip
C:\PROGRA~1\QGIS33~1.1\apps\Python39\DLLs
C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib
C:\Program Files\QGIS 3.34.1\bin
C:\Users\msi pc\AppData\Roaming\Python\Python39\site-packages
C:\PROGRA~1\QGIS33~1.1\apps\Python39
C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\Pythonwin
C:/Users/msi pc/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users/msi pc/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\site-packages
C:\Users/msi pc/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin
C:\Users\msi pc\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\qgispluginsupport\qps\pyqtgraph
C:\Users\msi pc\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\site-packages
C:\Users\msi pc\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\apps
C:\Users\msi pc\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\coreapps
C:\Users\msi pc\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\eo4qapps
.

"

**Comment by janzandr** [comment]
Please explain the steps to reproduce the error.

**Comment by janzandr** [comment]
@jakimowb just got an email from Akpona reporting the exact same issue.
The error is related to the PIP installer, when installing missing packages.
QGIS 3.34.1 and current stable EnMAP-Box.

**Comment by mohammed-arkan** [comment]
> Please explain the steps to reproduce the error.

When I try to open classification workflow (advanced) I get an error message:
Python error: An error has occurred while executing Python code: See message log (Python Error) for more details.
"

When you open the entire message, it is as follows:
"
An error has occurred while executing Python code: 

PyQt5.uic.exceptions.NoSuchClassError: Unknown C++ class:                                                                                     QgsFileWidget 
Traceback (most recent call last):
  File "C:\Users\msi pc\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\coreapps\classificationworkflowapp\__init__.py", line 32, in startGUI
    w = ClassificationWorkflowGui(parent=self.enmapbox.ui)
  File "C:\Users\msi pc\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\coreapps\classificationworkflowapp\classificationworkflowgui.py", line 249, in __init__
    loadUi(join(dirname(__file__), 'main.ui'), self)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\PyQt5\uic\__init__.py", line 238, in loadUi
    return DynamicUILoader(package).loadUi(uifile, baseinstance, resource_suffix)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\PyQt5\uic\Loader\loader.py", line 66, in loadUi
    return self.parse(filename, resource_suffix)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 1037, in parse
    actor(elem)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 828, in createUserInterface
    self.traverseWidgetTree(elem)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 273, in createWidget
    self.traverseWidgetTree(elem)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 503, in createLayout
    self.traverseWidgetTree(elem)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 546, in handleItem
    self.traverseWidgetTree(elem)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 273, in createWidget
    self.traverseWidgetTree(elem)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 273, in createWidget
    self.traverseWidgetTree(elem)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 503, in createLayout
    self.traverseWidgetTree(elem)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 546, in handleItem
    self.traverseWidgetTree(elem)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 273, in createWidget
    self.traverseWidgetTree(elem)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 273, in createWidget
    self.traverseWidgetTree(elem)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 503, in createLayout
    self.traverseWidgetTree(elem)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 546, in handleItem
    self.traverseWidgetTree(elem)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 273, in createWidget
    self.traverseWidgetTree(elem)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 503, in createLayout
    self.traverseWidgetTree(elem)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 546, in handleItem
    self.traverseWidgetTree(elem)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 503, in createLayout
    self.traverseWidgetTree(elem)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 546, in handleItem
    self.traverseWidgetTree(elem)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 264, in createWidget
    self.stack.push(self.setupObject(widget_class, parent, elem))
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\PyQt5\uic\uiparser.py", line 230, in setupObject
    self.wprops.setProperties(obj, branch)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\PyQt5\uic\properties.py", line 415, in setProperties
    prop_value = self.convert(prop, widget)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\PyQt5\uic\properties.py", line 378, in convert
    return func(prop[0], **args)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\PyQt5\uic\properties.py", line 129, in _enum
    return self._pyEnumMember(prop.text)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\PyQt5\uic\properties.py", line 115, in _pyEnumMember
    raise NoSuchClassError(prefix)
PyQt5.uic.exceptions.NoSuchClassError: Unknown C++ class: 
                                                                                    QgsFileWidget


Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.34.1-Prizren Prizren, 133927424d 

Python Path:
C:\Users\msi pc\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\apps\ensomap
C:/PROGRA~1/QGIS33~1.1/apps/qgis/./python
C:/Users/msi pc/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/msi pc/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS33~1.1/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS33~1.1\apps\grass\grass83\etc\python
C:\Users\msi pc\Documents
C:\Program Files\QGIS 3.34.1\bin\python39.zip
C:\PROGRA~1\QGIS33~1.1\apps\Python39\DLLs
C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib
C:\Program Files\QGIS 3.34.1\bin
C:\Users\msi pc\AppData\Roaming\Python\Python39\site-packages
C:\PROGRA~1\QGIS33~1.1\apps\Python39
C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\site-packages\Pythonwin
C:/Users/msi pc/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users/msi pc/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\site-packages
C:\Users/msi pc/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin
C:\Users\msi pc\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\qgispluginsupport\qps\pyqtgraph
C:\Users\msi pc\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\site-packages
C:\Users\msi pc\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\apps
C:\Users\msi pc\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\coreapps
C:\Users\msi pc\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\enmapboxplugin\enmapbox\eo4qapps
.
"

**Comment by janzandr** [comment]
@mohammed-arkan your second error message is a different issue, which is already fixed, see https://github.com/EnMAP-Box/enmap-box/issues/694
