### ISSUE TITLE
[Spectral Processing] Raster math algo not working within Spectral Processing

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#764]
How to reproduce with any library:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/d9b13735-9754-42f7-9fd1-82cec4a6981e)

```
Save parameters for enmapbox:RasterMath
Calculate feature intersection
Process 2 features
Make virtual raster(s) permanent
Write D:/QGIS/bin/qgis-ltr-bin/processing_pWMWoy/6a1b62ecd1a74219b5ecadbd1deabaa6/R1.tif
Execute algorithm: enmapbox:RasterMath ...
Traceback (most recent call last):
File "C:\Users\Andreas\AppData\Roaming\Python\Python39\site-packages\typeguard\__init__.py", line 1033, in wrapper
retval = func(*args, **kwargs)
File "D:\source\QGISPlugIns\enmap-box\enmapboxprocessing\algorithm\rastermathalgorithm\rastermathalgorithm.py", line 150, in prepareAlgorithm
self.mapLayers = {k: v for k, v in QgsProject.instance().mapLayers().items() if k in parameters[self.P_CODE]}
File "D:\source\QGISPlugIns\enmap-box\enmapboxprocessing\algorithm\rastermathalgorithm\rastermathalgorithm.py", line 150, in <dictcomp>
self.mapLayers = {k: v for k, v in QgsProject.instance().mapLayers().items() if k in parameters[self.P_CODE]}
KeyError: 'code'


```

**Comment by janzandr** [comment]
@jakimowb I did a print out for the parameters argument and it seems that the "code" parameter is missing.

```
parameters = {
'R1': 'D:/QGIS/bin/qgis-ltr-bin/processing_ecyxLA/9c87765586e940b3a6814344caf45f44/R1.tif', 'R10': None, 'R2': None, 'R3': None, 'R4': None, 'R5': None, 'R6': None, 'R7': None, 'R8': None, 'R9': None, 'RS': None, 
'V1': None, 'V10': None, 'V2': None, 'V3': None, 'V4': None, 'V5': None, 'V6': None, 'V7': None, 'V8': None, 'V9': None,
'floatInput': True, 'grid': None, 'monolithic': False, 'noDataValue': None, 
'outputRaster': 'D:/QGIS/bin/qgis-ltr-bin/processing_ecyxLA/9c87765586e940b3a6814344caf45f44/TEMPORARY_OUTPUT_test4.tif', 'overlap': None
}
```

I guess that you manipulate the original parameters dict inside the Spectral Processing. 
Somehow the "code" parameter gets lost.
Can you please check this on your side?

**Comment by jakimowb** [comment]
A previous problem is that the raster math widget does not display the raster files that are generated from the SpectralLibrary fields at all (see https://enmap-box.readthedocs.io/en/latest/usr_section/usr_manual/gui.html#spectral-processing)
![grafik](https://github.com/EnMAP-Box/enmap-box/assets/1404870/2531874e-dc2f-4291-8d05-f87d68928b54)

In the following screenshould we would expect in "Available data sources" "name" and a "profiles" raster, as both are available as columns in the spectral library vector layer.

![grafik](https://github.com/EnMAP-Box/enmap-box/assets/1404870/95739849-89af-431c-a78e-e4672ecb59a0)

**Comment by jakimowb** [comment]
@janzandr the `ProcessingParameterRasterMathCodeEditWidgetWrapper` needs to consider the [QgsProcessingContext](https://api.qgis.org/api/classQgsProcessingContext.html) it is called in. This context contains the layers yielded after converting profiles and profile attributes into raster layer.

This can be done by implementing a `createWrappedWidget (QgsProcessingContext &context)`. 
The QgsProject yielded from `context.project()` contains the (temporary) raster layers that contain the profiles from the spectral library.

As an example you may look into `SpectralProcessingRasterLayerWidgetWrapper(QgsAbstractProcessingParameterWidgetWrapper)`, which creates this combo-box:
![grafik](https://github.com/EnMAP-Box/enmap-box/assets/1404870/b1963d6f-33af-4bb3-886a-7e4210606f95)

    ```
def createWidget(self):

        model = QgsMapLayerModel(self, self.widgetContext().project())
        self.mMapLayerModel = model

        param = self.parameterDefinition()
        is_optional = param.flags() & QgsProcessingParameterDefinition.FlagOptional
        if is_optional:
            model.setAllowEmptyLayer(True)

        mapLayerWidget = None
        if isinstance(param, QgsProcessingParameterRasterLayer):
            cb = QComboBox()
            cb.setModel(model)
            cb.currentIndexChanged.connect(lambda idx, m=model: self.onIndexChanged(idx, m))
            mapLayerWidget = cb
        else:
            raise NotImplementedError()

        self.mMapLayerWidget = mapLayerWidget
        return mapLayerWidget
```

**Comment by jakimowb** [comment]
relates to #796

**Comment by janzandr** [comment]
> @janzandr the ProcessingParameterRasterMathCodeEditWidgetWrapper needs to consider the [QgsProcessingContext](https://api.qgis.org/api/classQgsProcessingContext.html) it is called in. This context contains the layers yielded after converting profiles and profile attributes into raster layer.

Sounds good.

**Comment by jakimowb** [comment]
@janzandr this issue now waits for the fixes in ProcessingParameterRasterMathCodeEditWidgetWrapper,
see https://github.com/EnMAP-Box/enmap-box/issues/764#issuecomment-1905665072

**Comment by janzandr** [comment]
> The QgsProject yielded from context.project() contains the (temporary) raster layers that contain the profiles from the spectral library.

@jakimowb that isn't working. The returned project is None:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/7f9e7203-b0ae-49b4-9b6e-c6b7e98940a6)

**Comment by jakimowb** [comment]
Your `createWidget()` is already called at object construction. Therefore the widget will never be able to consider a processing context that is set afterwards when [QgsAbstractProcessingParameterWidgetWrapper::setWidgetContext](https://api.qgis.org/api/classQgsAbstractProcessingParameterWidgetWrapper.html#af24dddfc4a821c0e00a1c9e3a330942d) is called.

You need to define a `def createWrappedWidget(self, context: QgsProcessingContext) -> QWidget:` that calls `createWidget()`.
Please have a look into `SpectralProcessingRasterLayerWidgetWrapper`.

**Comment by jakimowb** [comment]
@janzandr another blocking problem is the limitation of the ProcessingParameterRasterMathCodeEdit to use ogr/gdal sources only.
It simply cannot handle QgsVectorLayer / QgsRasterLayers from other data providers, but this is necessary to read data from the VectorLayerFieldRasterDataProvider which maps vector field attributes into an in-memory raster image.

```
if layer.dataProvider().name() not in ['gdal', 'ogr']:
    continue
```
