### ISSUE TITLE
error from decorrelationstretchdialog.py : MinMaxScaler must be an instance of 'tuple'. Got [0, 255] instead

### ISSUE THREAD

**Issue by roydenyates** [EnMAP-Box/enmap-box#771]
Latest QGIS and enmapbox.

Open decorrelationstretch renderer and select a loaded raster, error will follow:

```
2023-12-30T23:14:42     WARNING    Traceback (most recent call last):
              File "/some/path/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/coreapps/decorrelationstretchapp/decorrelationstretchdialog.py", line 182, in onLiveUpdate
              self.onApplyClicked()
              File "/some/path/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/coreapps/decorrelationstretchapp/decorrelationstretchdialog.py", line 174, in onApplyClicked
              renderer = self.currentRenderer()
              ^^^^^^^^^^^^^^^^^^^^^^
              File "/some/path/.py_virtualenvs/enmapbox/lib/python3.11/site-packages/typeguard/__init__.py", line 1033, in wrapper
              retval = func(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^
              File "/some/path/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapbox/coreapps/decorrelationstretchapp/decorrelationstretchdialog.py", line 126, in currentRenderer
              scaler2.fit(percentiles)
              File "/some/path/.py_virtualenvs/enmapbox/lib/python3.11/site-packages/sklearn/preprocessing/_data.py", line 435, in fit
              return self.partial_fit(X, y)
              ^^^^^^^^^^^^^^^^^^^^^^
              File "/some/path/.py_virtualenvs/enmapbox/lib/python3.11/site-packages/sklearn/base.py", line 1145, in wrapper
              estimator._validate_params()
              File "/some/path/.py_virtualenvs/enmapbox/lib/python3.11/site-packages/sklearn/base.py", line 638, in _validate_params
              validate_parameter_constraints(
              File "/some/path/.py_virtualenvs/enmapbox/lib/python3.11/site-packages/sklearn/utils/_param_validation.py", line 96, in validate_parameter_constraints
              raise InvalidParameterError(
             sklearn.utils._param_validation.InvalidParameterError: The 'feature_range' parameter of MinMaxScaler must be an instance of 'tuple'. Got [0, 255] instead.
```

Appears to be solved by changing decorrelationstretchdialog.py line 125, from

```scaler2 = MinMaxScaler(feature_range=[0, 255], clip=True)```

to

```scaler2 = MinMaxScaler(feature_range=(0, 255), clip=True)```

**Comment by janzandr** [comment]
Thanks @roydenyates. This seems to be an API change in sklearn.
