### ISSUE TITLE
CatBoostClassifier

### ISSUE THREAD

**Issue by dpoursanidis** [EnMAP-Box/enmap-box#790]
Hi,

In the classification workflow, some algorithms work and some not.

For example, the following dataset work in RF but not in CatBoost, XGBRFClassifier, XGBClassifier.

QGIS version: 3.28.3-Firenze
QGIS code revision: c12bcb2f76c
Qt version: 5.15.3
Python version: 3.9.5
GDAL version: 3.6.2
GEOS version: 3.11.1-CAPI-1.17.1
PROJ version: Rel. 9.1.1, December 1st, 2022
PDAL version: 2.4.3 (git-version: f8d673)
Algorithm started at: 2024-01-17T09:08:55
Algorithm 'Classification workflow' starting…
Input parameters:
{ 'classifier' : 'from catboost import CatBoostClassifier\nclassifier = CatBoostClassifier(n_estimators=100)', 'dataset' : 'C:/Users/homoaquaticus/AppData/Local/Temp/processing_oIuLBO/1c67a58b59b745a0ac216e7b9b183bfe/outputClassificationDataset.pkl', 'matchByName' : False, 'nfold' : 10, 'openReport' : True, 'outputClassification' : 'TEMPORARY_OUTPUT', 'outputClassifier' : 'TEMPORARY_OUTPUT', 'outputClassifierPerformance' : 'TEMPORARY_OUTPUT', 'outputProbability' : 'TEMPORARY_OUTPUT', 'raster' : 'C:/Users/homoaquaticus/Desktop/Seagrass_NYU/Stack_Clipped_maskBoats_RED.dat' }

Traceback (most recent call last):
File "C:\Users\homoaquaticus\AppData\Roaming\Python\Python39\site-packages\typeguard\__init__.py", line 1033, in wrapper
retval = func(*args, **kwargs)
File "C:\Users/homoaquaticus/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapboxprocessing\algorithm\fitclassifieralgorithmbase.py", line 98, in processAlgorithm
classifier.fit(dump.X, dump.y.ravel())
File "C:\Users\homoaquaticus\AppData\Roaming\Python\Python39\site-packages\catboost\core.py", line 4921, in fit
self._fit(X, y, cat_features, text_features, embedding_features, None, sample_weight, None, None, None, None, baseline, use_best_model,
File "C:\Users\homoaquaticus\AppData\Roaming\Python\Python39\site-packages\catboost\core.py", line 2190, in _fit
with log_fixup(log_cout, log_cerr), \
File "C:\PROGRA~1\QGIS32~3.3\apps\Python39\lib\contextlib.py", line 117, in __enter__
return next(self.gen)
File "C:\Users\homoaquaticus\AppData\Roaming\Python\Python39\site-packages\catboost\core.py", line 122, in log_fixup
_set_logger(_get_stream_like_object(log_cout), _get_stream_like_object(log_cerr))
File "C:\Users\homoaquaticus\AppData\Roaming\Python\Python39\site-packages\catboost\core.py", line 114, in _get_stream_like_object
raise CatBoostError(
_catboost.CatBoostError: Expected callable object or stream-like object

Execution failed after 0.15 seconds

Any idea on how this can be fixed?

**Comment by janzandr** [comment]
Algorithms only fail when started from within QGIS. Calling them from Python works fine. Problem is the standard out and standard error streams. I was able to monkey patch those. Fix is quit ugly, but seems to work.

**Comment by janzandr** [comment]
Also need to handle the regression case: CatBoostRegressor
