### ISSUE TITLE
error loading PRISMA L2D product in enMap Box

### ISSUE THREAD

**Issue by gthlor** [EnMAP-Box/enmap-box#793]
Hello, 

I get the following error when i try to import prisma L2d products in enmap box:

Traceback (most recent call last):
File "C:\OSGeo4W\apps\Python39\lib\site-packages\typeguard\__init__.py", line 1033, in wrapper
retval = func(*args, **kwargs)
File "C:\Users/loren/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapboxprocessing\algorithm\importprismal2dalgorithm.py", line 165, in processAlgorithm
badBandMultipliers = self.writeSpectralErrorMatrix(
File "C:\OSGeo4W\apps\Python39\lib\site-packages\typeguard\__init__.py", line 1033, in wrapper
retval = func(*args, **kwargs)
File "C:\Users/loren/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapboxprocessing\algorithm\importprismal2dalgorithm.py", line 279, in writeSpectralErrorMatrix
dsVnir = self.openDataset(he5Filename, key)
File "C:\OSGeo4W\apps\Python39\lib\site-packages\typeguard\__init__.py", line 1033, in wrapper
retval = func(*args, **kwargs)
File "C:\Users/loren/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapboxprocessing\algorithm\importprismal2dalgorithm.py", line 127, in openDataset
ds: gdal.Dataset = gdal.Open(source)
File "C:\OSGeo4W\apps\Python39\lib\site-packages\osgeo\gdal.py", line 6033, in Open
return _gdal.Open(*args)
RuntimeError: `HDF5:"""C:/Users/loren/Desktop/PRISMA/01_BOSTRICO/archivio/TRENTO/PRS_L2D_STD_20210226102715_20210226102719_0001.he5"""://HDFEOS/SWATHS/PRS_L2D_HCO/Data_Fields/VNIR_PIXEL_L2_ERR_MATRIX' does not exist in the file system, and is not recognized as a supported dataset name.

Execution failed after 0.05 seconds

Loading resulting layers
Algorithm 'Import PRISMA L2D product' finished

do you know how can i solve it?

**Comment by jakimowb** [comment]
Thanks for the report @gthlor . Can you share the files with @janzandr that he can investigate in this?

**Comment by gthlor** [comment]
[https://1drv.ms/u/s!AlW3HeKkC3kSgdhGb8sQzaBXYCOX5w?e=4kgwl6](url)

Here is the link to download the file from my Onedrive account. Do you know/prefer other ways to share content?

Thank you.

**Comment by janzandr** [comment]
Hi @gthlor, 
the problem sounds familiar. I guess there is a problem with the HDF5 library. Please have a look here:
https://github.com/EnMAP-Box/enmap-box/issues/301

Have you followed step 4 in the installation guide?
https://enmap-box.readthedocs.io/en/latest/usr_section/usr_installation.html#install-python-dependencies

**Comment by gthlor** [comment]
Hi @janzandr 
thank you for the tip!!!

I actually managed to import the PRISMA image by running the following commands:
1) C:\OSGeo4W>pip install --upgrade --user -r https://raw.githubusercontent.com/EnMAP-Box/enmap-box/main/.env/osgeo4w/requirements_osgeo4w.txt
2) setup and install hdf5
![image](https://github.com/EnMAP-Box/enmap-box/assets/105752636/7784eee8-ac61-4500-a046-1161339c6b48)

However, do you know what could be the reason for failing reading data with h5py API? (see image below)

![image](https://github.com/EnMAP-Box/enmap-box/assets/105752636/b7fe4156-1dcf-4033-b634-82c98bd8650c)

Thank you again for your support!

**Comment by janzandr** [comment]
> However, do you know what could be the reason for failing reading data with h5py API? (see image below)

In the OSGeo4W installer, you have to search and install **h5py** (not hdf).

![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/914d5b3a-5b0c-496e-8ed3-e34cc8fda84c)

**Comment by gthlor** [comment]
Thank you. I solved all the issues and I have nothing else to ask.

Thank you again!
