### ISSUE TITLE
QGIS v.3-36 problem when enabling EnMap-Box

### ISSUE THREAD

**Issue by grantboxer** [EnMAP-Box/enmap-box#818]
I have installed QGIS v3.36 and now when I try to enable EnMap-Box, I get the following error.
Any suggestions?

An error has occurred while executing Python code: 

TypeError: QgsProcessingParameterDefinition.setFlags(): argument 1 has unexpected type 'int' 
Traceback (most recent call last):
  File "C:\Users\boxer\AppData\Roaming\Python\Python39\site-packages\typeguard\__init__.py", line 1033, in wrapper
    retval = func(*args, **kwargs)
  File "C:\Users/boxer/AppData/Roaming/QGIS/QGIS3\profiles\Grant1/python/plugins\enmapboxplugin\enmapboxprocessing\algorithm\build3dcubealgorithm.py", line 49, in initAlgorithm
    self.addParameterFloat(self.P_SPECTRAL_SCALE, self._SPECTRAL_SCALE, 1, True, 0, None, True)
  File "C:\Users\boxer\AppData\Roaming\Python\Python39\site-packages\typeguard\__init__.py", line 1033, in wrapper
    retval = func(*args, **kwargs)
  File "C:\Users/boxer/AppData/Roaming/QGIS/QGIS3\profiles\Grant1/python/plugins\enmapboxplugin\enmapboxprocessing\enmapalgorithm.py", line 892, in addParameterFloat
    self.flagParameterAsAdvanced(name, advanced)
  File "C:\Users\boxer\AppData\Roaming\Python\Python39\site-packages\typeguard\__init__.py", line 1033, in wrapper
    retval = func(*args, **kwargs)
  File "C:\Users/boxer/AppData/Roaming/QGIS/QGIS3\profiles\Grant1/python/plugins\enmapboxplugin\enmapboxprocessing\enmapalgorithm.py", line 981, in flagParameterAsAdvanced
    p.setFlags(int(p.flags()) | QgsProcessingParameterDefinition.Flag.FlagAdvanced)
TypeError: QgsProcessingParameterDefinition.setFlags(): argument 1 has unexpected type 'int'

Python version: 3.9.18 (heads/master:5eba59e, Feb  1 2024, 20:02:10) [MSC v.1929 64 bit (AMD64)] 
QGIS version: 3.36.0-Maidenhead Maidenhead, 09951dc0 

Python Path:
C:/OSGeo4W/apps/qgis/./python
C:/Users/boxer/AppData/Roaming/QGIS/QGIS3\profiles\Grant1/python
C:/Users/boxer/AppData/Roaming/QGIS/QGIS3\profiles\Grant1/python/plugins
C:/OSGeo4W/apps/qgis/./python/plugins
C:\OSGeo4W\apps\grass\grass83\etc\python
C:\OSGeo4W\bin
C:\OSGeo4W\bin\python39.zip
C:\OSGeo4W\apps\Python39\DLLs
C:\OSGeo4W\apps\Python39\lib
C:\Users\boxer\AppData\Roaming\Python\Python39\site-packages
C:\OSGeo4W\apps\Python39
C:\OSGeo4W\apps\Python39\lib\site-packages
C:\OSGeo4W\apps\Python39\lib\site-packages\win32
C:\OSGeo4W\apps\Python39\lib\site-packages\win32\lib
C:\OSGeo4W\apps\Python39\lib\site-packages\Pythonwin
C:/Users/boxer/AppData/Roaming/QGIS/QGIS3\profiles\Grant1/python
C:\Users/boxer/AppData/Roaming/QGIS/QGIS3\profiles\Grant1/python/plugins\enmapboxplugin\site-packages
C:\Users/boxer/AppData/Roaming/QGIS/QGIS3\profiles\Grant1/python/plugins\enmapboxplugin
C:\Users\boxer\AppData\Roaming\QGIS\QGIS3\profiles\Grant1\python\plugins\enmapboxplugin\enmapbox\qgispluginsupport\qps\pyqtgraph
C:\Users\boxer\AppData\Roaming\QGIS\QGIS3\profiles\Grant1\python\plugins\enmapboxplugin\enmapbox\site-packages
C:\Users\boxer\AppData\Roaming\QGIS\QGIS3\profiles\Grant1\python\plugins\enmapboxplugin\enmapbox\apps
C:\Users\boxer\AppData\Roaming\QGIS\QGIS3\profiles\Grant1\python\plugins\enmapboxplugin\enmapbox\coreapps
C:\Users\boxer\AppData\Roaming\QGIS\QGIS3\profiles\Grant1\python\plugins\enmapboxplugin\enmapbox\eo4qapps

**Comment by janzandr** [comment]
Thanks @grantboxer, we'll do testing under QGIS 3.36 asap.

**Comment by janzandr** [comment]
sure, will be an easy fix I guess
