### ISSUE TITLE
Error in create classification dataset

### ISSUE THREAD

**Issue by omkamps** [EnMAP-Box/enmap-box#869]
Dear,

For a remote sensing course I would like to use the EnMAP-Box program. I am currently testing the landcover classification but I keep getting errors in the creation of a classification dataset. I want to use a vector file as training dataset. I get the following error, also when I use the example dataset.

_Traceback (most recent call last):
File "C:\Users/okamps/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\site-packages\typeguard\__init__.py", line 903, in wrapper
retval = func(*args, **kwargs)
File "C:\Users/okamps/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapboxprocessing\algorithm\rasterizecategorizedvectoralgorithm.py", line 179, in processAlgorithm
message, success = layer.saveDefaultStyle(QgsMapLayer.StyleCategory.AllStyleCategories)
TypeError: QgsMapLayer.saveDefaultStyle(): too many arguments_

Is this anything you can help me with?

With kind regards,

Oscar Kamps
TU Delft

**Comment by janzandr** [comment]
1. I can't reproduce the error.

2. what are the QGIS and EnMAP-Box versions you are using?

Current version of QGIS is 3.34+ and EnMAP-Box v3.13 (v3.14 is released this week).

**Comment by omkamps** [comment]
I still had the older versions indeed. When updating the newest versions of QGIS and Enmap I get the following error. I will check later if this still occurs with the v3.14.  

TypeError: QgsProcessingParameterDefinition.setFlags(): argument 1 has unexpected type 'int' 
Traceback (most recent call last):
  File "C:\Users/okamps/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapboxprocessing\algorithm\build3dcubealgorithm.py", line 49, in initAlgorithm
    self.addParameterFloat(self.P_SPECTRAL_SCALE, self._SPECTRAL_SCALE, 1, True, 0, None, True)
  File "C:\Users/okamps/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapboxprocessing\enmapalgorithm.py", line 889, in addParameterFloat
    self.flagParameterAsAdvanced(name, advanced)
  File "C:\Users/okamps/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapboxprocessing\enmapalgorithm.py", line 978, in flagParameterAsAdvanced
    p.setFlags(int(p.flags()) | QgsProcessingParameterDefinition.Flag.FlagAdvanced)
TypeError: QgsProcessingParameterDefinition.setFlags(): argument 1 has unexpected type 'int'


Python version: 3.9.18 (heads/master:5eba59e, Feb  1 2024, 20:02:10) [MSC v.1929 64 bit (AMD64)] 
QGIS version: 3.36.1-Maidenhead Maidenhead, 3e589453

**Comment by janzandr** [comment]
Have you restarted QGIS after EnMAP-Box installation?
If not, please do so and retry.

**Comment by omkamps** [comment]
Yes I reinstalled QGIS 3.36 and the EnMAP-Box 3.13. 

I currently have installed QGIS3.34 and it seems to work. I can open EnMAP-Box again and run the create classification dataset function.
