### ISSUE TITLE
Process `ApplyMaskLayerToRasterLayer` fails with an `AttributeError`

### ISSUE THREAD

**Issue by Florian-Katerndahl** [EnMAP-Box/enmap-box#87]
Dear EMB-Devs,

I want to apply a binary mask layer to a multilayer raster file. I'm using the CL-Interface and my call looks like this:
```
qgis_process run enmapbox:ApplyMaskLayerToRasterLayer -- raster=20200806_LEVEL2_LND08_BOA.tif mask=mask_raster.tif outputRaster=20200806_LEVEL2_LND08_BOA_masked.tif
```

However, this fails with the following error message:
```
Traceback (most recent call last):
    File "/home/docker/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/site-packages/typeguard/__init__.py", line 903, in wrapper
      retval = func(*args, **kwargs)
    File "/home/docker/.local/share/QGIS/QGIS3/profiles/default/python/plugins/enmapboxplugin/enmapboxprocessing/algorithm/translaterasteralgorithm.py", line 340, in processAlgorithm
      writer.removeMetadata()
  AttributeError: 'RasterWriter' object has no attribute 'removeMetadata'
```

I know, that this is not a very detailed description. So if you need any more information, I'll try to provide it to you.

Cheers,
Florian

**Comment by Florian-Katerndahl** [comment]
Thanks for the quick fix @janzandr. This fixed my issue
