### ISSUE TITLE
Decorrelation stretch rendering does not work in QGIS 3.36.2 and EnMap-Box 3.14 - Python Errors 

### ISSUE THREAD

**Issue by Bilou020285** [EnMAP-Box/enmap-box#892]
Hello,

I'm trying to use the decorrelation stretch rendering tool on a raster I've load and it seems to have issues on the decorrelationstretchdialog.py code.

I've installed the latest version of QGIS (3.36.2) and the latest version of EnMap Box (3.14).

The error console message : 

```
2024-05-15T13:22:34     WARNING    Traceback (most recent call last):
              File "C:\Users\cfont\AppData\Roaming\QGIS\QGIS3\profiles\caro\python\plugins\enmapboxplugin\enmapbox\coreapps\decorrelationstretchapp\decorrelationstretchdialog.py", line 174, in onApplyClicked
              renderer = self.currentRenderer()
              ^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users\cfont\AppData\Roaming\Python\Python312\site-packages\typeguard\__init__.py", line 1033, in wrapper
              retval = func(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users\cfont\AppData\Roaming\QGIS\QGIS3\profiles\caro\python\plugins\enmapboxplugin\enmapbox\coreapps\decorrelationstretchapp\decorrelationstretchdialog.py", line 96, in currentRenderer
              extent = self.currentExtent()
              ^^^^^^^^^^^^^^^^^^^^
              File "C:\Users\cfont\AppData\Roaming\Python\Python312\site-packages\typeguard\__init__.py", line 1033, in wrapper
              retval = func(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users\cfont\AppData\Roaming\QGIS\QGIS3\profiles\caro\python\plugins\enmapboxplugin\enmapbox\coreapps\decorrelationstretchapp\decorrelationstretchdialog.py", line 69, in currentExtent
              mapSettings: QgsMapSettings = self.mMapCanvas.mapSettings()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
             AttributeError: 'NoneType' object has no attribute 'mapSettings'
```

Do you have any solution to solve this issue ? Thanks for your help !
Best regards.
Caroline

**Comment by janzandr** [comment]
Can't reproduce this. Have you restarted QGIS after updating the EnMAP-Box?
If not, please do so and try again.

**Comment by Bilou020285** [comment]
I've restarted both QGIS and my computer and the result is still the same.

**Comment by Bilou020285** [comment]
Sure ! 

![Uploading 2024-05-15_14h27_42.gif…]()

**Comment by janzandr** [comment]
Can't see the animated GIF.

**Comment by Bilou020285** [comment]
Odd, it does not seems to work either...
Maybe with PNG...

Adding an image to the canvas :
![1](https://github.com/EnMAP-Box/enmap-box/assets/59787652/6c6f151a-734b-471b-abce-e96b96d92702)

Launching EnMap Box :
![2](https://github.com/EnMAP-Box/enmap-box/assets/59787652/ee8508e9-6091-48d9-a48d-242cff134ca9)

Launching Decorrelation Stretch Rendering :
![3](https://github.com/EnMAP-Box/enmap-box/assets/59787652/2b85d435-b964-4995-a7fa-a87dcc339020)

Selecting the raster and bands :
![4](https://github.com/EnMAP-Box/enmap-box/assets/59787652/547fcc30-722f-4a52-b267-9c2820850225)

The Python error appears on the top of the canvas : 
![5](https://github.com/EnMAP-Box/enmap-box/assets/59787652/86ccf1be-ee5c-46e1-ba5c-2690f86d65e6)

Message appears into the error console : 
![6](https://github.com/EnMAP-Box/enmap-box/assets/59787652/486f4824-2ee4-409a-a10d-d03a8da835d1)

**Comment by Bilou020285** [comment]
Yes ! It's working ! Wonderful ! Thanks a lot for your help ! 👍
