### ISSUE TITLE
[QPS] latest pyqtgraph update introduces ModuleNotFoundError

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#932]
Can't start EnMAP-Box anymore:

```
Traceback (most recent call last):
  File "D:\QGIS\apps\Python312\Lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "D:\pycharm\PyCharm 2022.2.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pycharm\PyCharm 2022.2.1\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/source/QGISPlugIns/enmap-box/examples/start_enmapbox.py", line 2, in <module>
    from enmapbox.gui.enmapboxgui import EnMAPBox
  File "D:\pycharm\PyCharm 2022.2.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\source\QGISPlugIns\enmap-box\enmapbox\gui\__init__.py", line 6, in <module>
    from ..qgispluginsupport.qps.plotstyling.plotstyling import PlotStyle, PlotStyleDialog, PlotStyleButton, PlotStyleWidget
  File "D:\pycharm\PyCharm 2022.2.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\source\QGISPlugIns\enmap-box\enmapbox\qgispluginsupport\qps\plotstyling\plotstyling.py", line 48, in <module>
    from ..pyqtgraph.pyqtgraph.graphicsItems.ScatterPlotItem import renderSymbol, drawSymbol
  File "D:\pycharm\PyCharm 2022.2.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'enmapbox.qgispluginsupport.qps.pyqtgraph.pyqtgraph.graphicsItems.ScatterPlotItem'
```

![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/e20a230f-2297-43b7-8974-f3a105bc43c0)

**Comment by chippey** [comment]
Just curious if there was any update on this?  We're getting hit with this on some newer installs (using QGIS 3.38, Windows and MacOS).

**Comment by janzandr** [comment]
@jakimowb can we close this issue?
