### ISSUE TITLE
[Apply mask layer to raster layer] cannot convert float NaN to integer

### ISSUE THREAD

**Issue by vprint** [EnMAP-Box/enmap-box#95]
Hello,

Applying mask to sentinel-2 VRT give the following error.

Traceback (most recent call last):
File "C:\Users/valen/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\site-packages\typeguard\__init__.py", line 903, in wrapper
retval = func(*args, **kwargs)
File "C:\Users/valen/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapboxprocessing\algorithm\applymaskalgorithm.py", line 69, in processAlgorithm
array[invalid] = noDataValue
ValueError: cannot convert float NaN to integer

Step : 
 1) Load sentinel-2 data
2) Create a mask with "reclassify by table" tool (in my casea wetland area using low NIR value)
3) Apply the mask using "Apply mask layer to raster layer"

Result : 
The previous error is outputed

workaround : 
Convert VRT to 32 bit floating values tif using gdal warp

Sincerely,

**Comment by janzandr** [comment]
FYI - I also get an error at the same line, but a different one:

```
Traceback (most recent call last):
File "D:\source\QGISPlugIns\enmap-box\site-packages\typeguard\__init__.py", line 903, in wrapper
retval = func(*args, **kwargs)
File "D:\source\QGISPlugIns\enmap-box\enmapboxprocessing\algorithm\applymaskalgorithm.py", line 68, in processAlgorithm
array[invalid] = noDataValue
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

Anyways, I guess those two errors are related.
