### ISSUE TITLE
[Regression-based unmixing] _catboost.CatBoostError: Expected callable object or stream-like object

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#980]
Reported by @dpoursanidis via email.

Hope this email finds you well. Running unmixing in the GUI with RF works great.  But when change to CatBoost, fails. Below the message 
What i can do to fix it?

```
Algorithm 'Regression-based unmixing' finished

QGIS version: 3.28.12-Firenze

QGIS code revision: dcc633b2de

Qt version: 5.15.3

Python version: 3.9.5

GDAL version: 3.7.2

GEOS version: 3.12.0-CAPI-1.18.0

PROJ version: Rel. 9.3.0, September 1st, 2023

PDAL version: 2.5.5 (git-version: 24f78d)

Algorithm started at: 2024-09-18T09:47:06

Algorithm 'Regression-based unmixing' starting…

Input parameters:

{ 'allowWithinClassMixtures' : True, 'background' : 0, 'classProbabilities' : '', 'dataset' : 'D:/0_PLANET_imagery/CystoseiraSkyros/Regression-based_UNMIXINGs/17092024/level3Dataset.pkl', 'ensembleSize' : 10, 'includeEndmember' : True, 'mixingProbabilities' : '0.5, 0.5', 'n' : 1000, 'outputClassification' : 'D:/0_PLANET_imagery/CystoseiraSkyros/Regression-based_UNMIXINGs/17092024/CatBOOST_classification_L3_17092024.tif', 'outputFraction' : 'D:/0_PLANET_imagery/CystoseiraSkyros/Regression-based_UNMIXINGs/17092024/CatBOOST_fraction_L3_17092024.tif', 'outputFractionVariation' : 'D:/0_PLANET_imagery/CystoseiraSkyros/Regression-based_UNMIXINGs/17092024/CatBOOST_Variation_L3_17092024.tif', 'raster' : 'E:/OneDrive - ΙΔΡΥΜΑ ΤΕΧΝΟΛΟΓΙΑΣ ΚΑΙ ΕΡΕΥΝΑΣ/H2020 Blue Carbon NIVA -CHINA/0_Mapping_Cystoseira_Areas/SkyrosWork/2024_06_02_ACO_part1.tif', 'regressor' : 'from catboost import CatBoostRegressor\nregressor = CatBoostRegressor(n_estimators=100)', 'robustFusion' : True, 'sumToOne' : False }


Create ensemble

Traceback (most recent call last):
File "C:\Users\DimitrisPoursanidis\AppData\Roaming\Python\Python39\site-packages\typeguard\__init__.py", line 1033, in wrapper
retval = func(*args, **kwargs)
File "C:\Users/DimitrisPoursanidis/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\enmapboxplugin\enmapboxprocessing\algorithm\fitregressoralgorithmbase.py", line 88, in processAlgorithm
regressor.fit(dump.X, dump.y.ravel())
File "C:\Users\DimitrisPoursanidis\AppData\Roaming\Python\Python39\site-packages\catboost\core.py", line 5703, in fit
return self._fit(X, y, cat_features, text_features, embedding_features, None, sample_weight, None, None, None, None, baseline,
File "C:\Users\DimitrisPoursanidis\AppData\Roaming\Python\Python39\site-packages\catboost\core.py", line 2317, in _fit
with log_fixup(log_cout, log_cerr), \
File "C:\PROGRA~1\QGIS32~1.12\apps\Python39\lib\contextlib.py", line 117, in __enter__
return next(self.gen)
File "C:\Users\DimitrisPoursanidis\AppData\Roaming\Python\Python39\site-packages\catboost\core.py", line 127, in log_fixup
_set_logger(_get_stream_like_object(log_cout), _get_stream_like_object(log_cerr))
File "C:\Users\DimitrisPoursanidis\AppData\Roaming\Python\Python39\site-packages\catboost\core.py", line 117, in _get_stream_like_object
raise CatBoostError(
_catboost.CatBoostError: Expected callable object or stream-like object
```

**Comment by dpoursanidis** [comment]
Shall i test all available algorithms using the GUI and provide feedback?
