### ISSUE TITLE
numpy.core._exceptions._ArrayMemoryError

### ISSUE THREAD

**Issue by jakimowb** [EnMAP-Box/enmap-box#995]
The ''Raster layer bounding polygon' processing algorithm fails with largs datasets, e.g. a VRT of 5000x21000 px showing parts of an EnMAP Orbit.

I think it would be good if this algorithm would work line-wise, instead of loading everything into the local memory.

@janzandr  An example VRT can be found on the EnMAP-Drive -> EnMAP data cube for Namibia

```
Traceback (most recent call last):  
File "C:\Users/geo_beja/AppData/Roaming/QGIS/QGIS3\profiles\EnMAP-Box/python/plugins\enmapboxplugin\enmapboxprocessing\algorithm\rasterboundingpolygonalgorithm.py", line 51, in processAlgorithm  
array = reader.array()  
^^^^^^^^^^^^^^  
File "C:\Users/geo_beja/AppData/Roaming/QGIS/QGIS3\profiles\EnMAP-Box/python/plugins\enmapboxplugin\enmapboxprocessing\rasterreader.py", line 275, in array  
array = self.arrayFromPixelOffsetAndSize(xOffset, yOffset, width, height, bandList, overlap, feedback)  
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  
File "C:\Users/geo_beja/AppData/Roaming/QGIS/QGIS3\profiles\EnMAP-Box/python/plugins\enmapboxplugin\enmapboxprocessing\rasterreader.py", line 260, in arrayFromPixelOffsetAndSize  
return self.arrayFromBoundingBoxAndSize(boundingBox, width, height, bandList, overlap, feedback)  
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  
File "C:\Users/geo_beja/AppData/Roaming/QGIS/QGIS3\profiles\EnMAP-Box/python/plugins\enmapboxplugin\enmapboxprocessing\rasterreader.py", line 241, in arrayFromBoundingBoxAndSize  
array = Utils.qgsRasterBlockToNumpyArray(block=block)  
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  
File "C:\Users/geo_beja/AppData/Roaming/QGIS/QGIS3\profiles\EnMAP-Box/python/plugins\enmapboxplugin\enmapboxprocessing\utils.py", line 172, in qgsRasterBlockToNumpyArray  
array = np.frombuffer(np.array(block.data()), dtype=dtype)  
^^^^^^^^^^^^^^^^^^^^^^  
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 401. MiB for an array with shape (420000000,) and data type uint8  

Execution failed after 347.91 seconds (5 minutes 48 seconds)

```

**Comment by janzandr** [comment]
I'll have a look at it, but in the error message it says: _Unable to allocate **401. MiB**_
400 megabytes isn't that much.

**Comment by janzandr** [comment]
Alright, the algo reads all bands at once. I would propose to add a band selection parameter to limit the computation to a single band, which is sufficient for most cases.
